### ISSUE TITLE
Automate the creation of a data factory

### ISSUE THREAD

**Issue by baf2117** [Azure/Azure-DataFactory#100]
Hello
I'm want to automate the creation of a data factory pipeline with data flow elements through sdk, but I can't find how to create this type of pipeline in any docs. There are some way to automate the creation of this type of pipeline?

**Comment by fhljys** [comment]
Have you checked these docs? 
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-rest-api
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-python
