### ISSUE TITLE
Update to Azure Data Factory Trigger breaks existing pipeline

### ISSUE THREAD

**Issue by michaelhambe** [Azure/Azure-DataFactory#102]
Hi,

According to the documentation, an event trigger needs:
-an Azure Subscription
-a Storage Account Name
-either a blob starts with or blob ends with
https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-event-trigger#

Using these parameters, I have successfully created the pipeline I need, In that the pipeline looks for files dropped into any container of the storage account.

However it looks like the ADF code has been updated before the documentation because now my trigger requires the Container Name as a compulsory parameter.

Is is possible to make the Container Name Dependency an option?

Thanks
Mike

**Comment by fhljys** [comment]
still have issues?

**Comment by michaelhambe** [comment]
This was a while ago - from memory, Microsoft enabled setting the trigger at the container level, after accepting a warning

**Comment by fhljys** [comment]
Turns out you can select "all containers" in UX, which is the same as make it optional. And there is a warning for this option: 
![image](https://user-images.githubusercontent.com/18674958/112074149-9aa5e380-8bb0-11eb-9543-b981d0859e34.png)
