### ISSUE TITLE
Unable to get ADF to show published changes with GIT integration

### ISSUE THREAD

**Issue by mshamann** [Azure/Azure-DataFactory#106]
I am working with Azure datafactory and the Git Integration with Azure Devops. 

At first, the publish functionality was working. It would create the linked services connections in an adf_publish branch and then that would be published to the actual data factory. 

However, when I added my Datasets and Pipelines, it seems to fail at showing them in the Azure Datafactory. The adf_publish branch shows the changes properly, but the they are not appearing in the actual datafactory. 

The pipelines all run in debug mode with success, the linked services all connect properly as well. 

Master Branch 
![image](https://user-images.githubusercontent.com/22153608/62636683-99527500-b8ff-11e9-8a9b-440baf743741.png)

Data factory view

![image](https://user-images.githubusercontent.com/22153608/62636738-b9823400-b8ff-11e9-8c3a-13123f684684.png)

All of those show properly in the adf_publish branch on my repo, and validation succeeds. When I try to publish it says it was successful. If I delete something and publish it shows the change in the list of publish changes. But it does not reflect the changes in the Data Factory.

**Comment by syedhamjath** [comment]
Publishing from Azure data factory is based on ARM template. ADF UI always cleans and deploys the ARM template. If an error occurs while deploying an ARM template then we find empty data factory. To find what is the issue, use ARM template from adf_publish directory and deploy using powershell.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy

Note : Use Incremental mode to preseve other resources in resource group
https://docs.microsoft.com/en-us/azure/azure-resource-manager/deployment-modes

**Comment by fhljys** [comment]
Suppose you are not experiencing this anymore.  We can reopen this if someone hit this again.

**Comment by aturlov-alta** [comment]
Not sure if you can reopen this or a new issue is required. I have a slightly different flavour of this problem: I deploy ADF changes via an ADO  YAML pipeline using an automated publishing with the data utilities package. The pipeline has a build and deploy stages. Build stage creates a pipeline artifact that contains all generated ARM templates and the deploy stage performs an ARM deployment from the pipeline artifact using those ARM templates. Both stages complete successfully. I go to ADF, switch to live mode and the changes are not there. They never appear as if the deployment never happened. If I run the pipeline again, they changes will appear correctly. Any suggestions?
