### ISSUE TITLE
DataFlow can't connect to sql datasheet

### ISSUE THREAD

**Issue by r3dr4gon** [Azure/Azure-DataFactory#109]
I have a data flow process that put data into a sql database.
However, as of today (it last worked at the 23 AFAIK), the process is failing with the message:
{
    "message": "Failure 2019-08-27 14:29:14.936 failed AppManager.submitExecutorRequest, run=81b9185d-7e49-49f3-bd30-443bed3b659a, errorMessage=DF-SRC-002 'database' (Database name) is required",
    "failureType": "UserError",
    "target": "Process 2 SQL"
}

When checking in the connection setting, "test connection" returns success.
When checking in the sql dataset, "test connection" returns success and I can use "privew data" and see the table.
Is there a way to fix this? as far as i see there is no place for me to insert "Database name", and all the connections are working as expected.

**Comment by r3dr4gon** [comment]
An update, this is working when the "Linked Service" is entered manualy and not via AKV.
My key valut value is:
Server=tcp:server_name.database.windows.net,1433;Database=database_name;User ID=user_name;Password=***;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30

**Comment by JoeTannouri** [comment]
Any news on this? I'm facing the same issue with "Linked Service" entered manually:
DF-SRC-002 - 'tableName' (Table Name) is required

**Comment by JoeTannouri** [comment]
Thank you @r3dr4gon for the reply but can you mention the solution provided by support?

**Comment by JoeTannouri** [comment]
And BTW the email you provided is bouncing.

**Comment by r3dr4gon** [comment]
There was no solution, it was a bug that was fixed.
ooh, unfortantly this was the mail i used to talk to them, maybe it was changed.
