### ISSUE TITLE
Pipeline stuck in "PendingUpdate" provisioning status on deployment

### ISSUE THREAD

**Issue by itstaby** [Azure/Azure-DataFactory#11]
I am a having a problem for the last couple of hours, upon deployment of a pipeline, it goes into the provisioning state and then gets stuck there.

It then eventually fails with one of these two errors:"Failed to reach service" or "Internal Server Error."
The state of the pipeline is stuck at "Pending Update"

I have even created a Data Factory from scratch, created new linked services and data sets, and created the pipeline within that data factory, and the same thing is happening.

What can be causing this issue?

I have to add that I was using DF and deploying pipelines and everything was going well, this was a sudden issue.

**Comment by gauravmalhot** [comment]
This issue is fixed now... Let us know if you are still seeing the issue.

**Comment by manub22** [comment]
What was the issue? I also facing the same issue.
