### ISSUE TITLE
Deploy ADF alerts via ARM

### ISSUE THREAD

**Issue by carmeleve** [Azure/Azure-DataFactory#110]
Hi,

I've set up a smart alert in ADF for a low pipeline frequency, and I want to deploy the alert as part of my ARM deployment. 

I can find examples of deploying app insights smart alerts, but none for ADF. I've tried exporting the ADF and resource group templates, but see the following message:

![image](https://user-images.githubusercontent.com/39550338/64003875-2191f780-cb05-11e9-821f-4b94a7520ad1.png)

Has anyone got any advice/examples of this working? Or an update on when the the alerts will show up in exported templates?

Thanks!

**Comment by fhljys** [comment]
Still hit this?

**Comment by fhljys** [comment]
Close due to inactivity.
