### ISSUE TITLE
GitHub Token Validation Failed to fetch

### ISSUE THREAD

**Issue by nareshynn** [Azure/Azure-DataFactory#114]
Hi,

we have Github enterprise server in azure and it is able to connect azure devops services. we can able to configure service connection and github connections in azure devops project settings. 
when we are trying to configure repos in azure data factory repos are not coming and while giving PAT authentication we are getting GitHub Token Validation Failed to fetch error. can you please help.

**Comment by nareshynn** [comment]
Hello Team,

can some one help me on this please

**Comment by SYETUKURI** [comment]
facing the same issue. did anyone find the root cause

**Comment by habeebtc** [comment]
This seems to be something a colleague of mine just ran into as well.

**Comment by Konvay** [comment]
Has there been any update or workaround for this? I am getting this same error.

**Comment by nareshynn** [comment]
please chec with correct repository Name. it worked for me.

**Comment by Konvay** [comment]
I'm trying to connect to a GitHub Enterprise account. After entering our account URL and I put in my personal account, it says I don't have access and prompts for an access token. I've generated one and when trying to have the ADF project accept the token, I get failed to fetch.

There's no place for me to put the repository name yet.

**Comment by fhljys** [comment]
Seems the issue has been resolved right? @konvay

**Comment by thrushika-s** [comment]
Hi,  
I am unable to configure repos in azure data factory using GitHub enterprise server.
I am getting GitHub Token Validation Failed to fetch error.
Can someone help look into this issue? 

Thank you.
