### ISSUE TITLE
Import schemas in Copy Data activity maps based on column order and not column name

### ISSUE THREAD

**Issue by billyswitzer** [Azure/Azure-DataFactory#115]
To reproduce:

Create two tables with the same columns overall but with the columns in a different order. Set up a pipeline to use the Copy Data activity with one table as the Source and the other as the Sink. Under Mapping, click Import Schemas.

Result:

The columns will be mapped to each other based on column order.

Desired result:

Would like Azure Data Factory to attempt to match columns based on name similar to the behavior in SSIS.

**Comment by fhljys** [comment]
Are you still experiencing this?

**Comment by fhljys** [comment]
Close due to inactivity.
