### ISSUE TITLE
Editing mappings in Copy Data activity after importing schemas resets other mapped columns

### ISSUE THREAD

**Issue by billyswitzer** [Azure/Azure-DataFactory#116]
To reproduce:

Set up a pipeline with a Copy Data activity. Under Mapping, click Import schemas, note the preselected mappings, then edit some of the mappings.

Result:

Mappings other than the one the user is editing are updated. This sometimes occurs in mapped columns which have been updated previously by hand.

Workaround:

Note: This only seems to occur when editing mappings created by the Import Schemas button. A workaround is to not use the Import Schemas button and add each column mapping manually. A correlated issue is that often the combo boxes to select columns from the Source and Sink appear offscreen, so I had to add several blank mappings and then delete the unused ones after mapping all 43 of the columns in my Source and Sink tables.

**Comment by fhljys** [comment]
Are you still experiencing this?

**Comment by billyswitzer** [comment]
I don’t think so but I wanted to set up a test and I have not had time to do so. I will be out of the office most of this week for a family emergency and will likely not have time this week either.

To Repro:

Create two tables with identical column names and data types but with a differing column order.

Table1
Col1
Col2
Col3

Table2
Col2
Col3
Col1

Set up a Copy Data task from Table1 to Table2 and click Import Schema. What was happening when I opened the ticket was that Table1.Col1 would map to Table2.Col2, etc., rather than Table2.Col1.

I believe I opened this ticket in mid-2019. I believe this has been resolved since then but again I have not had a chance to set up the specific scenario. In the application there are 44 columns in the tables in the pipeline in question. Also in our scenario, the source table is located on prem and the target table is an Azure Managed Instance.


Thanks for your follow-up.

Billy


From: Fang Liu ***@***.***>
Sent: Sunday, March 28, 2021 12:08 AM
To: Azure/Azure-DataFactory ***@***.***>
Cc: Billy Switzer ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL EMAIL] Re: [Azure/Azure-DataFactory] Editing mappings in Copy Data activity after importing schemas resets other mapped columns (#116)

NOT an FMCNA email - External email

Are you still experiencing this?

**Comment by Miwa199739** [comment]
Thanks for the detailed repro steps!
We set the exact same testbed, and test results showed UI map source and sink column default by name. (demoed in the following GIF)
![import mapping](https://user-images.githubusercontent.com/14820833/114118293-23e04880-991b-11eb-81b6-ed4c28e6a0e3.gif)
There may be chances that the mapping is default by order a long time ago (2019), and it's been corrected now. :)
Let us know if any blockers in your solution building with copy activity, thanks!

**Comment by billyswitzer** [comment]
Thank you so much for your follow-up!

From: Wang Zhang ***@***.***>
Sent: Thursday, April 8, 2021 10:31 PM
To: Azure/Azure-DataFactory ***@***.***>
Cc: Billy Switzer ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL EMAIL] Re: [Azure/Azure-DataFactory] Editing mappings in Copy Data activity after importing schemas resets other mapped columns (#116)

NOT an FMCNA email - External email

Thanks for the detailed repro steps!
We set the exact same testbed, and test results showed UI map source and sink column default by name. (demoed in the following GIF)
[import mapping]<https://user-images.githubusercontent.com/14820833/114118293-23e04880-991b-11eb-81b6-ed4c28e6a0e3.gif>
There may be chances that the mapping is default by order a long time ago (2019), and it's been corrected now. :)
Let us know if any blockers in your solution building with copy activity, thanks!
