### ISSUE TITLE
PowerShell does not work for Switch Activity in the Pipeline Data Factory V2 (Set-AzDataFactoryV2Pipeline)

### ISSUE THREAD

**Issue by rezasoltanirezvandeh** [Azure/Azure-DataFactory#117]
Set-AzDataFactoryV2Pipeline creates Data Factory Pipelines yet if there is a Switch Activity, the Pipeline would not be the same as you expected.

After Executing the command successfully, I could see the blank Pipeline yet the source code was different from my original Json file, seems it does not like the Switch activity tags and it got replaced with wrong tags by eliminating the typeProperties and replacing the "type": "Switch" to "type": "activity" ! the rest of the properties like the case section was gone too.

**Comment by BDunTG** [comment]
We're seeing the same exact issue which is preventing the use of automated deployments of pipelines using PowerShell commands. Looks to be a bug that needs to be resolved.

**Comment by fhljys** [comment]
It should be a powershell version issue. Have you tried upgrade the powershell to the latest version?
