### ISSUE TITLE
Web activity basic authentication dissapeared

### ISSUE THREAD

**Issue by RudyEvers** [Azure/Azure-DataFactory#120]
Hi,

What happende to the authentication possibilities of the control flow component Web Activity. All of a sudden the authentication method Basic dissapeared from the setting menu. Which means that the pipeline is not working anymore! 

Please come with a solution to fix this, because we can't change the API we are calling.

Best regards

![issue_webactivity](https://user-images.githubusercontent.com/38738862/67772844-11da5500-fa5b-11e9-86e3-1e5667ac44e3.PNG)

**Comment by fhljys** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/18674958/109831290-3f9c6300-7c7a-11eb-8a07-63ebefb33e84.png)
