### ISSUE TITLE
Merging resources from Data Factory into an already setup code repo

### ISSUE THREAD

**Issue by kvinther** [Azure/Azure-DataFactory#122]
I have a ADF with several resources. At some point I setup code repo integration with Azure DevOps git. However, initially I did not select the option to "add existing resources to git".

How do I add the Data Factory resources (stored directly in ADF) to a branch in the associated git repo?

Alternatively, can I remove the git integration and then add it again - this time selecting the above mentioned option?

**Comment by fhljys** [comment]
Sounds like possible.  But I think it would be better to try it with a test factory first.

**Comment by fhljys** [comment]
Close due to inactivity.
