### ISSUE TITLE
Source table column having special characters failed to load table

### ISSUE THREAD

**Issue by Kannancsq** [Azure/Azure-DataFactory#130]
We have table columns with special characters like (spaces, #). When to load data from such tables Azure data factory failed to load table.

Error : "Table with special character in the column name"

Can you please advise us with workaround or alternative solution to load tables which are having special characters in columns.

**Comment by fhljys** [comment]
You can encode your column name. Based on the data source type, encode name is different. For example, Sql is using [], mySql ``
