### ISSUE TITLE
Typo in adding new mapping

### ISSUE THREAD

**Issue by Grayincarnation** [Azure/Azure-DataFactory#132]
Hello,

Looks like adding a new mapping to the Mapping section of a Copy Data activity via the "+" sign and of an object type, adds the object with a data type of "obejct".

![add_obejct_1](https://user-images.githubusercontent.com/31732465/68681359-53e3ba80-0574-11ea-9e74-279177c19f97.JPG)
![add_obejct_2](https://user-images.githubusercontent.com/31732465/68681361-547c5100-0574-11ea-942e-196dcd23c05f.JPG)

Thanks,
Giray

**Comment by fhljys** [comment]
Fixed. Thanks for reporting.
