### ISSUE TITLE
ADF v2 - OData and open types

### ISSUE THREAD

**Issue by adamsow** [Azure/Azure-DataFactory#133]
Hi,
I'm trying to set ADF with OData as dataset but can't find option to include open types in dataset settings. The OData API I'm trying to connect is using open types and when I'm previewing data in ADF, the properties marked in $metadata as 'OpenType = true' are just not there. Is there a way to include open types in dataset?

BR,
Adam

**Comment by fhljys** [comment]
Are you still waiting for this feature?

**Comment by fhljys** [comment]
Close due to inactivity.
