### ISSUE TITLE
github organization repositories are not listed

### ISSUE THREAD

**Issue by toshi-miura** [Azure/Azure-DataFactory#135]
I have permission from the organization, but it is not displayed.
My private repositories are displayed.
The current situation is that it invites company members to personal repositories, but is there a good way to do that?

**Comment by nshahapplefcu** [comment]
Hi - did you find any answers to this question?  I am running into the same issue.

**Comment by migonidec** [comment]
Hey @nshahapplefcu, 
I had the same issue, it appeared (for my case) to be an authentication error. I had to disconnect from Azure, Github and empty my cookies to force my org repos to appear.

**Comment by nshahapplefcu** [comment]
@migonidec - did you have to register anywhere?  After emptying the cookies, I am still not able to see internal repositories created under organization.

**Comment by nshahapplefcu** [comment]
No, I am all set.  I just had to enter my ORGNAME/REPONAME.
It was my mistake.

**Comment by fhljys** [comment]
Good to know. Thanks.
