### ISSUE TITLE
How to call PowerShell Script and Azcopy Script with in Single Custom actvity command 

### ISSUE THREAD

**Issue by kyrmca** [Azure/Azure-DataFactory#142]
I have two commands one is **PowerShell script** this script will check if the file is exist or not in source,
Second command is **Azcopy script** if the file is exist in source it will copy source file into destination folder. These two scripts i need to call  in ADF V2 single **custom activity command**.So could you please help on this issue.

**Comment by fhljys** [comment]
Please reference this doc https://docs.microsoft.com/en-us/azure/data-factory/transform-data-using-dotnet-custom-activity#executing-commands
