### ISSUE TITLE
ARM deployment for Data Factory with share integration runtime

### ISSUE THREAD

**Issue by jchomarat** [Azure/Azure-DataFactory#144]
Hello,

Here is the use case I am trying to implement:

-  I have already a data factory resource set up (let's call it ADF1). This data factory resource has an integration runtime set up (called RT1).

- I want to have an ARM templates available for others that do the following:
    - Creates another data factory resource (in another resource group), called ADF2
    - Shares RT1 from ADF1 to ADF2
    - Adds RT1 to ADF2

I need then 3 steps in my ARM template

This templates receives as input 2 parameters
* 

1. Create ADF2

` {  
        "name":"ADF2",
        "apiVersion":"2018-06-01",
        "type":"Microsoft.DataFactory/factories",
        "location":"REGION",
        "identity":{  
            "type":"SystemAssigned" 
        },
        "properties": {},
        "resources": []
}
`

2. Adds permission on RT1 for ADF2
`
{
        "type": "Microsoft.DataFactory/factories/integrationRuntimes/providers/roleAssignments",
        "apiVersion": "2018-09-01-preview",
        "name": "[concat('ADF1", '/', 'RT1', '/Microsoft.Authorization/', guid(uniqueString('ADF1')))]",
        "dependsOn": [
          "[resourceId('Microsoft.DataFactory/factories', 'ADF1')]"
        ],
        "properties": {
            "roleDefinitionId": "[concat('/subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Authorization/roleDefinitions/', 'b24988ac-6180-42a0-ab88-20f7382dd24c')]",
            "principalId": "[reference(concat('Microsoft.DataFactory/factories/', 'ADF2'), '2018-06-01', 'Full').identity.principalId]",
            "scope": "[resourceId('Microsoft.DataFactory/factories/integrationRuntimes', 'ADF1', 'RT1')]"
        }
}
`

3. Adds the RT1 to ADF2

`
{
        "type": "Microsoft.DataFactory/factories/integrationRuntimes",
        "name": "[concat('ADF2', '/', 'RT1')]",
        "apiVersion": "2018-06-01",
        "dependsOn": [
          "[resourceId('Microsoft.DataFactory/factories/integrationRuntimes/providers/roleAssignments', 'ADF1', 'RT1', 'Microsoft.Authorization', guid(uniqueString('ADF1)))]"
        ],
        "properties": {
          "type": "SelfHosted",
          "typeProperties": {
            "linkedInfo": {
              "resourceId": "[resourceId('Microsoft.DataFactory/factories/integrationRuntimes', 'ADF1', 'RT1')]",
              "authorizationType": "RBAC"
            }
          }
        }
      }
`

So bacially, the third step is dependent on the 2nd one.

My issue is that both tasks are run at the same time, so it tries to add the RT at the same times it tries to give permission - it's like the dependency is not picked up.

So to reproduce, you need to
1. Create ADF1
2. Adds RT1
3. Run the previous arm template with both parameters.

Thanks for your help

**Comment by fhljys** [comment]
Looks same issue as this one. #207

**Comment by jchomarat** [comment]
Is there someone monitoring this repo and these issues?

**Comment by fhljys** [comment]
Not very active. I think. But there are other channels. Reference this: https://github.com/Azure/Azure-DataFactory/issues/223
