### ISSUE TITLE
ARM Template deployment with Special characters!!

### ISSUE THREAD

**Issue by videepthMSFT** [Azure/Azure-DataFactory#146]
I currently have an ARM template of ADF which takes adfname, sql and storage account conn strings as inputs.

Adf deployment is being done through devops pipeline AzureResourceGroupDeployment Task 

Template internally has special characters "Año" in source mapping of Copy Activity. But after the deployment, the mapping is getting converted into something like this., A�o and my copy is failing in higher environments.

Can you please help here.
![image](https://user-images.githubusercontent.com/20475543/71384338-cb424a80-2606-11ea-8265-923ef683413a.png)
![image](https://user-images.githubusercontent.com/20475543/71384358-ddbc8400-2606-11ea-9323-de87f25a935d.png)

**Comment by henrikamnas** [comment]
Same problem here, did you manage to solve it?

**Comment by larshem** [comment]
Same problem. Did anyone solve this?

**Comment by larshem** [comment]
I ended up saving the paramter json file using notepad++ witn UTF-8 encoding.

**Comment by fhljys** [comment]
Seems it is already resolved.
