### ISSUE TITLE
Adding/Saving LinkedService pushes to adf_publish?

### ISSUE THREAD

**Issue by Lutando** [Azure/Azure-DataFactory#148]
I am trying to set up CI CD flow for ADF (Azure DataFactory) from a development working instance to a production instance that is not connected by git, the production instance gets updated by CI/CD trigger on `adf_publish` that applies those ARM templates onto the ADF production instance.

I Pretty much have set up everything similarly in how [this](https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#automate-continuous-integration-with-azure-pipelines-releases) picture describes it. 

We have a pipeline/release definition that triggers on `adf_publish` being changed. My problem is that when you save a new linked service in ADF (dev) it will actually add that linked service as a partial ARM template in the `adf_publish` branch in the `PartialArmTemplates` thereby triggering a release to be pushed to production. Why does it do this? I only want to push to `adf_publish` when I click the publish button on my development datafactory instance. Do you suggest I add an exclude filter for this folder so that the build does not trigger for this LinkedService being saved?

**Comment by fhljys** [comment]
I think if you don't need change, you could exclude it. 
https://github.com/MicrosoftDocs/azure-docs/issues/60737
