### ISSUE TITLE
ADLS Gen2 event trigger triggering twice (on FlushWithClose and CreateFIle API calls)

### ISSUE THREAD

**Issue by ACorredoira** [Azure/Azure-DataFactory#152]
My trigger on ADLS Gen2 is triggering twice for the creation of a single file. 

The event based trigger for ADLS Gen2 is reacting to both the CreateFile and FlushWithClose events. This could be prevented by filtering to only include the FlushWithClose events. Filtering will prevent multiple events triggering on the same file. 

My non-ideal quickfix/workaround untill this issue is resolved will be to wrap the pipeline in a temporary pipeline with an execute pipeline activity only executing when the TriggerBody().event.data.api is equal to FlushWithClose. 

From https://docs.microsoft.com/nl-nl/azure/event-grid/event-schema-blob-storage: 
"If you want to ensure that the Microsoft.Storage.BlobCreated event is triggered only when a Block Blob is completely committed, filter the event for the FlushWithClose REST API call. This API call triggers the Microsoft.Storage.BlobCreated event only after data is fully committed to a Block Blob. To learn how to create a filter, see Filter events for Event Grid."

**Comment by rohank-proarch** [comment]
Is this issue solved? I have filtered the events for FlushWithClose but now while uploading file from Azure Storage Explorer to data lake I receive PutBlob API.
