### ISSUE TITLE
Error in Set Variable Activity

### ISSUE THREAD

**Issue by Balachander1998** [Azure/Azure-DataFactory#154]
Hi @msftclas 
  I am Using  Azure Data Factory V2  When a Set Variable Activity Gets failed IT  doesn't trigger the Web Activity present though i joined the Web Activity and Set Variable Activity. Please try to resolve this issue.
<img width="595" alt="issue" src="https://user-images.githubusercontent.com/41260222/74025319-b4df2b00-49c9-11ea-9da7-9e39d3692ab4.png">

**Comment by StevenDown** [comment]
Hi @Balachander1998,

Having a quick read of your pipeline- I think that you need to set the output from [Set variable2] to 'on completion', as this item is also linked to the [Failure Pipeline].

The [Failure pipeline] looks to need 3 inputs before it will be triggered, and the [Set variable2] is unlikely to failure in the chain.

**Comment by Balachander1998** [comment]
Hi @StevenDown 
 Thanks for the comment Now i have three different web activity for look-up, set variable and the if_activity and it works fine.
