### ISSUE TITLE
Greenplum connector does not recognize column types properly

### ISSUE THREAD

**Issue by kartas39** [Azure/Azure-DataFactory#159]
I am doing simple copy task from Greenplum to avro file stored at blob storage. Data factory UI shows all columns as strings, however in Greenplum they are different - numerics, timestamps etc

**Comment by kartas39** [comment]
Does anyone look at this repo at all?

**Comment by fhljys** [comment]
Are you still hitting this issue?

**Comment by fhljys** [comment]
Close due to inactivity.
