### ISSUE TITLE
Cannot Execute Pyspark Scripts

### ISSUE THREAD

**Issue by harrypraneeth** [Azure/Azure-DataFactory#16]
To execute pyspark scripts using spark-submit method, we need to call --py-files instead of --jarfile and there is no need for main class  when using pyspark scripts. However cannot modify the code to get it working with PySpark scripts.

**Comment by gauravmalhot** [comment]
Hey Harry

What issue are you facing in modifying the code for executing pyspark scripts?

Thanks

**Comment by waynesx** [comment]
Please add support to execute pyspark spark scripts.

**Comment by waynesx** [comment]
Just added support for python spark, and other options of spark-submit, for example --files, --packages, --driver-cores etc.
