### ISSUE TITLE
ADF SFTP sink error - UserErrorSftpPathNotFound errorCode:2200

### ISSUE THREAD

**Issue by AlbertDove** [Azure/Azure-DataFactory#160]
Hi 

I'm raising this as an issue since it was widely reported here: https://feedback.azure.com/forums/270578-data-factory/suggestions/18742906-support-sftp-as-sink

This is the error i'm getting

{
    "errorCode": "2200",
    "message": "Failure happened on 'Sink' side. ErrorCode=UserErrorSftpPathNotFound,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Can't find SFTP path '/vibranium/connectedexplora/Year=2020/Month=2/Day=11/Con_Exp_Cust_View_5.parquet.27d8a303480e4b67ad0cf038e30092b4'. Please check if the path exists. If the path you configured does not start with '/', note it is a relative path under the given user's default folder .,Source=Microsoft.DataTransfer.ClientLibrary.SftpConnector,''Type=Renci.SshNet.Common.SftpPathNotFoundException,Message=vibranium/connectedexplora/Year=2020/Month=2/Day=11/Con_Exp_Cust_View_5.parquet.27d8a303480e4b67ad0cf038e30092b4,Source=Renci.SshNet,'",
    "failureType": "UserError",
    "target": "CopyDataFromPublishToConnectedVideo",
    "details": []
}

**Comment by fhljys** [comment]
Are you still experiencing this?

**Comment by fhljys** [comment]
Close due to inactivity.
