### ISSUE TITLE
ADF v1 to v2 Migration issue 

### ISSUE THREAD

**Issue by FaiqueAli** [Azure/Azure-DataFactory#162]
Hi everyone,

Currently I am trying to migrate my data factory version from v1 to v2 by using tool "Azure Data Factory v1 to v2Migration Tool", I have downloaded and installed the tool from 
https://www.microsoft.com/en-us/download/confirmation.aspx?id=57269

But when I run it I get the error.

> Unable to connect with to azure with the specified source credentials.
> the user does not have access to specified subscriptionID ressourceGroup, or dataFactory.

I made following changes in my linked service.
1)destination is created with linked services having working connection strings
2) Service name is also exactly same as ADF 1, but still facing the same issue  having popup window..

any help will be appreciated..

Thanks

**Comment by fhljys** [comment]
Is this resolved?

**Comment by fhljys** [comment]
Close due to inactivity.
