### ISSUE TITLE
Can't login ADF UI V2 using Google Chrome or Microsoft Edge

### ISSUE THREAD

**Issue by mataralhawiti** [Azure/Azure-DataFactory#163]
whenever I try to access ADF portal via Google Chrome or Microsoft Edge, I got an error ( very quick I can't catch ). It's something to do with "Failed xxxx" but I can't catch it.
It will eventaully redirect me to :

https://adf.azure.com/accesstoken.html

I'm able to access ADF portal with no issues in Firefox.

**Comment by arfankgp** [comment]
I am also facing the same issue since couple of days. My colleague also reported the same issue.

**Comment by ushabapat** [comment]
Any update on this. We are facing the similar issue at our end.

**Comment by Ashish-Jovial** [comment]
I also face this issues and after many iterations I able to log in.

**Comment by ftijtaddeo** [comment]
Had the same issue.  Turned out that 3rd party cookies were blocked in the browser settings.  Enabling that allowed ADF to load.

**Comment by vegazbabz** [comment]
Still an issue with Chrome. Enabled 3rd party cookies, cleared cache and cookies, but still having that problem. Opened Edge and it worked fine.

**Comment by fhljys** [comment]
Please check this document. https://docs.microsoft.com/en-us/azure/data-factory/data-factory-ux-troubleshoot-guide#adf-ux-not-loading If it doesn't help, create support ticket to Microsoft.
