### ISSUE TITLE
ADF -> Log Analytics Json Data Merge

### ISSUE THREAD

**Issue by panovattack** [Azure/Azure-DataFactory#164]
I am attempting to manipulate Log Analytics Query Results and hitting a road block...not really sure where to ask, so please point me in the correct direction if this is not it.   I've been banging my head against the wall for about a week on this one.  I figured out how to do this via a series of web activities and 3 nested pipelines, but Web Activities dont support the data volume the copy activity does.  

The REST API for Log Analytics output is of the form:

{
  "tables": [
    {
      "name": "PrimaryResult",
      "columns": [
        { "name": "Category", "type": "string" },
        { "name": "count_", "type": "long" }
      ],
      "rows": [
        [ "Administrative", 20839 ],
          ...
        [ "ServiceHealth",  11    ]
      ]
    }
  ]
}

I want to create a JSON object of the form

 [{"Category":"Administrative", "count_": 20839},{"Category":"ServiceHealth", "count_": 11}]

Any ideas?  Again, if this is the wrong forum, please let me know and  I will adjust accordingly.

**Comment by fhljys** [comment]
Is this resolved?

**Comment by fhljys** [comment]
Close due to inactivity.
