### ISSUE TITLE
REST linked service, dataset, copy activity don't allow client cert

### ISSUE THREAD

**Issue by iampeterdaniels** [Azure/Azure-DataFactory#167]
I have been unable to find a place to configure a PFX client cert when using the REST linked service/dataset in a copy activity.  Was forced to revert to basic HTTP, which has it's own issues.

**Comment by iampeterdaniels** [comment]
Same issue as #169

**Comment by fhljys** [comment]
You could use this website for feature request: https://feedback.azure.com/forums/270578-data-factory

**Comment by fhljys** [comment]
@linda33wj , any idea?

**Comment by awhitford-cip** [comment]
> You could use this website for feature request: https://feedback.azure.com/forums/270578-data-factory

See https://feedback.azure.com/d365community/idea/5555b27e-f146-ec11-a819-0022484e8090

**Comment by fhljys** [comment]
Tracking with idea website.
