### ISSUE TITLE
Azure DF Speed issue oracle to blob storage

### ISSUE THREAD

**Issue by MinaS20** [Azure/Azure-DataFactory#168]
Hi All,
I am experiencing since last week a lot of troubles with data factory

it is very slow and when the load is finished it stays in progress without writing a row.

I am loading data from oracle DB to azure blob storage and I have noticed that writing to sink is taking too much time

Could you please help me with that?

Thanks

**Comment by fhljys** [comment]
Hope this doc helps. https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-performance-features
And there is also a perf feedback in the monitoring part. You could provide your feedback there.
