### ISSUE TITLE
Add Certificate Authentication to REST Dataset

### ISSUE THREAD

**Issue by pacific202** [Azure/Azure-DataFactory#169]
I am using the ADP REST API (ADP is the largest payroll provider in the world), and it requires Client Certificate Authentication. I would like to be able to use the REST Dataset for this as it features pagination, but it doesn't support client certificates.

Please add Client Certificate Authentication to the REST Dataset.

**Comment by iampeterdaniels** [comment]
+1 - same issue.

**Comment by fhljys** [comment]
Let's track with 167 and close this one. You could also use this website for feature request: https://feedback.azure.com/forums/270578-data-factory
