### ISSUE TITLE
ICustomActivity still in TwitterAnalysisSample-CustomC#Activity sample

### ISSUE THREAD

**Issue by ahkim** [Azure/Azure-DataFactory#17]
According to following,

https://azure.microsoft.com/en-gb/documentation/articles/data-factory-release-notes/

ICustomActivity interface is renamed to IDotNetActivity. However, the sample still uses ICustomActivity. Please update the sample code to reflect the change required.

**Comment by gauravmalhot** [comment]
Thanks Ahkim for reporting the issue. I see your pull request to correct the issue. I have merged it in the base branch.
