### ISSUE TITLE
Add Parameters to SFTP Linked Service

### ISSUE THREAD

**Issue by lymedo** [Azure/Azure-DataFactory#171]
Add parameters functionality to the SFTP linked service to enable dynamic connections.

"host": "@{linkedService().host}",
"port": "@{linkedService().port}",
"skipHostKeyValidation": "@{linkedService().skipHostKeyValidation}",
"authenticationType": "@{linkedService().authenticationType}",
"userName": "@{linkedService().userName}"

I've managed to implement this using the dynamic JSON option but the parameters do not appear when the linked service is added to a dataset.

**Comment by fhljys** [comment]
Fixed already
