### ISSUE TITLE
DIU and parallel process not being used

### ISSUE THREAD

**Issue by dandamudisanjay** [Azure/Azure-DataFactory#175]
Hi All,

I have changed my DIU from 4 to 32 and parallel process from 1 to 8. But when i debug, it is still showing as 4 and 1. I’m trying to use copy activity from blob to dynamics using CDS as sink. Anyone had luck using this? If you could share more info on this, that would be greatly appreciated.

**Comment by JacoboDB** [comment]
Did you solve the problem? I am experiencing something similar

**Comment by fhljys** [comment]
Does this help? https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-performance#data-integration-units

**Comment by fhljys** [comment]
Close due to inactivity
