### ISSUE TITLE
Serilaizing/Deserialising ADF Pipelines to JSON results in incompatible JSON structure

### ISSUE THREAD

**Issue by MattEvansA45** [Azure/Azure-DataFactory#176]
I am trying to source control our ADF development into JSON files using the .NET SDK. I don't wish to use the git connected repository method. 

I want json file definitions of all the entities but as its easier for us to build these via the ADF portal GUI i want to design the pipelines etc via the GUI then extract the json code behind the objects into files.  

I have connected to the data factory using the .net sdk libraries and for example serialized a simple demo pipeline which contains a single wait activity. 

the issue is that when serialising the class **PipelineResource** for example using newtonsoft it doesn't provide  a structure that can be deserialized again.  It seems to be missing the "type" of all the activities.  The same goes with dataflows.

**Code behind the GUI**
```
{
    "name": "PL_DEMO",
    "properties": {
        "activities": [
            {
                "name": "Wait1",
                "type": "Wait",
                "dependsOn": [],
                "userProperties": [],
                "typeProperties": {
                    "waitTimeInSeconds": 1
                }
            }
        ],
        "annotations": []
    },
    "type": "Microsoft.DataFactory/factories/pipelines"
}
```
**Standard Serialised version**
```
{
  "properties.activities": [
    {
      "typeProperties.waitTimeInSeconds": 1,
      "name": "Wait1",
      "dependsOn": [],
      "userProperties": [],
      "typeProperties": {
        "waitTimeInSeconds": 1
      }
    }
  ],
  "properties.annotations": [],
  "name": "PL_DEMO",
  "type": "Microsoft.DataFactory/factories/pipelines",
  "etag": "0000-0000-1100-0000-5e8b390c0000"
}
```
looking at the WaitActivity class i can see that it's assigned a JSONObject of "Wait" however this doesn't translate into any serialisation of the object.

```
namespace Microsoft.Azure.Management.DataFactory.Models
{
    //
    // Summary:
    //     This activity suspends pipeline execution for the specified interval.
    [JsonObject("Wait")]
    [JsonTransformation]
    public class WaitActivity : ControlActivity
```
 
Can anyone advise if this is a bug or whether some other method needs implementing to get the classes exported in a compatible format? similar to the format you see when you click "code" via the portal

Thanks

**Comment by QuanTran91** [comment]
The same issue, the reason for this issue is the wrong JsonPropertyName
![image](https://user-images.githubusercontent.com/10222639/89167475-a8691300-d5a5-11ea-8a20-afd1d668e364.png)

I have work around by this approach:
Create new model:

    public class DataFactoryPipelineModel
        {
            public string Name { get; set; }
            PipelineResource Properties { get; set; }
        }

Them I create new contract resolver:

    public class IgnoreJsonPropertyContractResolver : CamelCasePropertyNamesContractResolver
        {
            protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
            {
                // Let the base class create all the JsonProperties 
                // using the short names
                IList<JsonProperty> list = base.CreateProperties(type, memberSerialization);

                // Now inspect each property and replace the 
                // short name with the real property name
                foreach (JsonProperty prop in list)
                {
                    prop.PropertyName = prop.UnderlyingName;
                }

                return list;
            }
        }


Finally I deserialize it 

    var resource = JsonConvert.DeserializeObject<DataFactoryPipelineModel>(jsonData, new JsonSerializerSettings
            {
                ContractResolver = new IgnoreJsonPropertyContractResolver()
            });

**Comment by fhljys** [comment]
Seems it is resolved?
