### ISSUE TITLE
Azure Data Factory v2 Not Parameterizing Password Secret Name

### ISSUE THREAD

**Issue by dnh-developer** [Azure/Azure-DataFactory#178]
I have an Azure Data Factory to which I have added a Linked Service (SQL Server) via an Integration Runtime (the Integration Runtime is running on an on-premises PC on my network).

I have used an Azure Key Vault to store the Connection string and Password:
![SqlServerLinkedService_Secret](https://user-images.githubusercontent.com/64267052/80230849-65181380-864a-11ea-968a-647cd135bf48.png)

My problem is that when I look at the ARMTemplateParametersForFactory.json file generated by Publish, in the adf_publish branch, only the connectionString is parameterized, the password is not parameterized, meaning I cannot override the password secret name in TEST, UAT, Production etc.:
![ARMTemplateParametersForFactory_4](https://user-images.githubusercontent.com/64267052/80231267-0b641900-864b-11ea-8712-6c8d70c51d3e.png)

**Surely I should be able to override the password secret name?!?**

**Comment by dnh-developer** [comment]
Now if I contrast this to what happens when I just set the connection string and password manually, without using an Azure Key Vault, the ARMTemplateParametersForFactory.json file does parameterize the password field and does allow me to override it when deploying to other environments:
![SqlServerLinkedService_Hardcoded](https://user-images.githubusercontent.com/64267052/80231829-d60bfb00-864b-11ea-9638-18af8b628a0d.png)

In fact you can see that the template has 5 overridable parameters and not 4 as per above:
![ARMTemplateParametersForFactory_5](https://user-images.githubusercontent.com/64267052/80231858-e328ea00-864b-11ea-94aa-cfe4095206d1.png)

**Comment by VarunBhandary** [comment]
Curious to understand if this is an issue or if there is a workaround? Is there a way to override the secret name when moving between stages of release when using Azure DevOps? or we have to keep the name of the secrets consistent across environment specific key vaults?

The parameterization template does not cover the same as well.
https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#use-custom-parameters-with-the-resource-manager-template

**Comment by VarunBhandary** [comment]
> Curious to understand if this is an issue or if there is a workaround? Is there a way to override the secret name when moving between stages of release when using Azure DevOps? or we have to keep the name of the secrets consistent across environment specific key vaults?
> 
> The parameterization template does not cover the same as well.
> https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#use-custom-parameters-with-the-resource-manager-template

Refering to documentation -
https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#use-custom-parameters-with-the-resource-manager-template

Can an example be added to the documentation around how the secret names can be parameterized?

**Comment by donovan-dd** [comment]
I just faced a similar issue when trying to parameterize the AKV secret name where it said 'error: missing parameter definition for UserPassword' when my AKV parameter name was: UserPassword-KeyVaultSecretName

I changed it to UserPassword_KeyVaultSecretName with an underscore instead and it then worked.

I believe the issue here is you cannot use dashes for a secret name (strange), but you can use dashes in a parameter name or expression.  Try using an underscore instead and see if it works.  Maybe this is still a bug regardless...

**Comment by fhljys** [comment]
If you associated a git with your data factory, ADF provided a feature to help you customize which part you want to be parameterized. https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#use-custom-parameters-with-the-resource-manager-template
