### ISSUE TITLE
ADF - Rest API source not writing correct rows to sink Data Lake

### ISSUE THREAD

**Issue by sachindedhia** [Azure/Azure-DataFactory#179]
I'm reading the Microsoft Graph API Sign in API data using below article. 

https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-1.0

For the same, I've created Source REST API connection - 

![image](https://user-images.githubusercontent.com/53565935/80588911-1d5e0700-8a11-11ea-9cfc-b6cae841474f.png)

and this is writing to Data Lake Gen1 in csv format.

![image](https://user-images.githubusercontent.com/53565935/80588973-3b2b6c00-8a11-11ea-9c90-e525d3b4f215.png)

Since the API is sending the data is in json format, I've flatten the structure using the mapping activity.

![image](https://user-images.githubusercontent.com/53565935/80589044-5ac29480-8a11-11ea-84f7-293c87d018cc.png)

When I run this activity, it seems to write only very few records. As you see in the activity, it is reading 95 MB data from rest api but it has only written 16 KB data in to the sink as you can see below

I'm not sure why it is only writing limited data to sink

![image](https://user-images.githubusercontent.com/53565935/80589209-a83f0180-8a11-11ea-963b-c73d0608e69b.png)

**Comment by fhljys** [comment]
Still hitting this?

**Comment by fhljys** [comment]
Close due to inactivity.
