### ISSUE TITLE
Data Flow: DF-SRC-005 at Source

### ISSUE THREAD

**Issue by imheretomakefriends** [Azure/Azure-DataFactory#180]
Error Message: `DF-SRC-005 at Source 'source1': Column 'data has incompatible types( Found: ArrayType(StructType(StructField(day,StringType,true), StructField(month,StringType,true), StructField(year,StringType,true)),true), Required: ArrayType(StructType(StructField(day,StringType,true), StructField(month,StringType,true), StructField(year,StringType,true)),false))`

How to recreate in data flow: 
1. Source is a JSON file from blob storage
2. Source data has an array property
3. Tick `Validate schema` option
4. Refresh data preview

Is there a way to set the ArrayType containsNull option in Data Flow?

**Comment by shawnxzq** [comment]
@imheretomakefriends We will look into this, please disable the "validate schema" option to work around for now.
