### ISSUE TITLE
Key Vault Secret - Web activity - Self-Host IR

### ISSUE THREAD

**Issue by candidson** [Azure/Azure-DataFactory#181]
Hello Guys,

I have been trying to access secrets from Key Vault using the ADF Web activity using a self-hosted integrated runtime (version 4.6.7367.1). However, this doesn't work. I keep getting the following error. Though, I was still able to reach the AKV from the IR Machine directly.

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/12760630/81511378-55baea80-9319-11ea-8b60-da5e2365abab.png">

**Comment by fhljys** [comment]
Are you still hitting this?

**Comment by fhljys** [comment]
Close due to inactivity.
