### ISSUE TITLE
SSL certificate usage in Azure Data Factory while connecting to DB2

### ISSUE THREAD

**Issue by sndp2693** [Azure/Azure-DataFactory#182]
I want to use a SSL certificate while creating a linked service in azure data factory to DB2 database. 
When we do it via JDBC connection we don't provide password for DB and only set SSL properties. 
How can we do that in azure data factory? Password seems to a mandatory field there.
Is it possible in ADF to connect to DB using SSL certificates? If yes how ? I couldn't find anything on that. Your help is much appreciated !

**Comment by sndp2693** [comment]
Basically I want to connect to DB2 using a SSL certificate and not via username/password

**Comment by fhljys** [comment]
Sounds like a feature request? Maybe you can try this: https://feedback.azure.com/forums/270578-data-factory

**Comment by fhljys** [comment]
Close due to inactivity.
