### ISSUE TITLE
pipeline().Pipeline variable adds GUID to the name when "Execute Pipeline" activity is present

### ISSUE THREAD

**Issue by stawo** [Azure/Azure-DataFactory#188]
Similar to closed issue #75, but I experience it with a different activity and I also include steps to reproduce the problem.

Steps:
* create an empty pipeline
* set the pipeline name to 'test'
* define pipeline variable 'pipeline_name'
* add activity 'Set variable', select variable 'pipeline_name', and set its value to 'pipeline().Pipeline'
* add activity 'Execute Pipeline' after 'Set variable', connect 'Set variable' to it (doesn't matter the condition), and leave it empty (we do not need to specify any sub-pipeline)
* click on the 'Set variable' activity and activate 'Debug Until'
* Debug the pipeline.

Expected outcome:
* variable 'pipeline_name' should have value 'test'

Experienced outcome:
* variable 'pipeline_name' has a value like 'test7283b3a4-ff8e-4cac-92af-c859a6a0a998'

I'm not sure why Data Factory adds a GUID to the pipeline name, maybe to make it unique among the sub-pipelines that are invoked if we use the 'Execute Pipeline' activity.
If that is the case, I would prefer to keep the property 'pipeline().Pipeline' coherent with the name, and in case add an additional property like 'pipeline().PipelineId'.
The changing of the name under the hood with no warning is confusing, and I was hoping to use the name of the pipeline to retrieve specific parameters from a DB, but since the pipeline name is getting changed, it fails.
![Data Factory-Pipeline Name](https://user-images.githubusercontent.com/430753/83266474-2b937480-a1c3-11ea-89cb-d6016eb002c8.png)

**Comment by fhljys** [comment]
Still experiencing this?

**Comment by fhljys** [comment]
Close due to inactivity.
