### ISSUE TITLE
Deleted pipeline is referenced by a trigger and blocks publishing

### ISSUE THREAD

**Issue by aventius-software** [Azure/Azure-DataFactory#190]
We've run into a problem a couple of times now where we deleted a pipeline (that was referenced by a trigger) in a branch and created a pull request into master branch and tried to publish. The problems comes when trying to publish as we get an error saying the factory cannot be published as a trigger references the pipeline in the published data factory but the pipeline no longer exists. Thus we are left with a data factory that we cannot publish.

The only fix we found for this was to get the JSON code for the deleted pipeline(s) and then recreate the deleted pipeline in the feature branch using the JSON code, remove the trigger reference (without deleting the pipeline) and then merge to master branch and publish. Finally back to the feature branch to delete the pipeline and do another pull request to master and then publish...

Its seems like more of a design 'flaw' than a 'bug' I guess, but basically we need a fix that removes the trigger reference when a pipeline is deleted in the master branch. Or allow the master branch to be published when a trigger references a deleted pipeline, and if so, then remove that reference from the trigger during the publish... or something like that :)

**Comment by aventius-software** [comment]
There also seems to be a related issue to this, although I'm not sure where this would sit in terms of data factory or Azure DevOps.... If you have a pipeline which calls other pipelines (and so on...), then if you are using Azure DevOps to deploy the factory to another factory (so deploying to test/prod etc...) your publish will fail if the pipelines are not deleted in the correct order (i.e. from a pipeline dependency point of view) as it fails with an error that complains that pipeline X references pipeline Y so cannot continue. The only way to fix this is manually delete the offending pipelines in the destination factory then re-deploy the release from DevOps... This has happened to us on a number of occasions, not as often as the original issue detailed above though... ;-)

**Comment by aventius-software** [comment]
Any update on this? We've had this problem crop up a number of times so far... maybe we should stop using pipelines which call other pipelines :-)

**Comment by ChrisLloyd93** [comment]
I am having the same issue, which is a pain as if you delete a pipeline no longer required which contains a trigger then it takes a while to kind of sort this issue. A beneficial update would be to delete the trigger along with the pipeline when the pipeline is deleted, or just remove the link between the two when the pipeline is deleted

**Comment by AHSRFT** [comment]
Same issue here! Any better solution / permanent fix planned?

**Comment by fhljys** [comment]
Track with #208 . We are aware of this issue.

**Comment by manisha201301** [comment]
I also faced this issue and was looking for solutions. For me, when I switched from GtiHub mode to Live mode of ADF I saw the deleted resources. I tried re-deleting it and publishing the changes but it wasn't allowing to publish the changes as I had my GitHub configured to only publihs from "main" branch, later I used the "Overwrite" button and then again tried publishing from "main" branch in which case it worked
![image](https://user-images.githubusercontent.com/4443326/143139288-777360e6-b8fa-4461-8168-0e5c4b755c8b.png)
