### ISSUE TITLE
Getting keys of activity ouput

### ISSUE THREAD

**Issue by rriley99** [Azure/Azure-DataFactory#191]
Hello
Is there a functionality to receive an array of the keys within a json request return? Having an output like such is not uncommon: 

I've attempted work arounds with various string manipulation to no avail.

![image](https://user-images.githubusercontent.com/27045344/83449931-6810db80-a422-11ea-9fdb-e0eea71b032b.png)

**Comment by fhljys** [comment]
What do you want to do? get keys of an object?

**Comment by fhljys** [comment]
Close due to inactivity
