### ISSUE TITLE
Custom Activity: .NET Core 2.2 self-contained console app: Too many files in the folderPath

### ISSUE THREAD

**Issue by varismii** [Azure/Azure-DataFactory#193]
I created a .NET Core 2.2 console app and tried to run it via Azure Data Factory V2 custom activity.

If I deploy it via Blob Storage as a **framework-dependant app**, it gives error that hostfxr.dll is missing.

If I deploy it via Blob Storage as a **self-contained app**, it gives error 2504, The[ error description](https://docs.microsoft.com/en-us/azure/data-factory/data-factory-troubleshoot-guide) says:
"Too many files in the folderPath of the custom activity. The total size of resourceFiles can't be more than 32,768 characters."
I checked that my app's .deps.json is 44 409 bytes, even though it's minimal (OOTB from VS2019 templates).

So how to use a **self-contained** .NET Core app in an Azure Batch node via ADF V2?

Or are there Azure Batch compiliant VMs available with built in .NET Core 2.x or 3.x so that I can use a **framework-dependant** console app? That would be the preferred option.

Currently the only workaround I know is to revert to .NET Framework 4.7.2 console app. Not a big deal, but we are trying to migrate away from .NET Framework to newer Core and Standard.

**Comment by fhljys** [comment]
Does this help? https://docs.microsoft.com/en-us/azure/data-factory/data-factory-troubleshoot-guide#error-code-2504

**Comment by fhljys** [comment]
Close due to inactivity.
