### ISSUE TITLE
Rerun activity using cache

### ISSUE THREAD

**Issue by AlexMechanicus** [Azure/Azure-DataFactory#195]
Hi team,

Last week I noticed that after rerun pipeline from failed activity, all activities after re-ran one are marked as skipped and Lookup activity returned cached result, in my case it is email body.
I expected another email body, but I got old one.
Currently the only way is to rerun full pipeline. It is very time consuming.
Can you into it and fix or provide any comments/solution?

**Comment by fhljys** [comment]
Are you still hitting this?

**Comment by fhljys** [comment]
Close due to inactivity.
