### ISSUE TITLE
Copy Data Pipeline Extremely Slow For Azure SQL DB to AzurePostgre SQL 

### ISSUE THREAD

**Issue by t-josing** [Azure/Azure-DataFactory#197]
The Copy Data Pipeline in the azure data factory for Azure SQL DB to Azure Postgre SQL, is extremely slow. And you cannot even increase the DIUs. 

Any other method for migration?

**Comment by fhljys** [comment]
Please check whether this helps. Otherwise, you could create support tickets to ADF. https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-performance-troubleshooting
