### ISSUE TITLE
Azure Data Factory activity failed with no Error Code

### ISSUE THREAD

**Issue by amyfan-local** [Azure/Azure-DataFactory#198]
We observed this issue while running ADF pipeline. The web activity cancelled itself while running.
`"status": "Cancelled",
    "failureType": "UserError",
        "Error": {
        "errorCode": "",
        "message": "",
        "failureType": "UserError",
        "target": "InvokeAzureFunctionExportService",
        "details": ""
    },`
There is no user intervention during the run. There is no time limit set for the activity.

There is no errorCode that we can search or debug. Please help provide guidance if anyone encountered similar issue before. Any hint is appreciated. Thanks!

**Comment by fhljys** [comment]
Are you still experiencing this?

**Comment by fhljys** [comment]
If you hit this again, please provide activity ID or create support ticket to ADF team. Thanks.
