### ISSUE TITLE
.Net custom activity Sample for pulling data from Google Analytics

### ISSUE THREAD

**Issue by ahkim** [Azure/Azure-DataFactory#20]
I have recently developed ADF .Net custom activity pulling data from GA and push them into Blob(and to DW eventually). Though ADF supports OData connector, OAuth isn't supported yet. This was the reason why I had to come up with custom activity. Resolving OAuth was a bit tricky due to OAuth requiring user's consent. I am happy to contribute this with some sample code creation. But, I'd like to make sure whether this will be an appropriate addition to this repository before I start. Please comment.

**Comment by rahuliet2008** [comment]
Can you show me the code and sample.I am building same but OAuth is not working in hosted environment.

**Comment by ahkim** [comment]
Hi @rahuliet2008, please have a look at https://github.com/LindaLawton/Google-Dotnet-Samples/commit/e3ca73c2c4213a6ef737d07c6063448ef745eaf0

You should use authentication using a service account. I have integrated with google analytics using same authentication method both from Azure Data Factory and webjob. 

Authenticating to Google using a Service account : https://developers.google.com/accounts/docs/OAuth2#serviceaccount
