### ISSUE TITLE
Custom Logging In ADF

### ISSUE THREAD

**Issue by SidGrundfos** [Azure/Azure-DataFactory#200]
Hello Community,
I am new to ADF. I have mostly worked on Kubernetes and in our organization we use Humio as a centralized logging storage. From Kubernetes it is easy to setup ingestion to Humio via Fluentbit. 
We have also set up ADF for some projects, we would really love to know if there are any ways we can achieve this in ADF. Push all logs to Humio. I have gone through some blog and found there are no direct integration methods but please let me now where can I get some suggestions regarding the same?

**Comment by fhljys** [comment]
If Humio has rest api support, maybe you can consider rest connector of ADF ? https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-rest-api

Or web activity? https://docs.microsoft.com/en-us/azure/data-factory/control-flow-web-activity

Or custom activity if you can write your code: https://docs.microsoft.com/en-us/azure/data-factory/transform-data-using-dotnet-custom-activity
