### ISSUE TITLE
Unable to deploy Azure Data Factory's HttpService and RestServices using ARM Template

### ISSUE THREAD

**Issue by Ashish-Jovial** [Azure/Azure-DataFactory#204]
Dear Team,

I am facing the ARM template deployment issue for Azure Data Factory's HttpService and RestServices, I am following proper documentation, despite this I am getting error.

` {
      "name": "[concat(parameters('factoryName'), '/LinkedSvc_MySolution_WebAPI')]",
      "type": "Microsoft.DataFactory/factories/restservice",
      "apiVersion": "2018-06-01",
      "properties": {
        "annotations": [],
        "type": "RestService",
        "typeProperties": {
          "url": "https://www.mysolution.com/api/expense/extract/v1.0/",
          "enableServerCertificateValidation": false,
          "authenticationType": "Anonymous"
        }
      }
    },
    {
      "name": "[concat(parameters('factoryName'), '/LinkedSvc_MYSOLUTIONAPI')]",
      "type": "Microsoft.DataFactory/factories/httpserver",
      "apiVersion": "2018-06-01",
      "properties": {
        "annotations": [],
        "type": "HttpServer",
        "typeProperties": {
          "url": "https://www.mysolution.com/api/expense/extract/v1.0/",
          "enableServerCertificateValidation": false,
          "authenticationType": "Anonymous"
        }
      }
    }`

I had tried many iterations of deployment by modification (removing type key, changing URL, kept true for enableServerCertificateValidation key) above JSON.

![image](https://user-images.githubusercontent.com/5494030/86432415-418ddb00-bd15-11ea-9c44-a93c0c2db3bc.png)
The following error occurred when I hadn't applied the type of service.

![image](https://user-images.githubusercontent.com/5494030/86432557-c678f480-bd15-11ea-83a9-09eed44dbeda.png)

**Comment by Ashish-Jovial** [comment]
Has anyone looked into this issue?

**Comment by Ashish-Jovial** [comment]
There is an update, I have tried following JSON to deploy. I can see in the log that the ARM template deployed successfully but when I checked Azure Portal in Azure Data Factory, LinkedServices were not created.

`{
      "name": "[concat(parameters('factoryName'), '/LinkedSvc_HeartAPI')]",
      "type": "Microsoft.DataFactory/factories/pipelines",
      "apiVersion": "2018-06-01",
      "properties": {
        "annotations": [],
        "type": "HttpServer",
        "typeProperties": {
          "enableServerCertificateValidation": true,
          "url": "https://www.mysolution.com/api/expense/extract/v1.0/",
          "authenticationType": "Anonymous"
        }
      }
    }`

**Comment by fhljys** [comment]
Have you tried create your LS in ADF UI and then export the ARM template and compare it with yours?

**Comment by fhljys** [comment]
Close due to inactivity
