### ISSUE TITLE
Unable to bulk copy a mix of small ~50 mbs files and 2GB+ files from SFTP with SSH on DataFactory

### ISSUE THREAD

**Issue by khaledalarja** [Azure/Azure-DataFactory#205]
When I use the wildcard field path copy feature and I specify *.(extension here), it starts copying the small files first, but then when it arrives to the big files that are around 2GB it crashes and gives an SSH error

{
    "errorCode": "2200",
    "message": "Failure happened on 'Sink' side. ErrorCode=SftpAuthenticationFailure,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Meet authentication failure when connect to Sftp server '(SFTPSERVERHERE)' using 'SshPublicKey' authentication type.,Source=Microsoft.DataTransfer.ClientLibrary.SftpConnector,''Type=Renci.SshNet.Common.SshAuthenticationException,Message=Permission denied (publickey).,Source=Renci.SshNet,'",
    "failureType": "UserError",
    "target": "Copy SFTP Data",
    "details": []
}

Knowing that when I copy one of the big files alone it works well

**Comment by yew** [comment]
Hi @khaledalarja , here is Guosen from ADF product group.
Just saw this, do you still encounter this error now?

**Comment by fhljys** [comment]
Close due to inactivity.
