### ISSUE TITLE
Need some information and documentation about setting up Ternary Factory

### ISSUE THREAD

**Issue by GopiMtp** [Azure/Azure-DataFactory#206]
Hi Team,

I'm currently planning to use Self Hosted Shared Integration Runtime in Azure data factory. In Azure documentation suggests to use Ternary Factory for this purpose, but didn't specify any details about it. Can you please provide more information about it and how to setup and scenario's would be very helpful.

Please let me know, if you need any further details.

Thanks
Gopi Velusamy

**Comment by cimga** [comment]
i need answer of this question as well! can anyone explain what does it mean Ternary Factory?

**Comment by fhljys** [comment]
Suppose you are referring to this doc: https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment

I think it just means another dedicated factory for Integration Runtime. Nothing special, but only use it to host your integration runtime.

**Comment by rishabhbeni** [comment]
Hi,

I think this article might help if you are still looking for it: https://docs.microsoft.com/en-us/azure/data-factory/concepts-integration-runtime
