### ISSUE TITLE
Shared Runtime Access Policy setup across cross resource group IR

### ISSUE THREAD

**Issue by GopiMtp** [Azure/Azure-DataFactory#207]
Hi Team,

I've a subscription named "Prod" and configured data factory with self hosted runtime. Currently I'm setting up "Dev", "QA" resource groups with data factory and would like to use the same shared runtime via ARM. When I deploy ARM template all resources are created except shared runtime. The reason for that is, the new data factory principal needs to be added in Shared IR access settings, after setting that manually and deploying the package successfully deploys all.  But I'm trying to create data factory, and all it's resources including Shared Runtime access permission setup via ARM, but couldn't succeed on that. 

Any quick help would be much appreciated, let me know if you need any additional details.

Thanks
Gopi Velusamy

**Comment by fhljys** [comment]
Close this one and track with #144

**Comment by fhljys** [comment]
I think Azure Data Factory expects that your QA/PROD data factories are created and permissions are well granted before starting the CICD process.
