### ISSUE TITLE
Pipeline is referenced by a another pipeline, cannot be delete and blocks deployment to other environments

### ISSUE THREAD

**Issue by aventius-software** [Azure/Azure-DataFactory#208]
This seems to be a similar problem to this issue #190 

I'm not sure where this would sit in terms of data factory or Azure DevOps, but.... If you have a pipeline which calls other pipelines (and so on...), then if you are using Azure DevOps to deploy the factory to another factory (so deploying to test/prod etc...) your publish will fail if the pipelines are not deleted in the correct order (i.e. from a pipeline dependency point of view) as it fails with an error that complains that pipeline X references pipeline Y so cannot continue. The only way I've found so far to fix this is to manually delete the offending pipelines in the _destination_ factory then re-deploy the release from DevOps... This has happened to us on a number of occasions, I'd rather not have to resort to pipelines that do not call other pipelines, but this is rather frustrating when it happens...

**Comment by aventius-software** [comment]
Sorry should have put the error message we're getting when trying to deploy, this is the error from Azure DevOps.

` ##[error]HTTP Status Code: BadRequest
Error Code: BadRequest
Error Message: The document cannot be deleted since it is referenced by *** pipeline name removed ***.`

**Comment by aventius-software** [comment]
Also, I don't think i mentioned this but it also blocks publishing directly in data factory if you delete the pipeline which is called by another pipeline first - even though they have both been deleted. This is a screen shot of the error when you try and publish from data factory. Note that the error is the same as when trying to deploy using Azure DevOps release pipeline...

![image](https://user-images.githubusercontent.com/47484806/88265625-bffeec80-ccc5-11ea-80d9-db56255bf63e.png)

**Comment by aventius-software** [comment]
Any update?

**Comment by aventius-software** [comment]
This has happened again, someone in our team has deleted several pipelines which were referenced by other pipelines. However, as before, all the pipelines - the referenced ones and the ones referencing them are all now deleted, so the dependency is of no consequence, there are no orphaned pipelines. 

However, we now have a valid master branch (verified fine) with no orphans or anything but we cannot publish our data factory as its got it's knickers in a twist about deleting referenced pipelines. The publishing process should take into account any pipeline dependencies and work down the tree deleting them and then there would be no problem, but it seems to be deleting pipelines in some unknown/random order (possibly the order in which they were deleted in the commits?). 

I would say this is a design flaw (somewhere along the line when publishing the factory), the commits should not determine the deletion order of pipelines, the pipeline dependency should dictate the delete order or pipelines whatever the commit order - in fact the commit order should not

I'm going to have to log a support request for this as this as it is becoming a huge pain in the a** when it happens, basically we have to delete pipelines in the correct dependency order otherwise we cannot then later publish our factory!

**Comment by Brondahl** [comment]
FWIW, I just came across this bug too. I solved it by squash the series of commits down, then extracting the deletions into separate commits in the relevant order (top-most, then next, etc.) then publishing each commit in sequence.

Worked but was a **huge** PITA

**Comment by fhljys** [comment]
Based on my understanding, this happens when you have a complex dependency. If you check the network trace, the ADF UI didn't check the dependency when they send out deletion API calls. Instead, they will retry a few times if the deletion failed. They are aware of this and the fix is in backlog. 

For now, I think a workaround is that you could delete the parent entity first. For example, if your trigger references a pipeline, you should delete your trigger first and then pipeline.

**Comment by DayhopeZhang** [comment]
Introduced a delete sorting service to solve the issue. Now, all the resources to be deleted will be first sorted into batches according to the reference relationships, then be deleted batch by batch.
