### ISSUE TITLE
Help with OData source mappings in ADF

### ISSUE THREAD

**Issue by kisalay19** [Azure/Azure-DataFactory#209]
My question is around reading values from an OData/Dynamics AX source and dump the data to a sink in Cosmos DB. I am able to achieve this without any issue but the problem what I am facing is described below. Need help regarding that.

1. Some column values in my source are of type Enum due to which these are ignored/not visible when I Import Schema to create the mappings

2. Example : I have created a source and added a query to select the required columns only `$select=ProductID,ProductType,Country,Amount,Currency` . The `ProductType` is of type Enum so in mapping this is ignored and others are available as their type is "Edm.String", "Edm.Decimal"

Is there way somehow I can read that Enum column ?

**Comment by vdiallonort** [comment]
Hello,Did you find any workarround ? I have the same issue with Dynamics D365 Finance & Operations ?

**Comment by wazzer2000** [comment]
same issue here!

**Comment by Miwa199739** [comment]
Did you still experience the issue? @linda33wj, any suggestion?

**Comment by zhenqxuMSFT** [comment]
Hi all, I am from Azure Data Factory product team. We are in private preview for the support of Enum type. Please reach me via email (see in my profile) so that I can enable it for you.

**Comment by wazzer2000** [comment]
Hi,

Is this fixed?I've just checked and it's still not working.

Thanks

Ahmed

**Comment by fhljys** [comment]
@wazzer2000, can you reach out to zhenqxuMSFT as mentioned above?

**Comment by cameron-interactive** [comment]
Has this been fixed? I can see enum data when querying Dynamics AX sources in either ADF or Synapse.

**Comment by wazzer2000** [comment]
Yes it works for me now

**Comment by cameron-interactive** [comment]
How??? I can't see any enum fields in any entites.

**Comment by fhljys** [comment]
@cameron-interactive , see this : 

> Hi all, I am from Azure Data Factory product team. We are in private preview for the support of Enum type. Please reach me via email (see in my profile) so that I can enable it for you.

@cameron-interactive  see above

**Comment by cameron-interactive** [comment]
> 
> 
> > Hi all, I am from Azure Data Factory product team. We are in private preview for the support of Enum type. Please reach me via email (see in my profile) so that I can enable it for you.
> 
> @cameron-interactive see above reply from @zhenqxuMSFT

That was months ago and doesn't resolve the issue... I'm asking if this has been fixed or not, it sounds like it hasn't been fixed yet, even though there was commentary from months ago suggesting a fix existed.

**Comment by Micro-Yangzai** [comment]
Please add feature flag under odata or dynamics ax dataset script. ("RetrieveEnumValuesAsString": true)
![image](https://github.com/Azure/Azure-DataFactory/assets/87168976/92fd18f7-bc1d-41b3-bf6c-452834c595ba)

**Comment by Micro-Yangzai** [comment]
This hidden feature only work for OData service V4.  Not work for V3
