### ISSUE TITLE
[DOCUMENTATION] Please add a README

### ISSUE THREAD

**Issue by stephlocke** [Azure/Azure-DataFactory#21]
It would be super helpful if a README could be added to the [samples](https://github.com/Azure/Azure-DataFactory/tree/master/Samples) directory that provides an overview of the different samples so that folks do not need to click into each sample. 

This would also mean that each sample could have a consistent short overview as the individual READMEs vary substantially in content and format.

**Comment by gauravmalhot** [comment]
We have put folder names to give a sense of what each sample is about and each sample includes a readme.txt explaining about the sample..
