### ISSUE TITLE
Azure SQL TimeOut sink side

### ISSUE THREAD

**Issue by barakVaturi** [Azure/Azure-DataFactory#211]
hello,

I try to transform big tables to azure SQL server.
while the small one are complited, thebig ones aren't, and fall on timeout.
the errors are attached.

the sql db is 400 DTU.
how do i increse the timeout at sinkside,
how it can save the connection and will not force close it?

[outputError2.txt](https://github.com/Azure/Azure-DataFactory/files/5020500/outputError2.txt)
[outputError.txt](https://github.com/Azure/Azure-DataFactory/files/5020501/outputError.txt)

**Comment by fhljys** [comment]
Are you still experience this?
Please check this doc: https://docs.microsoft.com/en-us/azure/data-factory/connector-troubleshoot-guide#error-code-sqlbatchwritetimeout

According to this, you need contact Azure SQL support.
