### ISSUE TITLE
SFTP Session Timeout

### ISSUE THREAD

**Issue by dfrostpl** [Azure/Azure-DataFactory#212]
Hello!

I have a ADFv2 instance where I would like to run a copy job from Blob Storage to on-premise SFTP server.
To do so, I have an integration runtime installed on the Azure VM in the same VNET as blob storage. The VNET is connected through VPN to on-premise network.
If I go to that VM and connect to the SFTP Server through FileZilla, it works. However, Integration runtime of the same machine constantly throws Failed to connect to Sftp server '10.0.86.20'. Session operation has timed out.
IR of latest version and has just default configuration, no proxies. 

```
{
    "name": "eckelman_test_ftp",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "annotations": [],
        "type": "Sftp",
        "typeProperties": {
            "host": "10.0.86.20",
            "port": "22",
            "skipHostKeyValidation": true,
            "authenticationType": "Basic",
            "userName": "*********",
            "encryptedCredential": "*****"
        },
        "connectVia": {
            "referenceName": "vm-ki-pm",
            "type": "IntegrationRuntimeReference"
        }
    }
}
`

Please, advise!

**Comment by yew** [comment]
Hi @dfrostpl , I'm Guosen from ADF product group.
Just saw this, did you resolve the issue?

**Comment by fhljys** [comment]
Close due to inactivity.
