### ISSUE TITLE
Set-AzDataFactoryV2Pipeline creates invalid pipeline

### ISSUE THREAD

**Issue by suprak** [Azure/Azure-DataFactory#215]
I have a pipeline deployed in ADF V2 that functions and is runnable.

I create a `pipeline.json` with the contents of the pipeline from the ADF portal (json).

Running the following command produces a pipeline that is not runnable again from the ADF portal, even though the contents of the pipeline are identical to before.

```
Set-AzDataFactoryV2Pipeline -DataFactoryName ... -ResourceGroupName ... -Name ... -DefinitionFile 'pipeline.json' -Force
```

When the pipeline is overwritten by the cmdlet, any attempt to run it, yields error,

`Invalid activity type 'Activity'`

But if I take the contents of `pipeline.json` and edit the json through the ADF portal (by just copy-paste), the pipeline publishes and is runnable again.

**Comment by fhljys** [comment]
Basically, it is because you are using a new activity type which is not recognized by your powershell version.  To address this, just update your ADF module to latest. .
