### ISSUE TITLE
Azure data factory data lake analytics linked service provisioning failed

### ISSUE THREAD

**Issue by nitin16** [Azure/Azure-DataFactory#22]
I am creating pipeline using azure data lake factory. Pipeline has one data lake analytics U-SQL activity. This used to work fine but stopped working stating i need refresh credential tokens.

When I authorize again and deploy I get error saying "Provisioning failed. Internal server error. Request id :....".

{
"name": "DataLakeAnalyticsLinkedService",
"properties": {
    "description": "",
    "hubName": "datafactory_hub",
    "type": "AzureDataLakeAnalytics",
    "typeProperties": {
        "accountName": "datalakeanlytics",
        "authorization": "**********",
        "sessionId": "**********",
        "subscriptionId": "......",
        "resourceGroupName": "DataLake"
    }
}
}

I have tried restarting browser session, creating new service it still fails.

Is there anything else am I missing ?

**Comment by gauravmalhot** [comment]
Are you still facing this issue?

**Comment by gauravmalhot** [comment]
Closing this issue for now. Please let us know if you are still facing the issue and we will investigate at our end... Thanks..
