### ISSUE TITLE
"User/Operator" role for Azure Data Factory

### ISSUE THREAD

**Issue by ravikd744** [Azure/Azure-DataFactory#220]
We see built-in roles for Azure Data Factory (Data Factory Contributor / Reader). but there is no custom action or role available to limit users/serviceprincipals to just be able to run pipelines. We cannot grant contributor role to just run pipelines in the production environment. I see there was an old issue related to this, but closed without any resolution. Do we have any new guidance on this?

**Comment by NandanHegde15** [comment]
Hey @ravikd744 ,
There is no in built role available but you can create a custom role to just trigger the ADF pipelines by below action:

Microsoft.DataFactory/factories/pipelines/createrun/action

Also a reference link to trigger specific pipelines:
https://docs.microsoft.com/en-us/answers/questions/43496/provide-trigger-access-on-a-specific-pipeline-in-a.html
