### ISSUE TITLE
!!!THIS GITHUB REPO DOES NOT APPEAR TO BE MONITORED!!!

### ISSUE THREAD

**Issue by Brondahl** [Azure/Azure-DataFactory#223]
For the benefit of other users who arrive here: it doesn't look like MS actually watch the Issues in this Repo - I've just checked through and I can't see _any_ MS responses on _any_ issues.
All of the "Closed" issues, have been self-closed by the raiser.

I'd recommend looking elsewhere for support

**Comment by Brondahl** [comment]
I've tweeted @AzDataFactory, maybe that'll get a response? 🤷‍♂️

**Comment by albertleigh** [comment]
aggree, we should make some noises down here and let em know

**Comment by fhljys** [comment]
@Brondahl , we are monitoring this repo but not that frequently. 
There are several other ways to ask questions:

1. ADF UX feedback
![image](https://user-images.githubusercontent.com/18674958/106108711-9a2a3700-6183-11eb-9e7a-1463fa166e84.png)
2. Support tickets
3. Stackoverflow: https://stackoverflow.com/questions/tagged/azure-data-factory-2
4. MSDN:https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureDataFactory
