### ISSUE TITLE
Copy Activity fails when Max Rows Per Files is set

### ISSUE THREAD

**Issue by rezasoltanirezvandeh** [Azure/Azure-DataFactory#224]
The copy activity fails when the source table does not return any records and Max Rows Per Files in Sink is configured.

Source: SQL database
Sink: Parquet
Max Records Per File: 100000
Error Message: Invalid attempt to call MetaData when reader is closed.

Failure happened on 'Source' side. ErrorCode=UserErrorFailedFileOperation,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Upload file failed at path edw/ADW/ADW_stg_FactResellerSalesXL_CCI/\.,Source=mscorlib,''Type=System.InvalidOperationException,Message=Invalid attempt to call MetaData when reader is closed.,Source=System.Data,'

Activity succeed if the source has at least one record.

**Comment by fhljys** [comment]
Are you still hitting this?

**Comment by rezasoltanirezvandeh** [comment]
Hi @fhljys , Just tested now  there is no error but an empty file created.

**Comment by fhljys** [comment]
@rezasoltanirezvandeh , Is that expected? Since you mentioned that your source table doesn't return any records.

**Comment by rezasoltanirezvandeh** [comment]
@fhljys yes,  since I am using incremental data load, watermark from date to date, there might be a period which there is no new transactions or change in the source system.

**Comment by fhljys** [comment]
@rezasoltanirezvandeh , Seems we can close this issue now?

**Comment by rezasoltanirezvandeh** [comment]
yes please thanks @fhljys
