### ISSUE TITLE
Data not getting populated from Jason file(Rest API) to SQL DB using Azure Data factory..

### ISSUE THREAD

**Issue by DebolinaDan** [Azure/Azure-DataFactory#230]
Hi,
I am trying to copy data from a REST API i.e jason format into SQL DB, the mapping is validated but data is not getting loaded. The jason file link is 

https://api.data.gov.in/resource/a0cbfe0f-9306-47d2-a204-3d47c1fab015?api-key=579b464db66ec23bdd00000166bfc86e75954b855d39099c93f6bc3c%20&format=json&offset=0&limit=100

and the mapping done is as shown in below image 

![image](https://user-images.githubusercontent.com/74348805/98917050-e99c8780-24f1-11eb-93a5-8205d9e22783.png)

Can you help me out to resolve this issue.

Thanks,
Debolina

**Comment by fhljys** [comment]
Have you checked your schema mapping?

**Comment by fhljys** [comment]
Close due to inactivity
