### ISSUE TITLE
Source Column Not Recognized in Copy Activity

### ISSUE THREAD

**Issue by ghost** [Azure/Azure-DataFactory#232]
Hey there,

I'm trying to author a pipeline to merge data from an Azure SQL DB to an Azure Table. It's really a super-simple pipeline with only one step--copy. The Source for the copy activity is a stored procedure from the Azure SQL DB. The stored proc generates a three-column table with columns propertyId, unitId, and amenities. This maps to PartitionKey, RowKey, and Amenities in the Azure Table.

Unfortunately, I'm receiving the following error:
```
Failure happened on 'Sink' side. ErrorCode=UserErrorAzureTableRowKeyNameNotExist,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=The specified AzureTableRowKeyName 'unitId' doesn't exist in the source data. Please specify a valid column name instead.,Source=Microsoft.DataTransfer.ClientLibrary,'
```

As far as I can tell, I've set up the mapping correctly as outlined here: https://docs.microsoft.com/en-us/azure/data-factory/connector-azure-table-storage#copy-activity-properties.

I've provided the relevant portion of the pipeline code below. I can confirm that I can execute the stored proc on the database and it does return the table it should with the columns I'm expecting.

```
            {
                "name": "CopyAzureSqlToAzureTable",
                "type": "Copy",
                "dependsOn": [],
                "policy": {
                    "timeout": "7.00:00:00",
                    "retry": 0,
                    "retryIntervalInSeconds": 30,
                    "secureOutput": false,
                    "secureInput": false
                },
                "userProperties": [],
                "typeProperties": {
                    "source": {
                        "type": "AzureSqlSource",
                        "sqlReaderStoredProcedureName": "[dbo].[sp_GetCurrentAmenitiesForAPI]",
                        "queryTimeout": "02:00:00",
                        "partitionOption": "None"
                    },
                    "sink": {
                        "type": "AzureTableSink",
                        "azureTableInsertType": "merge",
                        "azureTablePartitionKeyName": "propertyId",
                        "azureTableRowKeyName": "unitId",
                        "writeBatchSize": 10000
                    },
                    "enableStaging": false,
                    "translator": {
                        "type": "TabularTranslator",
                        "mappings": [
                            {
                                "source": {
                                    "name": "propertyId",
                                    "type": "Int32",
                                    "physicalType": "int"
                                },
                                "sink": {
                                    "name": "PartitionKey",
                                    "type": "String"
                                }
                            },
                            {
                                "source": {
                                    "name": "unitId",
                                    "type": "Int32",
                                    "physicalType": "int"
                                },
                                "sink": {
                                    "name": "RowKey",
                                    "type": "String"
                                }
                            },
                            {
                                "source": {
                                    "name": "amenities",
                                    "type": "String",
                                    "physicalType": "nvarchar"
                                },
                                "sink": {
                                    "name": "Amenities",
                                    "type": "String"
                                }
                            }
                        ],
                        "typeConversion": true,
                        "typeConversionSettings": {
                            "allowDataTruncation": true,
                            "treatBooleanAsNumber": false
                        }
                    }
                },
                "inputs": [
                    {
                        "referenceName": "AzureSQLRealpage",
                        "type": "DatasetReference",
                        "parameters": {
                            "tableName": "N/A"
                        }
                    }
                ],
                "outputs": [
                    {
                        "referenceName": "AmenitiesAzureTable",
                        "type": "DatasetReference"
                    }
                ]
            }
```

Hopefully this is just something stupid that I'm not seeing, but I've spent two hours on this, and I can't figure it out.

**Comment by himanshusinha-msft** [comment]
Hello , 
I did tried to repro this issue , but unfortuantely i failed to repro this . Please find the animation of my implemenattion and that may help you to find what is that you are missing . 

I created a SQL table and proc and inserted some dummy data .

CREATE TABLE AzureTableTest 
( 
propertyId int 
,unitid int 
,amenities varchar(100)  

) 

INSERT INTO AzureTableTest values (1,1,'Amerties 1')
INSERT INTO AzureTableTest values (1,2,'Amerties 2')
INSERT INTO AzureTableTest values (1,3,'Amerties 3')

CREATE PROC getcolumns 
as 
SELECT * FROM AzureTableTest
exec getcolumns

Created the attached pipeline and it just works fine , without any issue . 

![Azuretable](https://user-images.githubusercontent.com/47539458/100016930-fd1bde00-2d8e-11eb-92d9-7bc69219034e.gif)

I could suggest you to please ask question here . https://docs.microsoft.com/en-us/answers/questions/ask.html . Also do add the appropiate tags so that the correct team is involved and help you resolve the issue . 

Thanks 
Himanshu

**Comment by sejohnson-at-griffis** [comment]
Hey Himanshu,

I actually ended up writing an Azure Function to do this for me, which I can then call from the pipeline. It ended up working better for my use case, as what I need to do is a merge/insert, and then delete any rows that were not updated (leaving only "current" records). That being said, I'm still interested in working this out, as I believe this will be a repeating use case for us.

Thanks for the detailed reply. Can you get it to work if you specify "Use Sink Column" as the PartitionKey value? My implementation looks almost exactly like yours in the GUI, but I don't want to specify a manual value for the PartitionKey -- I need the PartitionKey to be the propertyId listed in the source stored proc. Based on the documentation, it seems like this is possible, but I can't get it to work.

Elliott

**Comment by Splaxi** [comment]
Anyone finding this in the furture:

This solution works: https://stackoverflow.com/a/72977087/2678467

You need to create "Additional Columns" when working with the source, and this gets imported in the mapping and now you have columns that are available for the sink columns.

I personally just spend hours to figuring this out - and now my stuff works 🤘
