### ISSUE TITLE
ADF Extension: Select existing resource group

### ISSUE THREAD

**Issue by th0ger** [Azure/Azure-DataFactory#233]
I'm not able to use the new ADF Storage Explorer extension:
https://github.com/Azure/Azure-DataFactory/blob/master/StorageExplorerExtension/storage-explorer-plugin.md

Because of this limitation:
*You need to be subscription contributor. If you do not have contributor access on subscription, then at least ensure that there is a resource group under the subscription with the name as the 'subscription id', and you should have contributor permissions on this resource group to make the ADF plugin work.*

I get HTTP 403.

I have full Contributer rights to a resource group (where I already have an ADF running).

Suggesting feature(s):
1. Use an existing ADF resource as a connection.
and/or
2. Specify an existing resource group where the new dedicated ADF connection will be created.

**Comment by fhljys** [comment]
@th0ger, we are actually using the specific group which is named with your subscription id. Is that possible you can ask your sub admin to create a resource source with that name and share you permission?

**Comment by th0ger** [comment]
@fhljys that is not an option, since we need to have all resources for our department allocated to the same resource group. I think that is a typical and perfectly valid reason. (We can have dedicated/autogenerated resources inside that group though.)

Also, from a cost management perspective this forces all cost into one big bucket - Both seperating it from other ADLS/ADF costs, al well as mixing company budgets.

**Comment by fhljys** [comment]
Hi @th0ger , we will definitely take your suggestion into our consideration. 
To help us triage, I also want to understand your scenarios. You want to use this extension due to the simplicity? 
We developed this extension targeting users who are not very familiar with ADF. So we want to simply some steps like create resource group/ create data factory so that customers could just copy data with a simple drag and drop. 
For advanced ADF users, we still recommend ADF website. https://adf.azure.com as it has richer functionalities

**Comment by th0ger** [comment]
Storage Explorer i userful by it's simplicity, so data-maintainers can e.g. browse/upload/maintain data without concerns of Azure portal or ADF.
Production workloads will of couse still be handled by ADF or similar. But for ad-hoc one-time tasks such as migrations, corrective actions or master data management, Storage explorer is a better approach.

I could see use for the ASE-ADF extension as a simple way of migrating data between two ADLS Gen2 resources, or between two Containers in the same. (The "Move..." action currently only works within a container.) Of course cloud-to-cloud copy is mandatory for larger datasets.

But the simplicity is lost, if you have to argue with subscription admins about odd resource groups.

**Comment by fhljys** [comment]
@th0ger , what you said is exactly the scenario we want to target.  I will definitely talk this with our PM.  
Btw, hope you understand, even with ASE-ADF extension, it is still cloud-to-cloud copy, which happens in the data factory we created. The client just helps trigger the copy job.

**Comment by albertli-msft** [comment]
Hi @th0ger , 

We recently released a new version 0.1.4 supporting existing factories along with Azure Storage Explorer 1.17.0. 
The new extension could be seized via the link provided in the Storage Explore 1.16.0 or 1.17.0 release notes like:

![ase17_step_0](https://user-images.githubusercontent.com/69623692/102184831-10801c00-3eeb-11eb-8faf-321bf5e58399.png)
 
Once downloaded, the extension could be installed by simply doble clicking it on both Windows and Macintosh. For the other platforms, the open extension menu item on the File main menu dropdown could help you install it. 

Once the extension installed, there would be a new choice available allowing you to select an existing factory to do the drag and drop copy. At the same time, you still could choose to let the extension help you create a new factory beneath the subscription entitled. 

![ase17_step_2](https://user-images.githubusercontent.com/69623692/102185069-710f5900-3eeb-11eb-9ba7-e25bdf7edb6c.png)
![ase17_step_3](https://user-images.githubusercontent.com/69623692/102185183-9d2ada00-3eeb-11eb-9d70-1455731ead77.png)

And the connection here is a mapping concept to the linked service in ADF world; once opening one, you can do copy to the blob/gen2 explorer view of Storage Explorer. Currently, again, we still merely support the connection of the types of S3/Blob/Gen2 and Blob/Gen2 explorers on storage explore side. 

![ase17_step_1_output](https://user-images.githubusercontent.com/69623692/102185079-740a4980-3eeb-11eb-852f-fc594a4e33ca.png)

Thus, I supposed we have resolved this feature requested. The extension should pick up any factories of all resource groups beneath one entitled subscription and that would also include the one of your existing resource group. Hereby, we would close it and @th0ger please feels free to reopen if anything else popped up.

Thanks again for your valuable suggestion. 😀

**Comment by th0ger** [comment]
This works, thanks for your improvement.
