### ISSUE TITLE
Automate export/import ARM template

### ISSUE THREAD

**Issue by virtualdvid** [Azure/Azure-DataFactory#243]
**Is your feature request related to a problem? Please describe.**
I'm automating the process of promoting Az Data Factory objects to different environments but I'm getting frustrated when I have to export the ARM template manually so my code can continue its process replacing the `ARMTemplateForFactory.json` and `ARMTemplateParametersForFactory.json` files and pushing them into the release branch.

**Describe the solution or feature you'd like**
I would like a power shell command I can trigger using python to export the ARM template in a desire folder.

**Describe alternatives you've considered**
There could be a process running in the background that updates the ARM template in the repo each time we click the `save` or `validate all` button. So I don't even have to trigger this with python or power shell.

**Comment by fhljys** [comment]
@virtualdvid , please check whether this helps. https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment-improvements
