### ISSUE TITLE
False positive on secret storage in dynamic CosmosDB linked service

### ISSUE THREAD

**Issue by bcassell** [Azure/Azure-DataFactory#244]
When creating a dynamic linked service for CosmosDB as per the documentation like below:

```
{
    "name": "CosmosDbSQLAPILinkedService",
    "properties": {
        "type": "CosmosDb",
        "typeProperties": {
            "connectionString": "AccountEndpoint=<EndpointUrl>;Database=<Database>",
            "accountKey": { 
                "type": "AzureKeyVaultSecret", 
                "store": { 
                    "referenceName": "<Azure Key Vault linked service name>", 
                    "type": "LinkedServiceReference" 
                }, 
                "secretName": "<secretName>" 
            }
        },
        "connectVia": {
            "referenceName": "<name of Integration Runtime>",
            "type": "IntegrationRuntimeReference"
        }
    }
}
```

It gives me 
"Linked service will be published immediately
As Data Factory cannot store credentials in a Git repository, this change will be published immediately..."

Following the pattern above does not store any credentials in Git.  This is preventing me from developing a complete feature before publishing.

**Comment by fhljys** [comment]
We are aware of this and it is in our backlog.

**Comment by fhljys** [comment]
Fixed.

**Comment by chr0m** [comment]
I'm having the same issue with an Oracle Linked Service.
I only want to store the password in the key vault, like I do with my dynamical Azure SQL Database linked service, but for some reason when I do that in Oracle it complains about not being able to store credentials in git and wants to publish immediately.


This is the JSON of the Linked Service and as you can see, there are no credentials there. Is this another bug that I need to wait 3 months for it to be fixed?

{
	"name": "oracle_dynamic_linked_service",
	"type": "Microsoft.DataFactory/factories/linkedservices",
	"properties": {
		"parameters": {
			"ServerName": {
				"type": "string"
			},
			"DatabaseName": {
				"type": "string"
			},
			"UserName": {
				"type": "string"
			},
			"SecretName": {
				"type": "string"
			},
			"BaseURL": {
				"type": "string"
			},
			"Port": {
				"type": "string"
			}
		},
		"annotations": [],
		"type": "Oracle",
		"typeProperties": {
			"connectionString": "host=@{linkedService().ServerName};port=@{linkedService().Port};serviceName=@{linkedService().DatabaseName};user id=@{linkedService().UserName}",
			"password": {
				"type": "AzureKeyVaultSecret",
				"store": {
					"referenceName": "azurekeyvault_dynamic_linked_service",
					"type": "LinkedServiceReference",
					"parameters": {
						"BaseURL": {
							"value": "@linkedService().BaseURL",
							"type": "Expression"
						}
					}
				},
				"secretName": {
					"value": "@linkedService().SecretName",
					"type": "Expression"
				}
			}
		},
		"connectVia": {
			"referenceName": "selfthosted-ir-nonprod",
			"type": "IntegrationRuntimeReference"
		}
	}
}

**Comment by chr0m** [comment]
I'm having the same issue with an Oracle Linked Service.
I only want to store the password in the key vault, like I do with my dynamical Azure SQL Database linked service, but for some reason when I do that in Oracle it complains about not being able to store credentials in git and wants to publish immediately.


This is the JSON of the Linked Service and as you can see, there are no credentials there. Is this another bug that I need to wait 3 months for it to be fixed?

`{
	"name": "oracle_dynamic_linked_service",
	"type": "Microsoft.DataFactory/factories/linkedservices",
	"properties": {
		"parameters": {
			"ServerName": {
				"type": "string"
			},
			"DatabaseName": {
				"type": "string"
			},
			"UserName": {
				"type": "string"
			},
			"SecretName": {
				"type": "string"
			},
			"BaseURL": {
				"type": "string"
			},
			"Port": {
				"type": "string"
			}
		},
		"annotations": [],
		"type": "Oracle",
		"typeProperties": {
			"connectionString": "host=@{linkedService().ServerName};port=@{linkedService().Port};serviceName=@{linkedService().DatabaseName};user id=@{linkedService().UserName}",
			"password": {
				"type": "AzureKeyVaultSecret",
				"store": {
					"referenceName": "azurekeyvault_dynamic_linked_service",
					"type": "LinkedServiceReference",
					"parameters": {
						"BaseURL": {
							"value": "@linkedService().BaseURL",
							"type": "Expression"
						}
					}
				},
				"secretName": {
					"value": "@linkedService().SecretName",
					"type": "Expression"
				}
			}
		},
		"connectVia": {
			"referenceName": "selfthosted-ir-nonprod",
			"type": "IntegrationRuntimeReference"
		}
	}
}`

**Comment by chr0m** [comment]
I'm having the same issue with an Oracle Linked Service.
I only want to store the password in the key vault, like I do with my dynamical Azure SQL Database linked service, but for some reason when I do that in Oracle it complains about not being able to store credentials in git and wants to publish immediately.


This is the JSON of the Linked Service and as you can see, there are no credentials there. Is this another bug that I need to wait 3 months for it to be fixed?

```
{
	"name": "oracle_dynamic_linked_service",
	"type": "Microsoft.DataFactory/factories/linkedservices",
	"properties": {
		"parameters": {
			"ServerName": {
				"type": "string"
			},
			"DatabaseName": {
				"type": "string"
			},
			"UserName": {
				"type": "string"
			},
			"SecretName": {
				"type": "string"
			},
			"BaseURL": {
				"type": "string"
			},
			"Port": {
				"type": "string"
			}
		},
		"annotations": [],
		"type": "Oracle",
		"typeProperties": {
			"connectionString": "host=@{linkedService().ServerName};port=@{linkedService().Port};serviceName=@{linkedService().DatabaseName};user id=@{linkedService().UserName}",
			"password": {
				"type": "AzureKeyVaultSecret",
				"store": {
					"referenceName": "azurekeyvault_dynamic_linked_service",
					"type": "LinkedServiceReference",
					"parameters": {
						"BaseURL": {
							"value": "@linkedService().BaseURL",
							"type": "Expression"
						}
					}
				},
				"secretName": {
					"value": "@linkedService().SecretName",
					"type": "Expression"
				}
			}
		},
		"connectVia": {
			"referenceName": "selfthosted-ir-nonprod",
			"type": "IntegrationRuntimeReference"
		}
	}
}```

**Comment by fhljys** [comment]
This issue is kind of complex because false negative is much worse than false positive. We are taking action incrementally to reduce the risk. Besides of CosmosDB, we fixed some others as well. Given Oracle is mentioned here, we will fix it soon. ETA is the end of next week.

**Comment by fhljys** [comment]
Let's track it with https://github.com/Azure/Azure-DataFactory/issues/371
