### ISSUE TITLE
DelimitedText Encoding UTF-8 results in different behavior than Default(UTF-8)

### ISSUE THREAD

**Issue by dsuarez993** [Azure/Azure-DataFactory#247]
I was trying to create a dynamic dataset for CSV in Data Lake Store Gen2, when I found out this bug.

I was trying to parametrize the encoding from an String parameter, setting UTF-8 as default value, when I noticed this strange behavior.

I decided to debug a bit more until I found out that it was not because the parameter was incorrect or something like that, it was because the Default(UTF-8) encoding does not the same as UTF-8. This problem seems to happen when using the Dataset as a Sink, and doing fine as a Source (I haven't tested this that much, but preview data was working).

Here I attach an image with screenshots of this issue:
![bug](https://user-images.githubusercontent.com/31488342/105822794-c182d780-5fbc-11eb-9c7a-24f5465b5959.png)

I hope you can fix this! Thanks!

**Comment by hbzhxying** [comment]
Hi, @dsuarez993 
Could you help provide the run ids for both runs? If you can provide the sample data of the first row in this file, it will be much helpful for us to trouble shoot.

**Comment by fhljys** [comment]
Close due to inactivity.
