### ISSUE TITLE
Sample pre- and post-deployment script - does not clean up "Managed private endpoints"

### ISSUE THREAD

**Issue by jetnet** [Azure/Azure-DataFactory#250]
we've got issues with the ci-cd deployment script from the [tutorial](https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#script):

```
[error]InvalidResourceRequest: Invalid resource request. Resource type: 'ManagedPrivateEndpoint', Resource name: 'CustomManagedPrivateEndpoint' 'Error: A managed private endpoint to the data source already exist.'.
```

Could you please improve the CI-CD script to handle such cases?
Thanks a lot!

**Comment by jmcallister-msft** [comment]
Hi @jetnet, could you provide a few more details so I can help resolve the issue you are facing? Could explain your CI/CD process a bit more, specifically where the error is coming from? Is it during the pre/post-deployment script execution or the ARM template deployment? Any other information on the behavior you are expecting, factory configuration, logs and/or the ARM template you are deploying would be very helpful.

Something that may be useful from our [documentation](https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#best-practices-for-cicd):

> Managed private endpoint deployment. If a private endpoint already exists in a factory and you try to deploy an ARM template that contains a private endpoint with the same name but with modified properties, the deployment will fail. In other words, you can successfully deploy a private endpoint as long as it has the same properties as the one that already exists in the factory. If any property is different between environments, you can override it by parameterizing that property and providing the respective value during deployment. 

Is it possible that you are trying to deploy a modified MPE? If so, using a different name for the MPE or not modifying properties may be a solution. 

Thanks,
Joe

**Comment by kv50** [comment]
@jetnet,

I`m facing same issue, did you find a solution ?

**Comment by winklevos** [comment]
I'm seeing this issue as well. Looks to be occurring in the ARM template deployment part after the prescript is run
