### ISSUE TITLE
mapping parameter errors when passed as a parameter

### ISSUE THREAD

**Issue by nagasandeep** [Azure/Azure-DataFactory#255]
I have two pipelines, `CopyData `and `CopyData Parameterized`.
Mapping parameter object works fine when triggered on the activity `CopyData`. But when `CopyData` is executed from `CopyData Parameterized` the pipleline errors out with the exact same mapping parameter object.

The mapping parameter object that I used for the below example is 
```
{
	"type": "TabularTranslator",
	"mappings": [
		{
			"source": {
				"name": "TeacherName",
				"type": "string"
			},
			"sink": {
				"name": "StaffName",
				"type": "string"
			}
		}
	]
}
```

```
create table Teacher(
	[TeacherName] nvarchar(max) not null);

create table Staff(
	[StaffName] nvarchar(max) not null);
go

insert into Teacher ([TeacherName]) values ('Foo');
go
```
`CopyData` pipeline is 
```
```
{
    "name": "CopyData",
    "properties": {
        "activities": [
            {
                "name": "Copy data good",
                "type": "Copy",
                "dependsOn": [],
                "policy": {
                    "timeout": "7.00:00:00",
                    "retry": 0,
                    "retryIntervalInSeconds": 30,
                    "secureOutput": false,
                    "secureInput": false
                },
                "userProperties": [],
                "typeProperties": {
                    "source": {
                        "type": "AzureSqlSource",
                        "queryTimeout": "02:00:00",
                        "partitionOption": "None"
                    },
                    "sink": {
                        "type": "AzureSqlSink"
                    },
                    "enableStaging": false,
                    "translator": {
                        "value": "@pipeline().parameters.mapping",
                        "type": "Expression"
                    }
                },
                "inputs": [
                    {
                        "referenceName": "ParameterizedTable",
                        "type": "DatasetReference",
                        "parameters": {
                            "tableName": {
                                "value": "@pipeline().parameters.Source",
                                "type": "Expression"
                            }
                        }
                    }
                ],
                "outputs": [
                    {
                        "referenceName": "ParameterizedTable",
                        "type": "DatasetReference",
                        "parameters": {
                            "tableName": {
                                "value": "@pipeline().parameters.Destination",
                                "type": "Expression"
                            }
                        }
                    }
                ]
            }
        ],
        "parameters": {
            "mapping": {
                "type": "object"
            },
            "Source": {
                "type": "string"
            },
            "Destination": {
                "type": "string"
            }
        },
        "folder": {
            "name": "To Delete"
        },
        "annotations": []
    }
}
```
`CopyData Parameterized` pipeline is
{
    "name": "CopyData Parameterized",
    "properties": {
        "activities": [
            {
                "name": "CopyData",
                "type": "ExecutePipeline",
                "dependsOn": [],
                "userProperties": [],
                "typeProperties": {
                    "pipeline": {
                        "referenceName": "CopyData",
                        "type": "PipelineReference"
                    },
                    "waitOnCompletion": true,
                    "parameters": {
                        "mapping": {
                            "value": "{\n\t\"type\": \"TabularTranslator\",\n\t\"mappings\": [\n\t\t{\n\t\t\t\"source\": {\n\t\t\t\t\"name\": \"TeacherName\",\n\t\t\t\t\"type\": \"string\"\n\t\t\t},\n\t\t\t\"sink\": {\n\t\t\t\t\"name\": \"StaffName\",\n\t\t\t\t\"type\": \"string\"\n\t\t\t}\n\t\t}\n\t]\n}",
                            "type": "Expression"
                        },
                        "Source": "Teacher",
                        "Destination": "Staff"
                    }
                }
            }
        ],
        "annotations": []
    },
    "type": "Microsoft.DataFactory/factories/pipelines"
}
```

With `Source` as `Teacher` and `Destination` as `Staff` `CopyData` works fine but `CopyData Parameterized` gives error 
`Column 'TeacherName' does not exist in the table '[dbo].[Staff]'`

**Comment by fhljys** [comment]
Have you tried to convert your mapping string to a json? https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#json

**Comment by fhljys** [comment]
If it doesn't work, please provide your activity run id.

**Comment by fhljys** [comment]
Close due to inactivity.
