### ISSUE TITLE
Automated publish via npm package @microsoft/azure-data-factory-utilities not working

### ISSUE THREAD

**Issue by Jigar191089** [Azure/Azure-DataFactory#257]
I have datafactory for Development environment. In this datafactory both collaborator and publish branch are kept as master.

I created a feature branch from master and added a new ADF pipeline with one set variable activity in this feature branch. After this generated the arm template from this feature branch using the npm utility.

The ARM template got generated successfully. I also verified that my new ADF pipeline is present in ARMTemplateForFactory.json.

 However are performing the deployment via release pipeline using the above generated ARM template.

I am not able to find the new ADF pipeline in my DataFactory.

 Can you tell me where I may be doing something wrong.

Let me know if you need more information.

**Comment by fhljys** [comment]
Have you checked this Doc? https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment-improvements

**Comment by Jigar191089** [comment]
Yes, i am able to deploy now.
