### ISSUE TITLE
Pipeline run that includes a mapping data flow that references a parameterized table fails to start

### ISSUE THREAD

**Issue by jhoolachan** [Azure/Azure-DataFactory#259]
Hello,

I built a basic pipeline that:

1. reads a list of table names from a configuration table in Azure SQL using a LookUp activity
1. Loops through each table name and executes a mapping data flow
1. The mapping data flow reads data from a CDM folder and copies it into an existing Azure SQL table

To accomplish this, the sink dataset is parameterized to accept the value of the table from the current iteration of the foreach activity. If the data flow name includes spaces ("CDM to SQL DF"), the pipeline debug fails to start with the vague error:

{"code":"BadRequest","message":null,"target":"pipeline//runid/0005f454-9f42-426c-ba66-833e6cfd2632","details":null,"error":null}

If spaces are removed from the data flow name ("CDMtoSQLDF") but nothing else is changed, the pipeline runs without issue.

![pipeline](https://user-images.githubusercontent.com/9311394/111804502-84dda900-88a6-11eb-90bc-0deb130dcf2d.png)
![dataflow1](https://user-images.githubusercontent.com/9311394/111804510-87400300-88a6-11eb-8d1d-edd0867012f2.png)
![dataflow2](https://user-images.githubusercontent.com/9311394/111804526-8ad38a00-88a6-11eb-9632-6bcdba871f36.png)
![dataset](https://user-images.githubusercontent.com/9311394/111804666-a9398580-88a6-11eb-93a6-07fa67e095d2.png)
![error](https://user-images.githubusercontent.com/9311394/111804688-ae96d000-88a6-11eb-92db-05f39e9d49b4.png)

**Comment by syedhamjath** [comment]
The name of the mapping dataflow is used in DataBricks cluster notebook when it is being executed. looks like we can't have space in the name for the nested activities. Is it also the case when you use the mapping data flow activity outside of the for each container with static parameters?
