### ISSUE TITLE
create new store procedure and type in data factory

### ISSUE THREAD

**Issue by kktam** [Azure/Azure-DataFactory#260]
This is a question for the Azure Data factory, and the .net sdk.

When we use CopyData activity and sending output to Azure SQL database, often we require the destination table, a table , a store procedure that can insert into the table, as well as parameter type that the store procedure accepts as well.

It is more useful, and convenient, if the data factory can dynamically create the store procedure and table type, with code the developer provide.  Is there any way the data factory can do this? 

If so, can this also be done in the azure data factory .net sdk? 

SInce the CopyData activity can auto-create table schema if it is missing, and also delete the data in a pipeline. Having dynamic store procedure creation allows this the entire pipeline to be truly dynamic.

**Comment by syedhamjath** [comment]
If the objective of stored proc is to validate the parameter value you can give a try with mapping data flow. Otherwise, I would suggest to create Visual studio SQL database project to create stored procedures and add this project as dependencies in your ADF .NET solution. Before execution deploy DACPAC files in Azure SQL DB and execute ADF pipeline. I hope this should work for you.

**Comment by kktam** [comment]
I am currently using adhoc ADO.net script and store procedure to create dynamically store procedure and types needed for the CopyData activity, and does it inside an Azure function that uses data factory SDK ahead of time. 

I just felt that although the ADO approach worked, it is not as clean, and we need to do a big chunk of the work outside of the Data Factory SDK, and particularly outside the Data Factory pipeline being constructed by the Data Factory SDK.
It would be very nice if Microsoft can turn on this as feature request, and build a stand alone activity type to create all the necessary SQL construct for CopyData.

**Comment by kktam** [comment]
is there any way to dynamically create the code for the DACPAC files, and use Azure functions to execute it before running Data Factory SDK?

**Comment by syedhamjath** [comment]
@kktam You could possibly try the Code generation T4 text template. It has design and runtime support which can generate you a DACPAC file with dynamic code. More info : https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019

Although this has nothing to do with the ADF SDK. I hope you can understand and consider this issue as closed.

**Comment by kktam** [comment]
Advice received.
