### ISSUE TITLE
Misleading error

### ISSUE THREAD

**Issue by nehaagrawal** [Azure/Azure-DataFactory#262]
My current data factory pipeline is failing in prod with below error. The pipeline has many steps and we are unable to understand which step is failing exactly.  In the final step of the pipeline, we write the data to cosmos db. I have copied the error message below.  Since the error has documentClientException, I am assuming that the error happened when it was trying to write to cosmos db.
I have few questions based on the error description
1)We don't have a datetime field so not why below error says issue with date time field.
2) I tried running the pipeline in debug mode but couldn't get more details about the exact error. I also couldn't put a debug point as explained in your doc. https://docs.microsoft.com/en-us/azure/data-factory/iterative-development-debugging
3) The below error also says there is an issue with partition key. So the issue is with partition key or date time? Btw partition key is a string.
4) Is it possible for you to give me more details about this error from logs on your side?

Error: {"StatusCode":"DF-Executor-Conversion","Message":"Job failed due to reason: Converting to a date or time failed due to an invalid character","Details":"Errors encountered in bulk import API execution. PartitionKeyDefinition: {\"paths\":[\"/PartitionKey\"],\"kind\":\"Hash\"}, Number of failures corresponding to exception of type: com.microsoft.azure.documentdb.DocumentClientException = 207; FAILURE: com.microsoft.azure.documentdb.DocumentClientException: {\"Errors\":[\"Encountered exception while executing function. Exception = Error: {\\\"Errors\\\":[\\\"Supplied partition key length 2868 is bigger than maximum allowed 2048.\\\"]}\\r\\nStack trace: Error: {\\\"Errors\\\":[\\\"Supplied partition key length 2868 is bigger than maximum allowed 2048.\\\"]}\\n at createCallback (script.js:6350:26)\\n at Anonymous function (script.js:687:29)\"]}\nActivityId: dfc7225d-8b86-11eb-b767-8b0b01b3558c, Request URI: /apps/XXXX/services/XXX/partitions/XXX/replicas/XXX//, StatusCode: BadRequest, SubStatusCode: 400, \nRequestStartTimeUTC: \"23 Mar 2021 03:21:36.118\", RequestEndTimeUTC: \"23 Mar"}

**Comment by syedhamjath** [comment]
I would suggest to check the mapping in your copy activity or mapping data flow. It looks like there is an incorrect mapping to the partition key. If nothing works please raise a Microsoft Support ticket to get some help.
