### ISSUE TITLE
Azure Rest Service Issue with UTC Datetime

### ISSUE THREAD

**Issue by wazzer2000** [Azure/Azure-DataFactory#267]
I'm using the azure rest service to query an odata API in ADF.  

When querying the entity in Postman,  I am able to see the UTC date  in the following format

 "2021-04-21T17:19:58+01:00". 

However, when I query the API through the Rest Service it returns

"2021-04-21T17:17:58Z."

It looks like it's pushing the time back by 2 hours?.  Normal UTC dates are fine, but it has trouble interpreting UTC dates with time offsets?

**Comment by fhljys** [comment]
Rest service means this one? 
![image](https://user-images.githubusercontent.com/18674958/128032644-5cf427e3-4227-4a13-bbf3-0e9691b64025.png)

**Comment by wazzer2000** [comment]
Hi Fang Liu

Yes, I found a work around by copying the output to azure blob and then
from blob to azure sql.

However if you use the copy task directly, from rest (source) to azure sql
(sink).

The utc dates dont look correct.

I dont have access to the source anymore as I have left  the project i was
working on.

Thanks

Ahmed

**Comment by fhljys** [comment]
Got it. Thanks for replying @wazzer2000 . 
Next time, when you report an issue, please help provide the activity id. 
We will look into it offline and keep monitoring this issue. 
Close it for now and we can re-open it if we got another reporting.
