### ISSUE TITLE
CopyActivity not copying data correctly from DynamicsCRM using FetchXML if columns are sparsely populated

### ISSUE THREAD

**Issue by MattEvansA45** [Azure/Azure-DataFactory#268]
We are using the CopyActivty to extract data from DynamicsCRM using FetchXML as the source query as we need to also retrieve related record values at same time.

We are using a reusable pipeline where we pass in the source FetchXML statement and the sink table name so that a single pipeline can be reused for all similar activities.

However the entity we are extracting data from (bookableresource in this particular instance) has numerous sparsely populated columns (which are included in the Fetchxml statement) and it would appear that when ADF is determining the source schema if that attribute is NULL for however many rows it is scanning in its process to determine the schema, then it is not including that attribute in the source schema even though there are values in that attribute further on in the dataset, and therefore that attribute is not getting mapped and that column is not getting populated in the sink.

I have tried both providing all the column mappings as part of a dynamic mapping setting and also explicitly importing the schemas but as said, the preview/import does not show all attributes if the values are NULL for however many rows its intially scanning to determine the schema.  It really needs to scan/preview the whole dataset to get the full schema.

Example FetchXML
![image](https://user-images.githubusercontent.com/41288088/116397919-12ee6d00-a81f-11eb-887e-e601c675369c.png)

notice how in the preview, atributes such as **contactid** & **bdw_developmentid** are missing, this is because rows where these attributes are populated are not till further in the data set, but fetch xml drops the columns if all rows return NULLs.
![image](https://user-images.githubusercontent.com/41288088/116398324-927c3c00-a81f-11eb-8a30-109637caadcc.png)

Even if i provide a dynamic mapping with all the columns mapped the data is still not populated.  

![image](https://user-images.githubusercontent.com/41288088/116405048-2271b400-a827-11eb-91a6-73c6d38f9dd2.png)

I can only think its because ADF is defining the source schema based on this small scan of the data and ignores the mappings even when rows are returned where these attributes do exist and are populated.  

This is a major oversite, and needs addressing :(

**Comment by Miwa199739** [comment]
Sorry to see you’re running into this issue! The underlying schema detection logic in ADF is to fetch the top 10 rows of data with the specified query, and only return those columns with actual value setting in these 10 rows. This is out of performance consideration since schema detection can be really time-costing if the whole dataset is scanned.
In this specific instance, in order to detect contactid & bdw_developmentid, they should be ensured with values in the top 10 rows.

**Comment by MattEvansA45** [comment]
That's not a solution, you can't **make** the columns have data if they don't have data.

Kingsway soft manages to successfully retrieve the schema/map data from FetchXML with their product so why can't ADF?

**Comment by zhenqxuMSFT** [comment]
@MattEvansA45 
The workaround is to explicitly adding the missing columns in Mappings. You also need to modify the JSON to specify the type of the added column. If this is not working, could you please provide an activity id?
We will keep investigating how to retrieve schema from FetchXML.
If you want to use TDS endpoint, please try with SQL family connectors.

**Comment by wengkeong337** [comment]
Any fix on this issue since it was raise a year ago? I encounter the same issue when using fetchxml in ADF to query Dynamics 365

**Comment by vaclavrek** [comment]
I hit the same issue, when we can expect the solution?

**Comment by fhljys** [comment]
have you checked zhenqxuMSFT's answer?

**Comment by wengkeong337** [comment]
Thanks, I managed to workaround it through explicitly mapping the columns. Just wondering if there is a better fix to this other than doing it manually...if we have hundreds of columns, this is a pain to us.

**Comment by vaclavrek** [comment]
I'm actually not able to make it work even with the explicit mapping. Could you please share some example/code snippet?

**Comment by wengkeong337** [comment]
It just manual mapping like the one attached, no coding needed
![mapping](https://user-images.githubusercontent.com/103630803/165044594-4230af7b-1196-4302-99f2-6779a5203a64.PNG)
d

**Comment by vaclavrek** [comment]
Hmm, this is what I'm doing and still does not work. 
I guess the issue is that my attribute of interest seems like not present in the source ("Column 'abc' may not exist in the source data store...") so I can not put it into the mapping. Even when I do so manually, it's always empty. 
When I connect to Dynamics 365 database like to MSSQL server, I see the attribute and I'm able to query it...
Any clue what may be wrong?
Thanks

**Comment by wengkeong337** [comment]
I supposed you are trying to connect to Dynamics 365 using ADF? In this case are you able to connect to Dynamics 365 successfully using the connector in ADF and preview data? If you are able, then you should be able to see all the attributes

**Comment by vaclavrek** [comment]
Yes, I'm able to connect to Dynamics 365 using ADF connector (Dynamics 365 type) but I do not see some attributes in the preview. 
I see all of them when I connect using db client and SQL connection though...
![image](https://user-images.githubusercontent.com/6087524/166622914-51cac2ef-dfb6-4e6b-a049-8f51d6e242dc.png)

**Comment by wengkeong337** [comment]
Hmm...under ADF Pipeline, what did you use? Table or Query? Usually it is Table that we will use Table to ingest everythin
![ADFSource](https://user-images.githubusercontent.com/103630803/166847557-9b20a8fd-8e28-4efe-a822-a6c0ba0eabd4.png)
g

**Comment by vaclavrek** [comment]
I tried both, table and FetchXML with the same result...

**Comment by wengkeong337** [comment]
Did you try other tables?

**Comment by vaclavrek** [comment]
Yes, 4 (all pretty wide), same result... I'm wondering if there is something like deprecated (unused, hidden, computed...) attributes in Dynamics 365 which would justify them missing in DF preview. 
I'm sort of running out of options how to get these data out...

**Comment by wengkeong337** [comment]
Yup....guess will need to get support from Microsoft

**Comment by GreyDingo** [comment]
Any update on this issue? still seems to be a problem over 2 years later!

**Comment by gpsloveridge** [comment]
Not only is this still an issue, the workaround mentioned above doesn't work. This is me writing a simple FetchXML query to test (industrycode doesn't come through). The custom column "new_industrycode" references "industrycode" which I typed in manually because it doesn't appear on the dropdown.
![image](https://github.com/Azure/Azure-DataFactory/assets/118389510/377efcbb-0c5c-4a9c-982c-fe29482516d9)

When I try to import schemas on the mapping tab, I get this error:
![image](https://github.com/Azure/Azure-DataFactory/assets/118389510/22ea0a15-4bd3-4c9b-908c-d882237f2959)

Without this fixed, Copy Data is taking upwards of 40 minutes on some of these actions and driving DTU/hr costs up significantly.

**Comment by nguyentrieuanduong** [comment]
I got the same issue. I tried to order the data in descending order to fetch the non-null value first.

**Comment by GreyDingo** [comment]
@nguyentrieuanduong @gpsloveridge The way I got around the issue (this may not be an option for you) was to create a dummy row in the source table that has values in all fields to force the schema to be properly previewed/copied. I had to re-write the fetchXML query filter to include the dummy row, and order it in a way so the dummy was row 1. 

In my case I had a datetime field I could use to identify the dummy, but you could use other types.

Here's what it looks like in the ADF expression builder:
![Image](https://github.com/user-attachments/assets/108ca884-cf39-445b-b9fa-dd7c7ba2c7a3)

And the fetch query ends up being something like:
![Image](https://github.com/user-attachments/assets/f4edb92e-1fb5-4f9b-9a07-e05a311e534d)

The dummy row can then be removed in a later step in the pipeline. 

 Not elegant, but it works for me.
