### ISSUE TITLE
Purpose of FactoryId in @microsoft/azure-data-factory-utilities

### ISSUE THREAD

**Issue by shaneholder** [Azure/Azure-DataFactory#270]
Hello,

I've just started working with the package @microsoft/azure-data-factory-utilities for building out my CI/CD pipeline.  I was trying to understand the purpose of the FactoryId parameter and how it is used in the build process.  The subscription, RG and factory name seem to be more of a deployment concern and not a build concern. 

I made the following changes to the resourceId that I used and it appears that the only piece used is the last part of the path (nome) and that is used as the default name of the factory and to name the GlobalParameters.json file.
/subscriptions/do-i-really-matter-atall/resourceGroups/this-rg-does-not-exist/providers/Microsoft.DataFactory/factories/nome

Are there future plans to actually use the subscriptionId and the resource group?

Regards,
Shane

**Comment by jmcallister-msft** [comment]
Hi @shaneholder, thanks for using Azure Data Factory. You are correct that the resource group and subscription id do not currently affect the build output. There are not any plans currently to use these properties, but we included them as they could be useful for future functionality. 

Hope this helps and please me know if you have any other questions!
