### ISSUE TITLE
ODBC Linked Services don't support data write to ODBC correctly

### ISSUE THREAD

**Issue by spowellnet** [Azure/Azure-DataFactory#275]
We have an ODBC linked service (via a self hosted Integration runtime) and we are pushing data out of Azure Synapse into it. We get an error message "count of bad input rows reached maxerrors limit" and no rows are written. We've added the Load Max Errors=0; option to the connection string and now get an error "Failure happened on 'Sink' side. 'Type=Microsoft.DataTransfer.ClientLibrary.Odbc.Exceptions.OdbcException,Message=" and an empty messagae and null data in all the other error

Output looks like this

"errors": [
        {
            "Code": 11000,
            "Message": "Failure happened on 'Sink' side. 'Type=Microsoft.DataTransfer.ClientLibrary.Odbc.Exceptions.OdbcException,Message=,Source=,'",
            "EventType": 0,
            "Category": 5,
            "Data": {
                "FailureInitiator": "Sink"
            },
            "MsgId": null,
            "ExceptionType": null,
            "Source": null,
            "StackTrace": null,
            "InnerEventInfos": []
        }
    ],

The bizarre aspect of this is if we copy single rows it works fine. If we set the batch size to 1 (committing single rows) it also works fine though 15 mins to copy 3000 rows isn't really useable.

Something is obviously very seriously wrong

**Comment by spowellnet** [comment]
After further investigation this seems to be something to do with the parametrized dataset. If we used fixed (hard coded to a single table) datasets the data transfer works fine. As long as we only have 1 connection to the ODBC. We can't set the dataset dynamically so we're going to have to create a datset and pipeline per transfer (there are only 40 of these currently) but our approach for data coming the other way (NZ to Azure) uses a dynamic dataset as we copy data on 1300 or so tables.

**Comment by fhljys** [comment]
Has your issue got resolved?

**Comment by fhljys** [comment]
Close due to inactivity.
