### ISSUE TITLE
Convert PDF to Markdown

### ISSUE THREAD

**Issue by vaughanknight** [Azure/Azure-DataFactory#282]
Not a huge priority, but would be great if the PDF Azure-DataFactory/Metadata driven data ingestion solution in copy data tool/ could be converted to markdown.

Open sourcing a PDF means it can't be edited/diff'd etc.  And PDF's aren't indexed by github the content isn't discoverable, so someone looking for this guidance would have to be sent to it.

**Comment by fhljys** [comment]
Public doc is published. https://docs.microsoft.com/en-us/azure/data-factory/copy-data-tool-metadata-driven
