### ISSUE TITLE
Error: Not able to find model for type - ipeline and subType - undefined

### ISSUE THREAD

**Issue by lotsahelp** [Azure/Azure-DataFactory#288]
Using azure-data-factory-utilities export function and getting the following error.  Thanks,

` WARNING === ModelService: synchronizeInternal - Failed to find model for the resource, ignoring this resource. Error: {"stack":"Error: Not able to find model for type - ipeline and subType - undefined\n    at Function.e.getModelByResourceType (<<myrepo>>\\ADF\\downloads\\main.js:1300:195353)\n    at t.<anonymous> (<<myrepo>>\\ADF\\downloads\\main.js:1058:250689)\n    at <<myrepo>>\\ADF\\downloads\\main.js:16:2243\n    at Object.next (<<myrepo>>\\ADF\\downloads\\main.js:16:2348)\n    at <<myrepo>>\\ADF\\downloads\\main.js:16:1285\n    at new Promise (<anonymous>)\n    at Object.u (<<myrepo>>\\ADF\\downloads\\main.js:16:1030)\n    at t.synchronizeInternal (<<myrepo>>\\ADF\\downloads\\main.js:1058:250195)\n    at t.<anonymous> (<<myrepo>>\\ADF\\downloads\\main.js:1058:246447)\n    at <<myrepo>>\\ADF\\downloads\\main.js:16:2243","message":"Not able to find model for type - ipeline and subType - undefined"}`

**Comment by fhljys** [comment]
@jmcallister-msft could you help?

**Comment by jmcallister-msft** [comment]
Hi @lotsahelp, I am seeing that the error contains what appears to be a typo of pipeline "ipeline." Could you see if your git repository potentially has any folder misnamed as "ipeline" and if so delete it?

Any other information you can provide on your setup would be helpful for debugging. Thanks!
