### ISSUE TITLE
need a config entry for other clouds such as Azure China

### ISSUE THREAD

**Issue by chris-han** [Azure/Azure-DataFactory#293]
AADSTS500011: The resource principal named https://management.core.windows.net/ was not found in the tenant named 87b07dc2-8c24-4a49-b97f-c2b178d2d0c1. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: aa6aaf77-428c-4eed-9e1a-de72c2375400
Correlation ID: 08962119-e0b4-42f2-a4f3-1bf8d43b060c
Timestamp: 2021-06-23 01:33:22Z

**Comment by fhljys** [comment]
Are you using adf.azure.cn?

**Comment by fhljys** [comment]
In mooncake, you should set credential_scopes

![image](https://user-images.githubusercontent.com/18674958/128852230-62b07623-49d1-4d98-a6f9-438eff628679.png)
