### ISSUE TITLE
Automated publish Azure Data Factory

### ISSUE THREAD

**Issue by Dickkieee** [Azure/Azure-DataFactory#297]
Hi,

Having errors when do the build for deployment.

Validate job:

`PublishConfigService: _getLatestPublishConfig - retrieving config file.
 LocalFileClientService: Unable to list files for: integrationRuntime, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/integrationRuntime'
 LocalFileClientService: Unable to list files for: dataset, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/dataset'
 LocalFileClientService: Unable to list files for: trigger, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/trigger'
 LocalFileClientService: Unable to list files for: dataflow, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/dataflow'
 LocalFileClientService: Unable to list files for: credential, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/credential'
 LocalFileClientService: Unable to list files for: managedVirtualNetwork, error: Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/managedVirtualNetwork'`

Validate & Generatie Arm template:

`ERROR === LocalFileClientService: Unable to read file: /home/vsts/work/1/s/arm-template-parameters-definition.json, error: {"stack":"Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/arm-template-parameters-definition.json'","message":"ENOENT: no such file or directory, open '/home/vsts/work/1/s/arm-template-parameters-definition.json'","errno":-2,"code":"ENOENT","syscall":"open","path":"/home/vsts/work/1/s/arm-template-parameters-definition.json"}`

`ERROR === LocalFileClientService: Unable to read file: /home/vsts/work/1/s/arm-template-parameters-definition.json, error: {"stack":"Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/arm-template-parameters-definition.json'","message":"ENOENT: no such file or directory, open '/home/vsts/work/1/s/arm-template-parameters-definition.json'","errno":-2,"code":"ENOENT","syscall":"open","path":"/home/vsts/work/1/s/arm-template-parameters-definition.json"}`

I guess something is wrong with the path in my pipeline

'run build validate $(Build.Repository.LocalPath) /subscriptions/xxxxxxxxxxxxxx/resourceGroups/RG-Dick-DP203/providers/Microsoft.DataFactory/factories/df-testfactory-dev-9999'

Please, need some help on this.

Kind regards,

Dick
[azure-pipelines.txt](https://github.com/Azure/Azure-DataFactory/files/6741142/azure-pipelines.txt)

**Comment by jmcallister-msft** [comment]
Hi @Dickkieee, you are correct that this does appear to be an issue with the path provided. Have you verified that the collaboration branch of your repository is configured and the artifact is downloaded correctly in your pipeline? Another possibility is that you are using a subdirectory to store your adf files inside the repository. If this is the case, you would want to modify the path to be `run build validate $(Build.Repository.LocalPath)/<your-sub-directory> /subscriptions/xxxxxxxxxxxxxx/resourceGroups/RG-Dick-DP203/providers/Microsoft.DataFactory/factories/df-testfactory-dev-9999`

Any other information you can provide about your configuration would be helpful in assisting you. Your `azure-pipelines.txt` does not seem to have any noticeable issues.

**Comment by Dickkieee** [comment]
Thanks @jmcallister-msft , changing the path solved the issue.
