### ISSUE TITLE
BadRequest publishing error when using Azure Synapse Link Model.json dataset

### ISSUE THREAD

**Issue by joegithub** [Azure/Azure-DataFactory#299]
Hello,

Using the "Copy Dataverse data from Azure Data Lake to Azure SQL" template, I've built out a pipeline that uses a ForEach activity to loop an array of names to export unique tables to an Azure SQL database.
The array of names is created from a Lookup activity that references a dataset, and this dataset is a reference to the "model.json" file that is created when connecting a Power Platform Dataverse environment to an Azure Data Lake storage account. 
I parameterized the data flow and SQL dataset to use the value of the ForEach item as the table name when writing to my SQL database.
So the "items" of the ForEach are defined (based on the schema of the model.json file) like this:

> @activity('Lookup Entities').output.value[0].entities

With a "tableName" parameter defined like:

> @item().name

This was tested in a data flow debug session as working, but when I got to the point of publishing my changes I get the following error:

> Error code: BadRequest
Inner error code: BadRequest
Message: The document create or update failed because of invalid json, please ensure that special characters (like $) are not present in payload JSON properties.

This is a snippet of the contents the model.json file:

`{
    "name": "cdm",
    "description": "cdm",
    "version": "1.0",
    "entities":
    [
        {
            "$type": "LocalEntity",
            "name": "mywidget",
            "description": "mywidget",
            "annotations":
            [
                {
                    "name": "Athena:PartitionGranularity",
                    "value": "Month"
                },
                {
                    "name": "Athena:InitialSyncState",
                    "value": "Completed"
                },
                {
                    "name": "Athena:InitialSyncDataCompletedTime",
                    "value": "4/2/2021 8:25:32 PM"
                }
            ],
            "attributes":
            [
                {
                    "name": "Id",
                    "dataType": "guid",
                    "maxLength": -1
                },...`

The "$type" property is just one example where a $ is used in the model.json file. 
I believe this is the source of what is causing the BadRequest error when attempting to publish, but is there anything I can do about it?

Referencing the model.json file seemed like the easiest way to get a complete and current list of all tables being exported from the Azure Synapse Link in Power Platform as opposed to maintaining another list or db table somewhere else.

Is this perhaps a bug with the publish process that will eventually be fixed?
Would you recommend I open an issue with the MS team responsible for the Azure Synapse Link export service that creates the model.json file to see if the use of dollar signs is something that might go away in future versions of the Dataverse export?

Thank you!

**Comment by fhljys** [comment]
Can't reproduce your issue. If possible, please create a support ticket to ADF team and attach the support files. You can download it here. 
![image](https://user-images.githubusercontent.com/18674958/126738215-b744142c-d27d-4015-a0c9-f20d9c2709ed.png)

**Comment by fhljys** [comment]
Close due to inactivity.
