### ISSUE TITLE
Support help with ADF pipeline stuck in provisioning

### ISSUE THREAD

**Issue by guardrex** [Azure/Azure-DataFactory#3]
Hello @spelluru ... ? for you ...

I have an ADF pipeline (GuardRexPipelineRawDataAndProcessing) that seems to be stuck in provisioning. It's been stuck in that state for a few hours now and doesn't look like it's going to recover on its own. I can't access it in the portal; and when I try to delete it, I get this exception:

![exception](https://cloud.githubusercontent.com/assets/1622880/9156292/9f3c05e6-3e9a-11e5-9c6c-635c65ce3505.png)

I don't have a MS Azure support agreement, so nobody will talk to me via Azure tech support. Can you tell me the best way to get a team member to help me with this pipeline?

**Comment by GuardRex** [comment]
... nevermind ... it finally cleared itself with this result ...
```
ENTITY PROVISIONING FAILED: INTERNAL SERVER ERROR.
REQUEST ID: 6FE089FA-0978-4F43-B1BF-411E2F9BDC8E
```

**Comment by Blackbaud-BrandonHay** [comment]
How long did it take? I'm having this same problem. Did you hear from anyone with the Azure team?

**Comment by GuardRex** [comment]
@Blackbaud-BrandonHay I think they did respond a few days later. If I recall correctly, it cleared in 4-6 hours. It was definitely clear by the end of the day. Sorry ... I wish I had better news, but it did take quite a while.

**Comment by jessanmen1** [comment]
Hello,

I think that this topic should be definetely reopened  since we are still being impacted for this topic.
Honestly, I don't see how "I've waited 4-6 hours" is really a solution for this. Please, this is not the first time we have been impacted by this issue.

Hopefully someone will read this and will reopen the issue.

Regards,
Jesús.

**Comment by guardrex** [comment]
I'll reopen to see if the engineers want to comment on it.

**Comment by Jyoti492** [comment]
i see the same issue pending since 3 days

**Comment by dikokob** [comment]
Has the issue been solved?

**Comment by jessanmen1** [comment]
> 
> 
> Has the issue been solved?

Not sure, to be honest. But since there is a new version of Azure Data Factory I would recommend you to move to the new version (if possible). Since we migrated all our pipelines to version 2 we didn't face issues like that (for now)

**Comment by spelluru** [comment]
I am not in the Data Factory team. 

@sharonlo101  - Please review and help when you get a chance. Thanks.

**Comment by fhljys** [comment]
Please use ADF V2. If you still hit this in V1, please create support ticket to Microsoft.
