### ISSUE TITLE
[Feature Request] Allow escaped character or Unicode character definition as custom delimiter in dataset

### ISSUE THREAD

**Issue by sanity-dance** [Azure/Azure-DataFactory#302]
I would like to be able to enter "\t" as a column delimiter when "Edit" is checked, but currently, that causes a "Column delimiter cannot be empty string or multi-character string" validation error. In order to use a tab delimited file, I must either select \t from the dropdown menu or pass in a literal tab character I copied from Notepad into the "Edit" field if I want it to be dynamic.

**Comment by fhljys** [comment]
Given we already provide a dropdown for you, does it not work? (You can also open the json code to modify it as well) The limitation is that if you input \t, it will be escapsed as \\t. Dropdown is the solution we provided.

**Comment by sanity-dance** [comment]
It does not work when I want to create a general-purpose parameterized dataset that can handle different types of files, and need to pass the delimiter from a pipeline.

**Comment by fhljys** [comment]
It depends on how do you pass the value into the parameter. As long as you provide the right value into parameter, it should work. It is not related to the UI.
