### ISSUE TITLE
How to use parameter with Databricks Linked Service?

### ISSUE THREAD

**Issue by kshitijmamgain** [Azure/Azure-DataFactory#307]
I am trying to add parameter to the file path for logs in Databricks cluster. Below is how my configuration looks:
 
![image](https://user-images.githubusercontent.com/56703496/128798140-f08f3d65-a9f1-46e2-99a0-f17043ddf7d9.png)

In my pipeline, I have defined the parameters as below:
![image](https://user-images.githubusercontent.com/56703496/128799005-3e0e24b1-dff9-4fd4-bebe-5d3cd95ade97.png)

Why would one part would not get parameterized? It is passing first parameter correctly but second as a string

![image](https://user-images.githubusercontent.com/56703496/128799237-51e80f5b-757f-4092-9393-d194cbdb827b.png)

**Comment by fhljys** [comment]
Your parameter is not correct. you should use 

dbfs:/@{linkedService().client_name}/logs/@{linkedService().ingestDatetime}
https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#considerations-for-using-functions
![image](https://user-images.githubusercontent.com/18674958/156557408-a3e717fa-b9de-4ab0-a88b-3e26dfb906f1.png)
