### ISSUE TITLE
Issues code of conduct

### ISSUE THREAD

**Issue by OutKa5t** [Azure/Azure-DataFactory#310]
When submitting issues, contributors are directed to review https://github.com/Azure/Azure-DataFactory/blob/08547df71e38c553328a5044637d208c614f279c/CONTRIBUTING.md

However this page links to https://windowsazure.github.com/guidelines.html which returns a 404

**Comment by dcstwh** [comment]
Updated the docs above with the latest links.

**Comment by dcstwh** [comment]
#please-close
