### ISSUE TITLE
Failure happened on 'Sink' side. ErrorCode=SftpPathNotFound,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Can't find SFTP path '/

### ISSUE THREAD

**Issue by sarangnewalkar** [Azure/Azure-DataFactory#320]
Failure happened on 'Sink' side. ErrorCode=SftpPathNotFound,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Can't find SFTP path '/Genesys Sample Call Recordings/callrecordings/00QTLVGRKG8BF9E18AU362LAES06QH9J/00QTLVGRKG8BF9E18AU362LAES06QH9J_2021-08-23_13-34-01-00QTLVGRKG8BF9E18AU362LAES06QH9J_fad2973a343a4fe88ddff263533880df_2021_08_23_13_34_02_4Z58Hvt8RxO1jw780NnUfA.mp4'. Please check if the path exists. If the path you configured does not start with '/', note it is a relative path under the given user's default folder '/'.,Source=Microsoft.DataTransfer.ClientLibrary.SftpConnector,''Type=Renci.SshNet.Common.SftpPathNotFoundException,Message=No such file,Source=Renci.SshNet,'

**Comment by sarangnewalkar** [comment]
I also observed that the file name is too big so tried to sftp from local and its giving the error as no such file.

**Comment by fhljys** [comment]
Close due to inactivity.
