### ISSUE TITLE
InstallGatewayOnLocalMachine is not registering IR

### ISSUE THREAD

**Issue by albertoRamon** [Azure/Azure-DataFactory#324]
Based in the [manual](https://docs.microsoft.com/en-us/azure/data-factory/self-hosted-integration-runtime-automation-scripts) "_InstallGatewayOnLocalMachine.ps1 - The script can be used to install self-hosted integration runtime node and register it with an authentication key._ "

`.\InstallGatewayOnLocalMachine.ps1 "C:\Users\user\Downloads\IntegrationRuntime_5.10.7918.2.msi" -authKey "IR@xx=" -port 8060`

The output said that is OK
![image](https://user-images.githubusercontent.com/15262462/134432567-f7d380c3-1854-46e4-a69d-870b7d79e48c.png)

The install process works OK, but the IR is not registered:
![image](https://user-images.githubusercontent.com/15262462/134432615-1e3fd704-34b2-4180-a9d1-3e7ae18c4129.png)

*  The script is running as Admin
*  If I paste the Key on the UI works OK
*  The host has been restarted several times

**Comment by fhljys** [comment]
Have you tried to close the UI and restart it again? UI needs to read the Registry again after registration.

**Comment by albertoRamon** [comment]
yes, several times, is not working

**Comment by sarath2712** [comment]
Was this issue Fixed? I also have the same problem. It is not getting registered with the authKey. Also additionaly i need to pass the proxy server url and port as well. Is there a way for that as well.

**Comment by albertoRamon** [comment]
Sorry for the delay:
The bug has been fixed and works fine :)

Thanks !!
