### ISSUE TITLE
ADF to Azure function using Azure Function linked service managed identity authentication fails

### ISSUE THREAD

**Issue by sanalkumarp** [Azure/Azure-DataFactory#327]
Steps:
1. Create an Azure function resource and an HTTP function in it
2. Enable Azure AD authentication. 'User Assignment Required' should be turned 'Yes' for the AD application created for the azure function. Also create an application role for the AD app.
3. Create an Azure data factory instance, with managed identity turned on.
4. Assign the ADF managed identity to the application role created above.
5. In ADF, create an Azure Function linked service, with authentication as managed identity.
6. Create a data factory pipeline with and Azure Function activity to invoke the Azure function created above through the Function linked service

Expected: 
The pipeline activity should succeed.

Actual:
The Azure function activity fails with error '401 Unauthorized: You do not have permission to view this directory or page'. 
The call to the same Azure function works using a Web Activity in the pipeline by configuring the function URL and choosing Managed Identity as authentication.

**Comment by fhljys** [comment]
Did you specify resource ID?
