### ISSUE TITLE
Oracle connection fail after latest update of SHIR 5.9.7949.2

### ISSUE THREAD

**Issue by ajern** [Azure/Azure-DataFactory#330]
One of our connections to Oracle DB starts to fail with following error:
Failure happened on 'Source' side. ErrorCode=UserErrorFailedToConnectOdbcSource,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=ERROR [08S01] [Microsoft][ODBC Oracle Wire Protocol driver]Socket closed. ERROR [08001] [Microsoft][ODBC Oracle Wire Protocol driver][Oracle]Connection Dead.

I have checked that I can connect to the Oracle DB from the server that SHIR is running on. The issue has happend i 3 different environments at the same time. We are using servicename setup and is has worked fune until today morning. Looks like the update of SHIR has happend just before the issue appeared

**Comment by fhljys** [comment]
It is a known issue, And we have fixed it. Any version should work now. Thanks!
