### ISSUE TITLE
Require SHIR reference when saving a template

### ISSUE THREAD

**Issue by preethamrajk** [Azure/Azure-DataFactory#335]
While saving a pipeline as a template, I would like to a SHIR block to get added the requires json block.
This would force consumers of this template to select a linked SHIR before importing it.

Desired State in manifest.json
```
	"requires": {
          "integrationRuntimes": {
              "Integration Runtime": {
                  "type": "SelfHosted"                
              }
          }
        }
```

I see that when I add this code manually, it prompts to select an SSIS integration Runtime rather than a SHIR.

**Comment by zhimadaren** [comment]
We only support SSIS integration Runtime selection in template. 

> While saving a pipeline as a template, I would like to a SHIR block to get added the requires json block. This would force consumers of this template to select a linked SHIR before importing it.
> 
> Desired State in manifest.json
> 
> ```
> 	"requires": {
>           "integrationRuntimes": {
>               "Integration Runtime": {
>                   "type": "SelfHosted"                
>               }
>           }
>         }
> ```
> 
> I see that when I add this code manually, it prompts to select an SSIS integration Runtime rather than a SHIR.

When using a template, we only support the choices of Linked Services and SSIS Integration Runtimes because the Linked Service already includes the setting for SHIR. If you want to configure a SHIR, you may select one from the selected Linked Services or from a new created Linked Service.

**Comment by preethamrajk** [comment]
Hi @zhimadaren ,

Thanks for responding. My template doesn't have a linked service.

We are calling an Event Hub using the HTTP activity.

If the template has the ability to feed the SHIR, I can share the template with various EH consumer teams.

**Comment by zhimadaren** [comment]
I see..  We have filed a work item to support SHIR feed. 
Thanks for reporting this to us!

**Comment by preethamrajk** [comment]
Hi @zhimadaren,

Could you please let me know when I can expect this?

**Comment by zhimadaren** [comment]
> Hi @zhimadaren,
> 
> Could you please let me know when I can expect this?

It is expected to be completed in January next year.

**Comment by zhimadaren** [comment]
Hi, @preethamrajk could share your template to us?

**Comment by preethamrajk** [comment]
[EEBPublishEvent.zip](https://github.com/Azure/Azure-DataFactory/files/7825217/EEBPublishEvent.zip)
Please try this

**Comment by zhimadaren** [comment]
Hi, @preethamrajk, updates will be rolled out this week and will be deployed in all regions by the end of this week. Here is a modified template based on yours for your reference
[EEBPublishEvent_withSHIR.zip](https://github.com/Azure/Azure-DataFactory/files/7836745/EEBPublishEvent_withSHIR.zip)
.

**Comment by preethamrajk** [comment]
Thanks a ton for the update.
I shall try this once we have it ready.
