### ISSUE TITLE
Resources Filter gets stuck and can't be changed after Refresh

### ISSUE THREAD

**Issue by dansydner** [Azure/Azure-DataFactory#337]
Steps to reproduce

1. Enter something into the filter field in the Factory Resources part.
2. The Resources list is filtered
3. Hit refresh

The project is refreshed but the filter from step 2 is still in effect, If I remove the search terms the resource list is still filtered.

Removing the filter terms and then hitting refresh let's me see the entire project again.
![image](https://user-images.githubusercontent.com/62622768/142632527-d38194a6-759f-4e96-9d16-e7f49dceb56a.png)

**Comment by fhljys** [comment]
Thanks for reporting it.  Fix will be deployed soon.
