### ISSUE TITLE
Read position delimited file

### ISSUE THREAD

**Issue by xperiandri** [Azure/Azure-DataFactory#346]
What is the recommended way of reading a position delimited file?
I thought about:
1. Converting to a CSV or Parquet
2. Building an ADF component with columns configuration that supports it if it is possible. Is it possible?

**Comment by hbzhxying** [comment]
Do you mean fix width file? We don't support fix-width format in Azure data factory

**Comment by xperiandri** [comment]
Yes, fix width

**Comment by fhljys** [comment]
For feature requests, this is the right place. https://feedback.azure.com/d365community/forum/1219ec2d-6c26-ec11-b6e6-000d3a4f032c
