### ISSUE TITLE
Query Editor in Copy Data Activity throws syntax error for functioning query

### ISSUE THREAD

**Issue by billyswitzer** [Azure/Azure-DataFactory#347]
The query editor in the Source or Sink in the Copy Data Activity throws a syntax error on my query - but the pipeline with the current syntax is currently in Production and functioning correctly.

![ADFCopyDataActivity_QueryError_20211222](https://user-images.githubusercontent.com/47672463/147182895-9c0fb2fd-0667-4fde-a297-85064263de62.png)
.

**Comment by diptigupta2105** [comment]
remove concatenate and use < '@{variables('LastRunDate')}'

**Comment by billyswitzer** [comment]
> remove concatenate and use < '@{variables('LastRunDate')}' let me knowif it works for you

@diptigupta2105 That worked, thanks!
