### ISSUE TITLE
ADF  Get MetaData Activity CSV UTF-8 without BOM invalid encoding type

### ISSUE THREAD

**Issue by chr0m** [Azure/Azure-DataFactory#352]
I'm using ADF Copy Data activity, I select "UTF-8 without BOM" from the Encoding dropdown in the DelimitedText dataset. We also have a Get MetaData activity to get file info for logging and it seems to be failing on that saying that it isn't a valid encoding type. 

The default UTF-8 option creates a file with BOM and the client I am sending the file to can't handle it, so we need it WITHOUT BOM

**Comment by yew** [comment]
@chr0m Thanks for the feedback, we have committed fix to support "UTF-8 without BOM" in Get Metadata activity. Due to Chinese New Year vacation, our deployment is deferred to mid of Feb, I will update here when it is ready in production.

**Comment by fhljys** [comment]
Thanks @yew
