### ISSUE TITLE
ADF Stored Procedure Activity is not saving the parameter value with name id

### ISSUE THREAD

**Issue by mujahid** [Azure/Azure-DataFactory#353]
I have a stored procedure activity which has a parameter named **id** in my pipeline, but when I tried to publish the pipeline the parameter value is not saved. After reloading the pipeline, the value is gone. 

```
PROCEDURE [dbo].[updateLog]
    @id bigint,
    @layer varchar(20),
    @filename varchar(200) = NULL
AS
```

Changing the parameter name from **id** to **fileLogId** saved the parameter value. This issue occurred in the Synapse pipeline.

**Comment by Miwa199739** [comment]
hi @mujahid, we weren't able to reproduce the issue, please see the following screenshot, the 'id' parameter is well saved in out test.

Could you please share detailed repro-steps?

<img width="695" alt="image" src="https://user-images.githubusercontent.com/14820833/150716320-4bb7d960-7ef2-43df-8af1-0783037b6e95.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/14820833/150716462-8f091f64-edcb-496f-9432-208a7a6a4e89.png">

**Comment by fhljys** [comment]
I can reproduce it in Synapse. We are investigating it.
