### ISSUE TITLE
copy activity throws null exception

### ISSUE THREAD

**Issue by tnlthanzeel** [Azure/Azure-DataFactory#355]
I have a pipeline in which i have a copy activity. the copy activity reads from an azure sql db and sinks to an azure sql db. the problem is if the source table has no rows (empty table), the copy activity throws null object reference exception. this happens if i set the write behavior  to **upsert** 

{
    "dataRead": 0,
    "dataWritten": 0,
    "sourcePeakConnections": 1,
    "sinkPeakConnections": 2,
    "rowsRead": 0,
    "rowsCopied": 0,
    "copyDuration": 12,
    "throughput": 0,
    "errors": [
        {
            "Code": 11000,
            "Message": "'Type=System.NullReferenceException,Message=Object reference not set to an instance of an object.,Source=Microsoft.DataTransfer.ClientLibrary,'",
            "EventType": 0,
            "Category": 5,
            "Data": {},
            "MsgId": null,
            "ExceptionType": null,
            "Source": null,
            "StackTrace": null,
            "InnerEventInfos": []
        }
    ],
    "effectiveIntegrationRuntime": "AutoResolveIntegrationRuntime (Central India)",
    "usedDataIntegrationUnits": 4,
    "billingReference": {
        "activityType": "DataMovement",
        "billableDuration": [
            {
                "meterType": "AzureIR",
                "duration": 0.06666666666666667,
                "unit": "DIUHours"
            }
        ]
    },
    "usedParallelCopies": 1,
    "executionDetails": [
        {
            "source": {
                "type": "AzureSqlDatabase",
                "region": "South Central US"
            },
            "sink": {
                "type": "AzureSqlDatabase",
                "region": "Central India"
            },
            "status": "Failed",
            "start": "2022-01-24T04:41:33.7925658Z",
            "duration": 12,
            "usedDataIntegrationUnits": 4,
            "usedParallelCopies": 1,
            "profile": {
                "queue": {
                    "status": "Completed",
                    "duration": 5
                },
                "preCopyScript": {
                    "status": "Completed",
                    "duration": 0
                },
                "transfer": {
                    "status": "Completed",
                    "duration": 6,
                    "details": {
                        "readingFromSource": {
                            "type": "AzureSqlDatabase",
                            "workingDuration": 0,
                            "timeToFirstByte": 1
                        },
                        "writingToInterim": {
                            "type": "AzureSqlDatabase",
                            "workingDuration": 0
                        },
                        "writingToSink": {
                            "type": "AzureSqlDatabase",
                            "workingDuration": 0
                        }
                    }
                }
            },
            "detailedDurations": {
                "queuingDuration": 5,
                "preCopyScriptDuration": 0,
                "timeToFirstByte": 1,
                "transferDuration": 5
            },
            "interimDataWritten": 0,
            "interimRowsCopied": 0
        }
    ],
    "dataConsistencyVerification": {
        "VerificationResult": "NotVerified"
    },
    "durationInQueue": {
        "integrationRuntimeQueue": 0
    }
}

**Comment by seanwang051** [comment]
We identified there is a code bug causing this issue. Will be fixed in a week or two. Thanks for sharing your findings with us.

**Comment by fhljys** [comment]
Fixed.
