### ISSUE TITLE
Dataset with parameter used in data flow with dash in name results in error

### ISSUE THREAD

**Issue by LockTar** [Azure/Azure-DataFactory#356]
When you have a dataset with a parameter. Just a normal string parameter. 
If you use that dataset in a data flow with a dash (-) in the name this will result in an error at runtime.

You will end up with the error:
_ErrorCode=InvalidTemplate, ErrorMessage=The expression 'body('Create silver dataComposeRuntimeVariables')?.**AdoProjects-Silver**ddf7cedaf16f4ea2aaf9cf40d7fc858e?.AdoProjects.ContainerName' is not valid: the string character 'S' at position '63' is not expected."_

So the user interface says it's allowed to use a dash (-) in the name for a data flow. But it's not allowed in a dataset. So above is an bug?

Steps to reproduce:

1. Create dataset AdoProjects 
2. Create parameter on dataset called ContainerName
3. Use dataset in a data flow called AdoProjects-Silver
4. Debug data flow

**Comment by fhljys** [comment]
It is a known issue that “-‘” doesn't work well with parameters. We didn't block it because there are some customers using "-" in their dataflow already and they don't use parameters. 
But we are considering adding a warning for "-". Thanks for reporting it.

**Comment by fhljys** [comment]
We added warnings
