### ISSUE TITLE
keep original filenames

### ISSUE THREAD

**Issue by flomader** [Azure/Azure-DataFactory#36]
I want to copy files from an onprem fileshare to Azure Blob Storage or Data Lake Store.
Since I want to copy all files from a directory I do not specify a filename.
Is there a way to keep the original filenames and extentions? All the files currently end up on wasb or adls with a filename something like Data.9fdb19e7-1f8b-41a5-b77b-7086b0fe1151

Thanks!

**Comment by flomader** [comment]
Finally found it myself:
`"copyBehavior": "PreserveHierarchy"`
in the copy activity did the trick.

**Comment by Guy-Leumi** [comment]
Thanks flomader, really helpful

**Comment by manna018** [comment]
I am (Source)Recursive Copy with Flattened Hierarchy(Sink) so filenames are autogenerated but I want to keep the original name

**Comment by andrewvi7** [comment]
yep, keeping the original names, or having some options in case of duplications when flattening the hierarchy would be amazing...
