### ISSUE TITLE
Unable to create a custom trigger based on event grid domain topics

### ISSUE THREAD

**Issue by preethamrajk** [Azure/Azure-DataFactory#368]
Starting approximately November last year, ADF can trigger pipelines based on event grid events.

However, the limit to creating event grid subscriptions is quickly reaching its limit of 500 subscriptions as it translates to 500 triggers.

We have slightly pivoted our design to use Event Grid domains based on suggestions found on MS documentation website. But this doesn't appear to be implemented as I can't create an event grid subscription based on event grid domain topic. I can neither find the event grid domain/domain topic in the dropdown list, nor can I pass the {resourceId}/domain/{domain name}/topics/{domain topic} directly.

When I pass the latter, I get an error related to storage events - which is not correct.

`You are not authorized to create storage events subscriptions using Event Grid. Please verify that you have the 'Microsoft.EventGrid/EventSubscriptions/Write' permission. Learn more about event trigger here and the required permissions in Data Factory`

**Comment by fhljys** [comment]
Did you register Event resource provider? https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-event-trigger?tabs=data-factory
![image](https://user-images.githubusercontent.com/18674958/159396207-60ae5a9a-1b31-41de-a654-8e3182a4bf8e.png)
