### ISSUE TITLE
ADF uses the work "sink" instead of "sync" in the web user interface.

### ISSUE THREAD

**Issue by jeremy-donson** [Azure/Azure-DataFactory#369]
https://adf.azure.com/en/authoring/pipeline

![Screen Shot 2022-03-28 at 4 41 22 PM](https://user-images.githubusercontent.com/34130568/160484185-f5c90848-961c-4e31-b9ec-d97bdef4a79a.png)

This SOFTWARE ERROR has corresponding doc errors.
They are logged here:  https://github.com/MicrosoftDocs/azure-docs/issues/90525

**Comment by fhljys** [comment]
Sink means "destination", opposite of source, which is by design.

**Comment by jeremy-donson** [comment]
This is accurate.
https://wikidiff.com/sink/sync. 

Do you contest this information?  :)

Also, are you calling the work "sink" a noun or a verb?

**Comment by fhljys** [comment]
I believe we used it as a noun. 
Source is the container for data you read from. 
SInk is the container for data you write into.

**Comment by joshuha-msft** [comment]
As above we use Source and Sink as a noun. The terminology is used in the domains of electrical/electronics/logic controller engineering. You will also see that it's also used by some other large cloud ETL vendors as well.

**Comment by joshuha-msft** [comment]
#please-close
