### ISSUE TITLE
Change Control

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/Azure-DataFactory#37]
What is the typical development cycle for an Azure Data Factory pipeline (mainly from a change-control perspective). Suppose I create a pipeline and it runs for a while, but then it needs a change. How would I do a code-review for the pipeline change?

**Comment by PaulMarshall66** [comment]
You can create pipelines via the Azure portal or there is a data factory template in Visual Studio which allows you to develop them locally, attached to source control, and then publish from Visual Studio or via a Power Shell script.
