### ISSUE TITLE
Case-sensitivity issue in @pipeline().DataFactory when executed via trigger

### ISSUE THREAD

**Issue by billyswitzer** [Azure/Azure-DataFactory#374]
The value returned by the @pipeline().DataFactory variable differs in case from the data factory name when the pipeline is executed via a trigger:

![PracticeRosterLoad_Overnight_202204013](https://user-images.githubusercontent.com/47672463/163192118-17f53448-84cf-4d74-a075-c6496d8c171c.png)

This is causing an error in a downstream activity in the pipeline.

When executed manually the case matches and the pipeline completes successfully:

![image](https://user-images.githubusercontent.com/47672463/163192276-878557e3-c163-4817-a20d-07855bd4159f.png)

**Comment by fhljys** [comment]
Reached out via email.
