### ISSUE TITLE
Strange behaviour convertTimeZone function on data pipeline and activities

### ISSUE THREAD

**Issue by marcusRB** [Azure/Azure-DataFactory#393]
Hi everyone, it seems we are a bug when using a special **conversionTimeZone** function on Copy Data pipeline.

## Steps
- Create new data copy, fille source and sink and using extra column from source .
- In extra column in the value I'm using fetch now() date in my time zone. Example:
```
@convertTimeZone(utcnow(), 'UTC', 'Romance Standard Time', 'yyyy-MM-dd HH:mm:ss')
````
- Deploy and publish and It works , excepted value in this datetime format as `2022-06-06 17:14:07`

But, if I use preview data on debug mode I'm getting an error:

```
Error Message: {
"message": "ErrorCode=InvalidTemplate, ErrorMessage=In the function 'convertTimeZone', the value provided for the time zone id 'Romance Standard Time' was not valid. "
```

So, it seems only work with other timezone format, i.e. 'CET' in my case and I retrieve the data from preview mode.

If I publish with CET instead Romance Standard Time (seen above), I'm getting another kind of error 

```
In the function 'convertTimeZone', the value provided for the time zone id 'CET' was not valid. '.
```

## EXPECTED RESULT

So, to solve it, I need the change CET to 'Romance' and deploy, but If I need to previsualize the data, again I must to change again the value.

Please check timezone format in both cases

SOURCE used: SQL DATABASE, SAP HANA, MYSQL
DATAFACTORY version 2

Thanks

**Comment by hbzhxying** [comment]
Yes, this is a limitation for preview API. For timezone names, please follow https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones#time-zones. If hit error in Preview, please ignore the error. The error won't happen in pipeline run. We will improve the error message to avoid confusion.
