### ISSUE TITLE
Connectionstring for azure sql database linked service is not working as Expected 

### ISSUE THREAD

**Issue by mkasinma** [Azure/Azure-DataFactory#414]
Hi Team,

Currently we are trying to setup the CI/CD pipeline in Azure Data factory to promote the Pipeline from Dev2 to UAT environment using ARM template in the Release setp.

Release pipeline is working based on the ARMTemplateForFactory.json and ARMTemplateParametersForFactory.json and it executed fine .

During the verification when i checked the linked the Service Azure sql database Authentication type is set as Sql Authentication instead of "System Assigned managed identity" but we used connection string as securestring .

We are not sure why by default it is taking this sql Authentication . kindly help me to change the setting to always set the "System Assigned managed identity".

**Comment by fhljys** [comment]
Refer to this doc, https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-resource-manager-custom-parameters#sample-parameterization-template

With this, your connection string will not be wrapped as a secure string. 
![image](https://user-images.githubusercontent.com/18674958/185911619-582e6869-0654-42f9-b054-4e91a3d5508d.png)

**Comment by fhljys** [comment]
If your connection string is wrapped as an secure string, UI will always get "*******"  and can't tell whether there is a user name in your connection string.  Then we default to SQL auth.
