### ISSUE TITLE
DataFlow can't connect to sql (keyvault)

### ISSUE THREAD

**Issue by amirkheirollah** [Azure/Azure-DataFactory#442]
I have a dataflow that reads data from a table in Sql Server (Authentication with KeyVault). The Linked Service connecting successfully in Edit Linked Service page, but it fails for Test Connection (linked service) in Source Settings. It returns an error message:

Spark job failed: {
"text/plain": "{\"runId\":\"XXX",\"sessionId\":\"XXX",\"status\":\"Failed\",\"payload\":{\"statusCode\":400,\"shortMessage\":\"DF-ARG-007 at Connect 'SrcStageXXX'(Line 5/Col 0): store is not defined\",\"detailedMessage\":\"Failure 2022-XX-XX XX:XX:XX.XXX failed DebugManager.processJob, run=XXXX errorMessage=DF-ARG-007 at Connect 'SrcStageXXX'(Line 5/Col 0): store is not defined\"}}\n"
} - RunId: XXXX

  The debug session is running with no issues. Also the Interactive Authoring is enabled. 

The Data Preview returns another error:
Spark job failed: {
"text/plain": "{\"runId\":\"XXXX",\"sessionId\":\"XXXX",\"status\":\"Failed\",\"payload\":{\"statusCode\":400,\"shortMessage\":\"DF-SRC-002 at Source 'SrcStageXXX': 'database' (Database name) is required\\nDF-SRC-002 at Source 'SrcStageXXXX': 'server' (Qualified server name with port) is required\",\"detailedMessage\":\"Failure XXXX-XX-XX XX:XX:XX.XXX failed DebugManager.processJob, run=XXXX, errorMessage=DF-SRC-002 at Source 'SrcStageXXX': 'database' (Database name) is required\\nDF-SRC-002 at Source 'SrcStageXXXX': 'server' (Qualified server name with port) is required\"}}\n"
} - RunId: XXXX

And the Import Schema also does not work and returns the same error: 
Spark job failed: {
"text/plain": "{\"runId\":\"XXXX",\"sessionId\":\"XXXX",\"status\":\"Failed\",\"payload\":{\"statusCode\":400,\"shortMessage\":\"DF-SRC-002 at Source 'SrcStageXXX': 'database' (Database name) is required\\nDF-SRC-002 at Source 'SrcStageXXXX': 'server' (Qualified server name with port) is required\",\"detailedMessage\":\"Failure XXXX-XX-XX XX:XX:XX.XXX failed DebugManager.processJob, run=XXXX, errorMessage=DF-SRC-002 at Source 'SrcStageXXX': 'database' (Database name) is required\\nDF-SRC-002 at Source 'SrcStageXXXX': 'server' (Qualified server name with port) is required\"}}\n"
} - RunId: XXXX

I get the same error with Inline data set query or table settings (the schema and tables names get successfully imported into Table source setting despite failures mentioned above! 

What can be the issue? 

This issue is similar to (https://github.com/Azure/Azure-DataFactory/issues/109) but not exactly the same.

**Comment by seanwang051** [comment]
Hi [amirkheirollah](https://github.com/amirkheirollah)

The first error seems a UX issue. Please try rebuild the dataflow.
The last 2 error seems related to the connection string in the AKV. Could you try use manually edit to test again?
