### ISSUE TITLE
Connect-AzAccount is not working in Azure DevOps CI CD Pipeline

### ISSUE THREAD

**Issue by KANNIBALAMK** [Azure/Azure-DataFactory#462]
I was trying to execute the below powershell while executing the CI CD pipeline through YML:

- task: PowerShell@2    
  displayName: "Disable Trigger"
  inputs:
    targetType: 'filePath'    
    filePath: $(System.DefaultWorkingDirectory)\<foldername>\<foldername>\filescript.ps1
    arguments: '  
    -DataFactoryName "${{ parameters.DataFactoryName }}" 
    -state "Disabled"
    -resourceGroupName "${{ parameters.ResourceGroupName }}"'

**Script:**
Param(
 	[string]$DataFactoryName,
	[string]$state, 
	[string]$resourceGroupName
)
<#
   Possible values for state are Enabled or Disabled
#>
Install-Module Az.DataFactory -Force -AllowClobber
Install-Module Az.Accounts -Force -AllowClobber
Connect-AzAccount 
Write-Host "Netic: Change state for DataFactory Trigger: $DataFactoryName"
$triggersADF = Get-AzDataFactoryV2Trigger -DataFactoryName $DataFactoryName -ResourceGroupName $ResourceGroupName
$triggersADF | ForEach-Object { Stop-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName -Name $_.name -Force -ErrorAction Ignore}
Write-Host "successfully changed state of trigger for DataFactory $DataFactoryName to $state"

CI CD pipeline gets timeout and it's not getting executed.
It was waiting for a long time at Connect-AzAccount statement.

**Note:**  I don't want to pass username/credentials/tenentID etc..  Means, I was executing it through service principal and so I hope those credentials will be taken automatically.

**Comment by BernieWhite** [comment]
@KANNIBALAMK `Connect-AzAccount` is an interactive process by default so it is wating for user input.

You would use something the following to use a service principal with a client secret instead.

```powershell
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $SecuredPassword
Connect-AzAccount -ServicePrincipal -TenantId $TenantId -Credential $Credential
```

However in Azure Pipelines, you should just use a Service Connection by using the Azure PowerShell task instead to run your PowerShell code.

See: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines
