### ISSUE TITLE
PrePostDeploymentScript.Ver2.ps1 fails to parse schedule triggers with only one weekDays definition

### ISSUE THREAD

**Issue by troyel** [Azure/Azure-DataFactory#470]
Input in scheduled trigger template:
```				"schedule": {
					"minutes": [
						0
					],
					"hours": [
						19
					],
					"weekDays": [
						"Sunday"
					]
				}
```

Output from Powershell script when running:
```Getting triggers
WARNING: Failed to compare payload for 'Weekly_Maintenance' trigger
WARNING: Error: Exception calling "Deserialize" with "3" argument(s): "The JSON value could not be converted to System.Collections.Generic.IList`1[System.Nullable`1[Microsoft.Azure.Management.DataFactory.Models.DaysOfWeek]]. Path: $.recurrence.schedule.weekDays | LineNumber: 30 | BytePositionInLine: 19." from Line: 208
```
This is not a problem if I change the trigger definition to contain multiple days, e.g.:

```				"schedule": {
					"minutes": [
						0
					],
					"hours": [
						19
					],
					"weekDays": [
						"Sunday",
						"Monday"
					]
				}
```

**Comment by rockberts** [comment]
Hi @troyel 
View the trigger as Json 
![image](https://user-images.githubusercontent.com/10236235/200591651-3657951a-3c73-4dce-9495-e05e766c1412.png)
And change the day of week from letter to this enum properly
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.daysofweek?view=azure-dotnet

![image](https://user-images.githubusercontent.com/10236235/200591436-805b1674-00c8-4f40-844d-7308f47d98f6.png)

Ps: This is a work around

**Comment by soma-ms** [comment]
@troyel - The issue has been fixed now, please use the latest script.
