### ISSUE TITLE
Integration runtime Failed to get service token from ADF service after update 5.22.8312.1

### ISSUE THREAD

**Issue by jbatterink** [Azure/Azure-DataFactory#478]
Some pipelines in our night run are running into errors suggesting the integration runtime is offline since last friday. I have taken a look at the error logs and what I found is this: 

Error in ADF activity: "Operation on target LookupTables failed: The Self-hosted Integration Runtime '[IR-Name]' is offline, last connect time is '11/21/2022 04:23:29.828 UTC', Self-hosted Integration Runtime id is '[Id]'."

Error in windows log: "Failed to get service token from ADF service with key [Key] and time cost is: 28.6497341 seconds, the error code is: UnexpectedFault, activityId is: [Id] and detailed error message is Processed HTTP request failed."

The error in the windows log is logged 3 times plus a warning. warning and a first initial error then 2 times a retry with the same error message. ![VGA error](https://user-images.githubusercontent.com/118748178/203251830-73e5ba22-20a3-4cc5-b340-8e0039acb752.png)

Yesterday I checked the error and only rebooted the VM, but after this ADF didn't fail even though I see the error in the windows log from time to time. I see this also happening in other customer environments and what the other team is saying is that they see this behavior since the integration runtime update 5.22.8312.1. For now, I have 2 possible solutions worked out, reconnect the integration runtime to ADF with new authentication keys and hopefully the error disappears and if this won't work go back to the last update and wait for a fix and then re-enable auto update.

**Comment by jbatterink** [comment]
Weird thing is that the metric on our side is continuously on 1 on our side. We restart the VM that the intregration runtime is hosted on once a week and on that time, we see the drop, otherwise is shown as active. Makes the error we are getting even weirder. @milicevica23 did you check your windows application log on the machine the IR is hosted on, and do you see the same errors?

**Comment by milicevica23** [comment]
Yea we have the same errors as you described

When you are in the metrics view did you set the minute granularity? 
You can do it in the upper right corner

![image](https://user-images.githubusercontent.com/46800472/203327425-c5361965-232b-49e1-9f4a-848563a0de1c.png)

**Comment by jbatterink** [comment]
Oh you are right! When setting the granularity to 1 minute it's showing the down times. Currently my team is testing if regenerating the IR authentication keys solves the issue.

**Comment by milicevica23** [comment]
Hi is there some update on this issue?

**Comment by jbatterink** [comment]
Resetting the key's helped a lot, we still see the errors from time to time (availability node = 0 on the minute scale). But at this time, it isn't causing any error in the pipeline runs anymore. We did add some addiontal retries with a longer interval period to be sure the process runs through, but all of this feels like a work around and not a definitive fix. There is an IR update I saw, but the release notes don't mention anything about the errors we're facing. For now, we keep the auto update on and keep track of the process and available updates. A colleague tried reaching MS trough twitter, but we've not gotten an update of fix through there as well.

**Comment by milicevica23** [comment]
We still have the same problem as earlier on the minute base. Also tried the new update but it didn't help. 
I just wonder if somebody from microsoft has to say something about this issue? 
@fhljys Can you maybe provide the information that microsoft is aware of the issue?

**Comment by fhljys** [comment]
There was an outage at that time and Microsoft already sent notifications to impacted customers. The issue should have been fixed now.

**Comment by jbatterink** [comment]
Hi @fhljys, 

First of all, I would suggest waiting for conformation that the issue is actually solved before closing the issue. I understand if no response is then given, that you would close the item. I work as a consultant for multiple companies and none of the customer received an update on this. From what time exactly should the issue have been fixed? In my log is still see drops up until yesterday. 

![Log](https://user-images.githubusercontent.com/118748178/205576978-e3e26c91-d50c-44d6-80a2-516279c1187b.png)

Could you send any information about what the issue was and what resulted in a fix?

**Comment by Zengqwei** [comment]
Hi @jbatterink and @milicevica23 ,
This issue is not related to the new SHIR release and resetting key cannot help. There was a service outage on West Europe starting from approximately 15th Nov that ADF service APIs might experience transient big latency at peak times. That's why you see a lot of timeout errors and warning in event logs and the SHIR intermittent offline.
We already sent notifications to impacted customers, and I confirm your subscription was in the impacted list.
Due to Azure deployment frozen for Black Friday and World Cup 2022, we cannot deploy any changes to services. As mitigation, we applied some configuration changes to give more buffer time to bare the "SHIR offline" false alarm at 2022-11-24 08:20:00 UTC. Although you might still see timeout error in event logs, there was no real impact on your activity execution. I don't see there is new activity failure due to this issue on your SHIR since 2022-11-22 00:30:00.
Today after deployment unfreezing, we rolled out the hotfix at 2022-12-05 00:30:00 UTC to fix this API big latency issue. After hotfix, from our telemetry, the API average performance and timeout rate got significantly improved so we think the outage was resolved thoroughly.
Please check your SHIR event logs to see whether the issue is resolved in your side.

**Comment by jbatterink** [comment]
Hi @Zengqwei, 

i've taken a look at our metrics, and we do have some drops in connectivity before the 15th, but from the 18th onwards it was impacting activities. We do recognize improvement from the 24th onwards, suggesting the configuration update did improve the API performance. As shown in the picture in my previous post, since yesterday (2022-11-04 04:32:00 UTC) we don't see any availability issues on the SHIR. This together with our daily activities not being impacted since the 24th suggests this issue is solved. For now, I would like to keep it open until the whole week went through without any issues. I've set a reminder to close the topic next monday. Thanks for the info, and work on the issues! 

Best Regards,

**Comment by jbatterink** [comment]
Issue hasn't returned, so this is fixed!
