### ISSUE TITLE
Flowlets: can I have a flowlet just change the flowlet output columns in my data

### ISSUE THREAD

**Issue by DriesVyvey** [Azure/Azure-DataFactory#499]
I have a generic dataflow that is metadata driven for doing what it has to do.
Within this dataflow, there is logic that I have to repeat several times.  I have put this logic in a flowlet, so the steps in my dataflow are now:
transform1 (2 fixed name columns, 8 drifted columns) ==> flowlet call1 ==> transform2 ==> flowlet call2 ==> transform3.

In the flowlet mapping settings I can do some fixed column mappings for the input that the flowlet needs.  What the flowlet then does is changing the content of some of its 'input' columns, let's say 2 of them.  The changed columns are in the 'output' columns of the flowlet.

What I expected was for my 'transform2' step to still get the 10 columns from 'transform1', 2 that were changed by the flowlet and the other 8 drifted columns.

As this is not the case, the re-useability of flowlets remains limited.
Please let me know if I missed something that makes what I want possible.

**Comment by fhljys** [comment]
This should have been supported now. Please have a try.
