### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ElectricLlama** [Azure/Azure-DataFactory#50]
Perhaps this a newbie question. When I copy/paste into VS Studio Express 2015, nuget the libraries and build I get (among others): "The name 'datasets' does not exist in the current context" on line 74 which makes perfect sense since datasets is not visible inside the function "DeleteBlobFileFolder". Am I missing something? Does this actually compile?

**Comment by fhljys** [comment]
Close this due to inactivity. We can re-open it again if someone else report this issue.
