### ISSUE TITLE
This should have been supported now. Please have a try.

### ISSUE THREAD

**Issue by DriesVyvey** [Azure/Azure-DataFactory#509]
This should have been supported now. Please have a try.

_Originally posted by @fhljys in https://github.com/Azure/Azure-DataFactory/issues/499#issuecomment-1384259314_

Original post was closed while the issue is not resolved.
my additional info:

I see that there is 'allow schema drift' checkbox in the 'input settings' of a flowlet input step, but checking it or unchecking it does not make any difference in the output of the flowlet

**Comment by LoganxDev** [comment]
Hi @DriesVyvey,

Referencing the dataflow in your previous comment, could you try to run a data preview after the first flowlet, you should see all the original columns. Then use the `map drifted` button to create a new derive transformation that will allow you to access all these drifted columns. 

If you are using a data preview on transform 2 and allow schema drift is on but the drifted columns are not showing up that is indeed a bug. Or if you don't see it in your final output.

**Comment by DriesVyvey** [comment]
Hi,

Thanks for your reply.
I ran a data preview after the first flowlet but it doesn't show me the original columns, only the ones that I gave as input to the flowlet and the new columns created by the flowlet.  I tried the 'map drifted' and it only maps the 2 newly created columns.

**Comment by LoganxDev** [comment]
That is quite strange, what is transform1 in your example? Just a source?

Could you post the DSL, or a screenshot of your dataflow for reference?

**Comment by DriesVyvey** [comment]
Hi,

transform1 is not just a source, it is a step that initializes some things.  you can see the data preview of transform1 below (as you can see, already here there are a lot of drifted columns, that's because the dataflow itself has a 'dynamic' source table)
![image](https://user-images.githubusercontent.com/121445466/213092521-748a8b0c-0da7-48e3-a2c2-abe8c87a7311.png)

The data preview of flowlet call1 is as follows
![image](https://user-images.githubusercontent.com/121445466/213093005-0d5f8a8c-47be-4ea8-957f-bb28b674bb8c.png)

I then tried a 'map drifted' from the transform1 data preview to see if it makes any difference.  The data preview after 'map drifted' is (columns are not indicated as being drifted anymore)
![image](https://user-images.githubusercontent.com/121445466/213093966-d649f17b-8aa2-4923-a32e-73f23a13067c.png)

data preview of the flowlet step stays the same
![image](https://user-images.githubusercontent.com/121445466/213103760-a8bc23ff-511f-4086-8c1a-fe483ffbee68.png)

**Comment by LoganxDev** [comment]
Got it, and inside the flowlet are there any select transforms? One limitation is that if anything is done to limit the columns inside the flowlet they will not be able to be carried through to the following transformation.

**Comment by DriesVyvey** [comment]
of course, that's it.  Thanks for the suggestion.  I added a rule based mapping to the select to catch the original columns and it works fine now.

Thank you so much for your help

**Comment by LoganxDev** [comment]
Awesome! Happy to get it working!
