### ISSUE TITLE
Failing SPN Authentication in AzureAnalysisServicesRefresh sample

### ISSUE THREAD

**Issue by ljsons** [Azure/Azure-DataFactory#51]
Attempting to use SPN Authetication in the AAS Refresh Sample. The method "AzureAnalysisServicesProcessSample.ProcessAzureASActivity.GetTabularModel" is throwing NullReferenceExceptions. Debugged code locally and I'm successfully retrieving a token from Azure AD but it fails at the same position. 

The stack trace log from ADF references the directory on my personal machine where the code is stored, not the expected directory from the Azure Batch Cluster. Additionally, the activity works when using regular username and password. This only happens when using SPN Auth.
[AASRefreshStackTrace.txt](https://github.com/Azure/Azure-DataFactory/files/1257786/AASRefreshStackTrace.txt)

**Comment by syedhamjath** [comment]
May be you can check what permission SPN has on the Azure Analysis service.
Follow the below link to check the required SPN permissions :https://cloudblogs.microsoft.com/industry-blog/en-gb/cross-industry/2018/06/22/how-to-automate-processing-your-azure-analysis-services-models/#Step2`

**Comment by fhljys** [comment]
Seems not an ADF issue.
