### ISSUE TITLE
PrePostDeploymentScript fails while trying to stop triggers

### ISSUE THREAD

**Issue by PASSCH1** [Azure/Azure-DataFactory#511]
Since last wednesday the script fails while trying to stop triggers.

The error message I receive is:

[error]...\PrePostDeploymentScript.ps1:470 char:74
+ ... parameterType = $templateParameters.$($parameterName).value ? $templa ...
+                                                                 ~
Unexpected token '?' in expression or statement.
2023-01-18T06:31:58.8943567Z ##[error]PowerShell exited with code '1'.

**Comment by OleksandrShamrai** [comment]
The same issue on our pipelines:

![image](https://user-images.githubusercontent.com/80760264/213461547-88137d8c-ce88-4338-a518-344a82f81b48.png)

**Comment by BjornVanslembrouck** [comment]
Same here...

**Comment by OleksandrShamrai** [comment]
Resolved:

Check your build agent (use the latest):

![image](https://user-images.githubusercontent.com/80760264/213470869-50b68dd1-6911-43c2-84ea-4bc6ce5fb2ca.png)

and check using of PowerShell Core in all steps:

![image](https://user-images.githubusercontent.com/80760264/213470983-18f21e80-d361-45b4-a3c0-c2af3ad03dc1.png)

**Comment by dmenese** [comment]
I'll try with that check. Thanks!

**Comment by PASSCH1** [comment]
@OleksandrShamrai Thanks for the provided solution. With this check the script is running succesfully again.
