### ISSUE TITLE
DeleteFromBlobActivity.cs Contains Build Errors

### ISSUE THREAD

**Issue by screechez** [Azure/Azure-DataFactory#53]
In public void DeleteBlobFileFolder

The name 'datasets' does not exist in the current context.
The name 'logger' does not exist in the current context.
The name 'linkedServices' does not exist in the current context.

**Comment by DavideDelVecchio** [comment]
+1 Same thing happened to me
Env is Microsoft Visual Studio Community 2017 15.7.1

**Comment by fhljys** [comment]
Close this due to inactivity. We can reopen it if someone report it again.
