### ISSUE TITLE
Using azure-data-factory-utilities to export results in ARM template with missing property

### ISSUE THREAD

**Issue by chrish** [Azure/Azure-DataFactory#538]
As part of our CI/CD pipeline in Azure DevOps were exporting the ARM template for a data factory as in the [Yaml-example from the docs](https://learn.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-improvements):

`run build export $(Build.Repository.LocalPath) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.DataFactory/factories/$(factoryName) "ArmTemplate"
`

This results in a good template, containing the following ADF definition:
```
{
	"name": "[variables('dataFactoryName')]",
	"apiVersion": "2018-06-01",
	"type": "Microsoft.DataFactory/factories",
	"location": "[parameters('location')]",
	"identity": {
  	"type": "SystemAssigned"
	},
	"tags": {
		"Environment": "[parameters('tagEnvironment')]",
		"managedBy": "[parameters('tagManagedBy')]",
		"displayName": "[parameters('tagDisplayName')]",
		"description": "[parameters('tagDescription')]"
	},
 	"properties": {
		"globalParameters": {
			"subscription_id": {
				"type": "string",
    				"value": "[subscription().subscriptionId]"
			},
			"resourceGroup": {
				"type": "string",
				"value": "[resourceGroup().name]"
			}
		}
	}
}
```

Our organization requires the use of private endpoints, but for some reason the exported template doesn't include the property `"publicNetworkAccess": "Disabled"`. This is set and can be seen on the ADF in Azure, and can also be seen when viewing the JSON from the Azure Portal. 

Is this a bug, or can this be included with a separate parameter when exporting the template? The current workaround we're leaning towards is to hard-code this as part of the pipeline, but we'd much prefer having it included in the exported template if possible.

**Comment by soma-ms** [comment]
@chrish - We don't recommend including factory resource template as it will result in overridden or losing some properties such as repoConfiguartion, CMK settings, purview configuration, etc. 

I think you might be using 'Include in ARM template (deprecated)' feature in either global parameters or CMK settings that added above factory resource in arm-template. That old mechanism will not include all the factory level properties and is deprecated.
