### ISSUE TITLE
Template Validation workflow fails on pull request.

### ISSUE THREAD

**Issue by prasann** [Azure/Azure-DataFactory#544]
Template validation workflow that runs as part of the `pull_request` fails at the `create_comment` step.

as per the github actions' readme: https://github.com/peter-evans/create-or-update-comment

> Note: In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, Resource not accessible by integration. This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event to comment on pull requests.

Likely, the PRs raised by non-maintainers will be triggered by forks I believe.

Example: https://github.com/Azure/Azure-DataFactory/actions/runs/4280602024/jobs/7452581479 - Failed job

**Comment by ZhiliangLiu** [comment]
Hello @prasann, thank you for reporting this and the fix. I have tried to use `pull_request_target`, but this event is run in the context of the base branch and doesn't contain the newest change, you can find the information [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks). So I choose to not comment when the `pull_request` is triggered by forks. But seems it doesn't work now. And I have fixed it today in this [PR](https://github.com/Azure/Azure-DataFactory/pull/555) and this [PR](https://github.com/Azure/Azure-DataFactory/pull/553). And now I believe it will work as I expected.

**Comment by prasann** [comment]
thanks @ZhiliangLiu  for checking on this. I wasn't aware of the issue you mentioned. happy to close this PR. thanks
