### ISSUE TITLE
How to pass data out from azure batch

### ISSUE THREAD

**Issue by nssidhu** [Azure/Azure-DataFactory#56]
string inputFolderPath = activity.typeProperties.extendedProperties.InputFolderPath;
I see that you can read the value from extendedProperties.

Is it possible to write or update the extended properties so that down stream activities can read from it ?
Or even write to the output ?
so that it can be extracted using statements like this 
 "@{activity('InputOutputTest').output.outpufromBatch}"

**Comment by fhljys** [comment]
What if you make InputFolderPath as a parameter so that you can use the same parameter in your down stream?
