### ISSUE TITLE
Add private link for Azure MySQL Flexible Server to the Azure Database for MySQL linked service

### ISSUE THREAD

**Issue by MrMKJ** [Azure/Azure-DataFactory#570]
We have followed Microsoft's advice and migrated away from the deprecated Azure MySQL Single Server offering, and started using Azure MySQL Flexible Server for hosting our MySQL application databases.  However, we are unable to integrate with these DBs via Azure Data Factory as the support for private link connections has not yet been added to the Azure Database for MySQL linked service.

[See: Copy and transform data in Azure Database for MySQL using Azure Data Factory or Synapse Analytics](https://learn.microsoft.com/en-us/azure/data-factory/connector-azure-database-for-mysql?tabs=data-factory)

![ADF_AzMySQLFS_PE_Error1](https://user-images.githubusercontent.com/40501541/234917065-96c01855-a278-46b9-8a45-4a3fed47fd57.png)

Several of our legacy and 3rd party developed applications do not support SSL encryption, so cannot utilise Public connections and must must rely on private Managed Virtual Network connections. However, we cannot migrated these workloads to Single Server as the creation of new Single Server instances has now been retired.

[See: What's happening to Azure Database for MySQL - Single Server?](https://learn.microsoft.com/en-us/azure/mysql/single-server/whats-happening-to-mysql-single-server)

Please can you confirm when support for Private Link connections via a Managed Virtual Network Integration Runtime will be added to the Azure Database for MySQL linked service connector?

**Comment by fhljys** [comment]
PE for MySQL Flexible server has been released.
