### ISSUE TITLE
Sample for custom activity in Batch Service does not show usage

### ISSUE THREAD

**Issue by devbeard** [Azure/Azure-DataFactory#58]
**Issue**: Non realistic sample in Batch Service

**Comment**: A sample showing how to process data in Batch Service in coop with Data Factory should show actual data processing. There is no loading of data, use of parallelism, and the sample is all in all not very realistic or useful as it is now.

**Comment by fhljys** [comment]
Are you referencing this? https://docs.microsoft.com/en-us/azure/data-factory/transform-data-using-dotnet-custom-activity#custom-activity

**Comment by devbeard** [comment]
Probably, but this was 3 years ago and I don't recall 100%. I of course should have referenced the content I was complaining about. 

I trust ADF is much improved in the last couple of years and will try to get this issue closed.
