### ISSUE TITLE
Reading from empty Gzip file in Azure Data Lake Store hangs pipeline

### ISSUE THREAD

**Issue by Dmcc0123** [Azure/Azure-DataFactory#59]
Using DataFactoryV2 - When a Copy activity is reading from an empty GZIP file in Azure Data Lake Store to write to an Azure SQL sink, the pipeline hangs (will not move forward). Updating the dataset to Compression=None, allows the file to be recognized as empty and read without issue.

Confirmed this behavior when using GZIP, BZIP, and Deflate compression options.  ZipDeflate fails the pipeline with the message "is not a valid Zip file with Deflate compression method".

**Comment by fhljys** [comment]
Are you still hitting this?

**Comment by fhljys** [comment]
Close due to inactivity
