### ISSUE TITLE
Documentation about dynamic folder paths/wild cards

### ISSUE THREAD

**Issue by jamesbascle** [Azure/Azure-DataFactory#6]
Is there a feature for having dynamic folder paths using wild cards, custom partitions, or some other mechanism?

For example "myContainer/myFiles/{Year}/{Month}/{Day}/{CustomerId}/customerdata.json" or 
"myContainer/myFiles/{Year}/{Month}/{Day}/*/customerdata.json" while preserving filename/partitioning key values.

**Comment by gauravmalhot** [comment]
As of now, we don't support wild cards. You can only using the 'SliceStart' and 'SliceEnd' variable for generating dynamic time based values.
