### ISSUE TITLE
ADF Web Activity - Incorrect data send while posting JSON content with Arrays

### ISSUE THREAD

**Issue by codepossible** [Azure/Azure-DataFactory#60]
While trying to perform HTTP post with JSON content with array in the body of the HTTP request, the endpoint receives - System.Collections.Generic.List`1[System.Object] instead of the actual content.

Verified it using combination of ngork, Visual Studio and Azure Functions

![adfinput](https://user-images.githubusercontent.com/18466262/37979406-87b54e0c-31b6-11e8-85c4-84738bb4ae33.PNG)

![endpointreceived](https://user-images.githubusercontent.com/18466262/37979415-8ca59386-31b6-11e8-8236-ffcd264861c9.PNG)

**Comment by fhljys** [comment]
Are you still hitting this? 
Find this in doc; https://docs.microsoft.com/en-us/azure/data-factory/control-flow-web-activity#request-payload-schema
Suppose it should have been fixed 
![Uploading image.png…]()

**Comment by codepossible** [comment]
Thank you for the follow up. I have not looked at the project in a while. Can I get back to you on this?

**Comment by fhljys** [comment]
Of course. Thank you

**Comment by fhljys** [comment]
PG confirmed this has been fixed. They will update docs soon.
