### ISSUE TITLE
Error 1920. Service 'Integration Runtime Service' (DIAHostService) failed to start. Verify that you have sufficient privileges to start system services.

### ISSUE THREAD

**Issue by 310kdf** [Azure/Azure-DataFactory#606]
We're trying to install this in a corporate environment, and Log On As Batch is locked down by group policy. Why is this installer not set up to run as a System first so the installation completes and then allowed to run as a different service account that we designate from active directory?

**Comment by kurt-song** [comment]
Unfortunately, if the service cannot start the UI installation will fail. You may bypass the service start in command line installation.

msiexec /q /i IntegrationRuntime.msi SKIPSTARTSERVICE=1

**Comment by 310kdf** [comment]
Thanks. I will give that a shot.
