### ISSUE TITLE
"Index operation failed; the array index evaluated to null." in Post-deployment script stage running on a Azure Pipeline

### ISSUE THREAD

**Issue by Joalari** [Azure/Azure-DataFactory#608]
I'm currently running this script in a Azure pipeline and it has the following problem in the Post-deployment script stage:

![image](https://github.com/Azure/Azure-DataFactory/assets/143207497/4336c9dd-a1fb-488b-9906-d1b6b901f234)

The lines to which the error refers are:
`$pipeline.Activities | ForEach-Object { Get-PipelineDependency -activity $_ -pipelineNameResourceDict $pipelineNameResourceDict }  | ForEach-Object {
        Push-PipelinesToList -pipeline $pipelineNameResourceDict[$_] -pipelineNameResourceDict $pipelineNameResourceDict -visited $visited -sortedList $sortedList
    }` 
       
 I've tried isolating the code and running it separately, but to no avail and the error remains the same. It has already been verified that the pipelines can be called using the command `Get-AzDataFactoryV2Pipeline -DataFactoryName $DataFactoryName -ResourceGroupName $ResourceGroupName`, but the script doesn't seem to be able to obtain this information.

Thank you in advance for any advice or solutions!

**Comment by Joalari** [comment]
I identified that they were errors in the activities that were poorly constructed within the pipelines.

**Comment by anthonynassar** [comment]
Hello @Joalari, could you please detail what do you mean by poorly constructed? It might help us here.

**Comment by Liszet** [comment]
@Joalari could you please detail how you have fixed this issue, since we are facing the same problem?
