### ISSUE TITLE
inconsistent ARM template schema for Triggers in ADFv2

### ISSUE THREAD

**Issue by isehuet** [Azure/Azure-DataFactory#61]
I hereby request that ARM template schema is aligned for different trigger types. 
For example ScheduleTrigger pipeline reference is
"pipelines": [
{
"pipelineReference": {
"type": "PipelineReference",
"referenceName": "PipelineName"
},
"parameters": {}
}
]

For a tumbling window trigger, the reference is
"pipeline": {
"pipelineReference": {
"type": "PipelineReference",
"referenceName": "PipelineName",
},
"parameters": {}
}
}

Thanks you.

**Comment by fhljys** [comment]
By design. Tumbling window trigger can only trigger one pipeline, which schedule trigger can trigger multiple pipeline. https://docs.microsoft.com/en-us/azure/data-factory/concepts-pipeline-execution-triggers#trigger-type-comparison
