### ISSUE TITLE
DatafactoryManagementClient Method not found

### ISSUE THREAD

**Issue by tausif1809** [Azure/Azure-DataFactory#62]
Hi,

As soon as I add the code snippet below in to my code I get the error below:

`   DataFactoryManagementClient client = new DataFactoryManagementClient(credentials) { SubscriptionId = subscriptionId };`

Method not found: 'Void Microsoft.Azure.Management.DataFactory.DataFactoryManagementClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'.

The full code snippet for the method is below:

                ```
```
string tenantId = "my-tenant-id";
                string clientId = "my-client-id";
                string secretKey = "my-secret-key";
                string subscriptionId = "my-subscription-id";
```

                var context = new AuthenticationContext("https://login.windows.net/" + tenantId);
                ClientCredential clientCredential = new ClientCredential(clientId, secretKey);
                var tokenResponse = await context.AcquireTokenAsync("https://management.azure.com/", clientCredential);
                var accessToken = tokenResponse.AccessToken;

                TokenCredentials credentials = new TokenCredentials(accessToken);
                DataFactoryManagementClient client = new DataFactoryManagementClient(credentials) { SubscriptionId = subscriptionId };
```

Is this a bug? Or am I doing something wrong?

Thanks

**Comment by biashka** [comment]
How did you fix this error? thanks

**Comment by fhljys** [comment]
Close due to inactivity. We can reopen it if someone report it again.
