### ISSUE TITLE
ADF v2 unable to debug pipeline

### ISSUE THREAD

**Issue by tausif1809** [Azure/Azure-DataFactory#64]
Hi,

I get the following error when debugging a newly created pipeline:

{"name":"TimeoutError","stack":"TimeoutError: Timeout has occurred\n    at new t (https://adf.azure.com/main.0254f8f467e8b5ca2d8c.bundle.js:1:3286122)\n    at https://adf.azure.com/main.0254f8f467e8b5ca2d8c.bundle.js:1:3209053\n    at e.U6yM.qe.a.timeout (https://adf.azure.com/main.0254f8f467e8b5ca2d8c.bundle.js:1:3287253)\n    at e.<anonymous> (https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1401040)\n    at https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1366636\n    at Object.next (https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1366741)\n    at https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1365891\n    at new t (https://adf.azure.com/polyfills.9c34bdd62ad81631e216.bundle.js:1:125185)\n    at CnKh.kd (https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1365668)\n    at e._constructSandboxPipeline (https://adf.azure.com/4.11215f27c8fb6d770ab6.chunk.js:1:1400467)","message":"Timeout has occurred","__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

Its a simple pipeline and works when I click on trigger now.

But debug option does nothing and then the error above appears.

Thanks

**Comment by qetza** [comment]
Hi,
I'm getting the same issue since friday when trying to debug a pipeline:

> {"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

Any workaround?

Thanks

**Comment by tausif1809** [comment]
Is this a new pipeline?  I would discard it and log out of azure portal and then back in again and create a new pipeline.

If this isn't I suggest you create a new pipeline as a test and see if you can debug.

Thanks

**Comment by tausif1809** [comment]
I had this problem on a friday also, USQL scripts were also running slow on this day. ADF team must be doing something on their end.. i.e. updates.

**Comment by tausif1809** [comment]
Was this a small change or one that had taken some time. Once I started to SAVE on a regular basis I haven't had any problems since.

**Comment by qetza** [comment]
The change was small, i tend to keep my pipeline shorts so i was able to rewrite it quickly and it's now working. No idea why this happened.

**Comment by joeharker** [comment]
I found that error often happens when the publish phase of the Debug fails.
Try a Publish to see the real error where the Validation fails

**Comment by fhljys** [comment]
Seems the issue has been resolved.
