### ISSUE TITLE
ADF Datasets - HTTP Datastore is missing

### ISSUE THREAD

**Issue by PratikAnkushLad** [Azure/Azure-DataFactory#644]
Under the dataset - HTTP dataset option is missing we can create http linked service but for dataset its not showing http dataset. this can be a bug.

![image](https://github.com/Azure/Azure-DataFactory/assets/98518545/bde62155-bc8b-45b5-b1bb-32cb002b40ed)

**Comment by fhljys** [comment]
Thanks for reporting this. It has been fixed.
