### ISSUE TITLE
Copy data from Blob fields in SQL server to Azure Blob Storage

### ISSUE THREAD

**Issue by alexwilsh** [Azure/Azure-DataFactory#65]
I have a table in SQL Server with the structure similar to this:

```
CREATE TABLE dbo.Documents (
   Id INT IDENTITY
  ,Name VARCHAR(50) NOT NULL
  ,Data IMAGE NOT NULL
 ,CONSTRAINT PK_Documents_DocumentId PRIMARY KEY CLUSTERED (DocumentId)
)
```

I need to extract the data from this table and load it to Azure Blob Storage (this is like a part of migration from on-prem data to cloud) preserving the following structure:

- import-results
   - document-id
     - document-name

where 
- **document-id** is actually id of a document (Id field) from Document table
- **document-name** is name of a document (Name field) from Document table 
- **the content of the blob** is Data field from Document table

Is there a way to achieve this using Data Factory v2?

**Comment by syedhamjath** [comment]
Create a SSIS package to convert Image to base64 or use this link to create base64 column https://social.technet.microsoft.com/wiki/contents/articles/36388.transact-sql-convert-varbinary-to-base64-string-and-vice-versa.aspx

Next, call REST API of storage account to create a blob use the document-id and name as parameter in dataset
https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob
