### ISSUE TITLE
Copy activity mappings not displayed in Dark theme

### ISSUE THREAD

**Issue by ivoburger** [Azure/Azure-DataFactory#653]
It seems quite recently, the dropdown boxes on the Mapping tab changed both the font color and background color to white in the dark theme 
The mapping values are there, you can inspect them in the JSON, it is just not possible to check/edit it on the tab.
![image](https://github.com/Azure/Azure-DataFactory/assets/48688535/9b6e841a-d4e1-4563-821b-c443e62f9d27)

**Comment by ZhiliangLiu** [comment]
Hello @ivoburger, recently we upgraded some dropdown components to provide better user experience, but seems we didn't handle their style well in dark mode. We have fixed it last week and it will apply to all regions by the end of this week.

**Comment by fhljys** [comment]
Fix has been deployed.
