### ISSUE TITLE
@microsoft/azure-data-factory-utilities - validation error: Pipeline has more than the max number of 40 activities allowed per pipeline.

### ISSUE THREAD

**Issue by ranovladimir** [Azure/Azure-DataFactory#659]
Hello,

It's been several weeks now that Microsoft has shared that [they increased the Maximum Activities Per Pipeline from 40 to 80](https://blog.fabric.microsoft.com/en-us/blog/add-up-to-80-activities-to-your-pipeline/)

I use the CI/CD process with Azure DevOps to deploy my ADF. I have followed this [link](https://learn.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-improvements). It auto generates the ARM template and the PrePostDeploymentScript.ps1 script for manage ADF triggers.

But running `npm run build validate <rootFolder> <factoryId>` raise the following error : "CmdApiApp: Resource 'pipeline_test' has the following validation error: Pipeline 'pipeline_test' has more than the max number of 40 activities allowed per pipeline."

I am using the last [@microsoft/azure-data-factory-utilities 1.0.2 version](https://www.npmjs.com/package/@microsoft/azure-data-factory-utilities/v/1.0.2).

When I validate my pipeline via Azure Portal with the "validate template" button I get no errors.

What action should I take to increase the number of activities when calling the npm command ? 

Version:
node: 18.20.1
npm: 10.5.0
@microsoft/azure-data-factory-utilities : 1.0.2
command run from my package.json file : node node_modules/@microsoft/azure-data-factory-utilities/lib/index --preview export /azp/_work/60/s /subscriptions/XXX-xxx-xxx/resourceGroups/xxx-xxx-xxx/providers/Microsoft.DataFactory/factories/xxx-xxx-xxx adf-artifact
 
 Thanks for your help <3

**Comment by ranovladimir** [comment]
Hello @xumou-ms @soma-ms, I see the last update was 6 months ago. Is the increase is implemented in the @microsoft/azure-data-factory-utilities package ?

![image](https://github.com/Azure/Azure-DataFactory/assets/17979737/a636a3a0-2913-4fea-84e5-560a028bf44f)

**Comment by fhljys** [comment]
Should have been fixed.
