### ISSUE TITLE
Fix a typo in Install-Gateway() function

### ISSUE THREAD

**Issue by xupiter** [Azure/Azure-DataFactory#677]
Looks like there is a typo in `SamplesV2 > .. > InstallGatewayOnLocalMachine.ps1 > Install-Gateway()` function:

```
function Install-Gateway([string] $gwPath)
{
... <truncated for brevity> ...
    
    $process = Start-Process "msiexec.exe" "/i $path /quiet /passive" -Wait -PassThru
```
should be
```
    $process = Start-Process "msiexec.exe" "/i $gwPath /quiet /passive" -Wait -PassThru
```

Link: https://github.com/Azure/Azure-DataFactory/blob/main/SamplesV2/SelfHostedIntegrationRuntime/AutomationScripts/InstallGatewayOnLocalMachine.ps1#L24

**Comment by fhljys** [comment]
Fixed by https://github.com/Azure/Azure-DataFactory/pull/636
