### ISSUE TITLE
In ADF facing exceeded 256 parameters 

### ISSUE THREAD

**Issue by kallum3009** [Azure/Azure-DataFactory#684]
We are currently facing issue with adf deployment due to restrictions of 256 parameters limit. Has anyone faced this issue and what are the options available. Looking for help in case anyone has done something to overcome this issue. Any pointers or help will be much appreciated.

**Comment by fhljys** [comment]
https://learn.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-resource-manager-custom-parameters
