### ISSUE TITLE
Public network access for Azure Key Vault is disabled, What is the way to access Key Vault from ADF using private network

### ISSUE THREAD

**Issue by sauvikbiswas94** [Azure/Azure-DataFactory#685]
Previously I have Azure Key Vault and Azure Data Factory publicly accessible. Now for security reason I need to disable public access to Key vault and need to use private endpoints. What is the way to access private endpoint Key Vault from Azure Data Factory

**Comment by fhljys** [comment]
![image](https://github.com/user-attachments/assets/74b327f3-4c8e-4ded-872a-1847d1d9a5cb)
Create a key vault private endpoint and then use managed vnet.
