### ISSUE TITLE
Failing to create authentication headers while creating Rest linked service through PowerShell script

### ISSUE THREAD

**Issue by AmareswarapuBhavani** [Azure/Azure-DataFactory#697]
Failing to create authentication headers while creating Rest linked service through PowerShell script below:

`Set-AzDataFactoryV2LinkedService -ResourceGroupName "<resourceGroupName>" -DataFactoryName "<ADFName>"  -Name "<linkedServiceName>" -DefinitionFile <jsonFileName>`

Linked service is created but headers are not created in linked service,along with that if I created the linked service manually with headers, after refreshing the data factory studio, headers are missing in linked service.

Here is the example issue:https://stackoverflow.com/questions/79091839/definition-file-for-a-an-azdatafactoryv2linkedservice

**Comment by fhljys** [comment]
Headers are created but have been encrypted so it cannot be listed in UI. I believe as long as you have provided the right value, this linked service should work well (test connection, copy, etc.)
