### ISSUE TITLE
How to increment a parameter value inside Until activity in Azure ADF V2

### ISSUE THREAD

**Issue by santhoshkumarmksss** [Azure/Azure-DataFactory#71]
I am looping thorough couple copy activities inside the Until activity in Azure ADF V2, as part of this I am passing "top" as input parameter in the dataset "DS_HTTP_School1" for the "COPY_HTTP_School" activity. Here i want to increment "top" value inside the loop every time by 100 and have to pass the updated value to my API for pagination purpose.

Help me on how to increment this value for each iteration

{
    "name": "PL_DATA_DS_HTTP_TO_BLOB_School2",
    "properties": {
        "description": "PL_DATA_DS_HTTP_TO_BLOB_School1",
        "activities": [
            {
                "name": "Until1",
                "type": "Until",
                "typeProperties": {
                    "expression": {
                        "value": "@activity('COPY_HTTP_School').output",
                        "type": "Expression"
                    },
                    "activities": [
                        {
                            "name": "COPY_HTTP_School",
                            "type": "Copy",
                            "policy": {
                                "timeout": "7.00:00:00",
                                "retry": 3,
                                "retryIntervalInSeconds": 30,
                                "secureOutput": false,
                                "secureInput": false
                            },
                            "typeProperties": {
                                "source": {
                                    "type": "HttpSource",
                                    "httpRequestTimeout": "00:01:40"
                                },
                                "sink": {
                                    "type": "BlobSink"
                                },
                                "enableStaging": false,
                                "dataIntegrationUnits": 0
                            },
                            "inputs": [
                                {
                                    "referenceName": "DS_HTTP_School1",
                                    "type": "DatasetReference",
                                    "parameters": {
                                        "top": 100
                                    }
                                }
                            ],
                            "outputs": [
                                {
                                    "referenceName": "DS_BLOB_Output_School",
                                    "type": "DatasetReference"
                                }
                            ]
                        },
                        {
                            "name": "COPY_School",
                            "type": "Copy",
                            "dependsOn": [
                                {
                                    "activity": "COPY_HTTP_School",
                                    "dependencyConditions": [
                                        "Succeeded"
                                    ]
                                }
                            ],
                            "policy": {
                                "timeout": "7.00:00:00",
                                "retry": 3,
                                "retryIntervalInSeconds": 30,
                                "secureOutput": false,
                                "secureInput": false
                            },
                            "typeProperties": {
                                "source": {
                                    "type": "BlobSource",
                                    "recursive": false
                                },
                                "sink": {
                                    "type": "SqlSink",
                                    "writeBatchSize": 10000
                                },
                                "enableStaging": false,
                                "dataIntegrationUnits": 0,
                                "translator": {
                                    "type": "TabularTranslator",
                                    "columnMappings": {
                                        "schoolid": "SchoolId",
                                        "schoolname": "SchoolName",
                                        "schoolnumber": "SchoolNumber",
                                        "region": "RefRegionId",
                                        "schooltype": "SchoolTypeId",
                                        "authoritytypedesc": "AuthorityTypeDesc",
                                        "email": "Email",
                                        "agreedmaxresourcingroll": "AgreedMaxResourcingRoll",
                                        "schoolstatusdate": "SchoolStatusDate"
                                    }
                                }
                            },
                            "inputs": [
                                {
                                    "referenceName": "DS_BLOB_School",
                                    "type": "DatasetReference"
                                }
                            ],
                            "outputs": [
                                {
                                    "referenceName": "DS_ASQL_School",
                                    "type": "DatasetReference"
                                }
                            ]
                        }
                    ],
                    "timeout": "7.00:00:00"
                }
            }
        ]
    },
    "type": "Microsoft.DataFactory/factories/pipelines"
}

**Comment by fhljys** [comment]
Tried set variable activity? https://docs.microsoft.com/en-us/azure/data-factory/control-flow-set-variable-activity

**Comment by fhljys** [comment]
Close it due to inactivity.
