### ISSUE TITLE
Invalid expresion in logical functions with variables

### ISSUE THREAD

**Issue by jyeros** [Azure/Azure-DataFactory#73]
I got invalid expression error when i try to use the expression

```@greater(variables('x'), variables('y'))```

i got the same error with less, equals and the others logical functions.

**Comment by vinayakmoh** [comment]
I have the same issue, i am unable to use variable in expressions. I got invalid expression.

![image](https://user-images.githubusercontent.com/6029922/51743503-cefde200-20c2-11e9-824e-40accf15ac1b.png)

**Comment by jyeros** [comment]
It was fixed. Thanks
