### ISSUE TITLE
pipeline().Pipeline variable gives GUID with the name

### ISSUE THREAD

**Issue by sergeart** [Azure/Azure-DataFactory#75]
**pipeline().Pipeline** system variable has to return the pipeline name only but now it gives some GUID number with the name like this <pipelineName>9a61de73-a35a-4a22-95ed-256406e0f15a

**Comment by sergeart** [comment]
I cannot reproduce the issue in ADF. Feels like some floating error. Will raise the new issue if I manage to reproduce it. Thanks

**Comment by lotsahelp** [comment]
I can reproduce this issue at will when using a Lookup activity.
