### ISSUE TITLE
Data Factory UI not showing using free subscription

### ISSUE THREAD

**Issue by Alcasser** [Azure/Azure-DataFactory#76]
Hello, I'm having trouble launching the Data Factory UI from Azure Portal.

I'm using a free subscription.

I can create the resource, but when I press "Author & Monitor" the UI doesn't show.

If I open the developer console, the following error is shown:

`ERROR Error: Uncaught (in promise): AADSTS70002: Error validating credentials. AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: 4acd0a65-c1da-414c-b334-b05170022200
Correlation ID: 4349ee60-82dd-4c74-9950-0caffe656237
Timestamp: 2019-01-24 13:21:48Z`

According to this [link](https://azure.microsoft.com/en-us/free/free-account-faq/), the free subscription includes _free low frequency activities with Azure Data Factory_

Thanks.

**Comment by fhljys** [comment]
Is this still repro?
