### ISSUE TITLE
Unable to access key vault key

### ISSUE THREAD

**Issue by ChrisJr** [Azure/Azure-DataFactory#77]
I stored a private RSA key inside key vault, but when trying to retrieve it from data factory it says data factory is unable to retrieve the secret. Is data factory limited to only retrieving secrets? or am I doing something wrong?

Thank you,
Cristian

**Comment by syedhamjath** [comment]
By design ADF can only read secrets for now. Check the below link
https://docs.microsoft.com/en-us/azure/data-factory/store-credentials-in-key-vault#steps
