### ISSUE TITLE
Multiple active dependencies between differents pipelines in ADF V2

### ISSUE THREAD

**Issue by AbdelSolis** [Azure/Azure-DataFactory#79]
Currently ADF V2 only allow once dependencies from activities of different pipelines, so we need create pipelines with differents dependencies to activities in multiples pipelines.

**Comment by syedhamjath** [comment]
Well, the question is not so clear. If its about how to create dependency between pipelines. 
Follow this link : https://docs.microsoft.com/en-us/azure/data-factory/concepts-pipelines-activities#activity-dependency

**Comment by AbdelSolis** [comment]
So, the dependencies explained here: https://docs.microsoft.com/en-us/azure/data-factory/concepts-pipelines-activities#activity-dependency are among activities of the same pipeline, what about activities from different pipelines?
In my case I have multiple activities from one pipeline that depends from multiple activities from another.

**Comment by fhljys** [comment]
@AbdelSolis, have you checked execute pipeline activity? https://docs.microsoft.com/en-us/azure/data-factory/control-flow-execute-pipeline-activity

**Comment by AbdelSolis** [comment]
@fhljys Yes, I have it. I think the best solution to my problem is to use the `Tumbling window` triggers, to create dependencies between pipelines. TY. I think this issue could be closed it.

**Comment by fhljys** [comment]
Good to know. Thanks.
