### ISSUE TITLE
ADF pipeline parameters default values

### ISSUE THREAD

**Issue by mightyblue01** [Azure/Azure-DataFactory#81]
Hi,
Not sure if my understanding is not correct or this is a bug. It's about passing (parameter) values to the ADF pipeline and collecting it. Here is my use case -
I have a pipeline(say P2) with an activity. The pipeline is triggered from another pipeline(say P1) which passes some value to this pipeline that is extracted using @pipeline.parameters().variablename. An example is as follows - 

**Scenario-1**
Define the parameter with default values(click on P2 pipeline and select "New" under "Parameters" tab.)

Name | Type | Default Value
-- | -- | --
paramValue | String | @pipeline().parameters.inputValue

Which results in an error while trying to publish the pipeline. [Error code: BadRequest
Inner error code: BadRequest
Message: Missing parameter definition for inputValue]

**Scenario-2**
Define default value of the parameter with same name as the collecting variable (click on P2 pipeline and select "New" under "Parameters" tab.) -

Name | Type | Default Value
-- | -- | --
paramValue | String | @pipeline().parameters. paramValue

This works. 
Could somebody throw light on how the collecting variable name is related to the parameter value passed to the pipeline. Logically it doesn't make sense.

**Comment by dalmat36** [comment]
See if this is helpful at all: http://blog.pragmaticworks.com/azure-data-factory-v2-parameter-passing

**Comment by fhljys** [comment]
1. Default value can't be expressions. It has to be static value. 
2. For your case, if you are using execute pipelines, you can use it this way:
![image](https://user-images.githubusercontent.com/18674958/110234242-453cc600-7f64-11eb-8cf7-6a41e3125f02.png)
Check execute pipeline activity for more information. https://docs.microsoft.com/en-us/azure/data-factory/control-flow-execute-pipeline-activity
