### ISSUE TITLE
MySQL Date Conversion Issue

### ISSUE THREAD

**Issue by YouLearnSomethingNewEveryDay** [Azure/Azure-DataFactory#83]
This is seems to be an issue with the integration runtime, so if this isn't the right place to put this issue then let me know.

**Background:**
I have a MySQL database that I'm pulling the data from and copying it over to an Azure SQL database. 
The MySQL database has the Data Type of Date (or Timestamp) and the NO_ZERO_DATE mode is disabled, so some of the dates are 0000-00-00. (I have no control over the MySQL datasource structure). 

**Issue:**
When copying from tables with the Data Type of Date I get the following error
`{
    "errorCode": "2200",
    "message": "Failure happened on 'Source' side. 'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Odbc Operation Failed.,Source=Microsoft.DataTransfer.ClientLibrary.Odbc.OdbcConnector,''Type=System.Data.Odbc.OdbcException,Message=ERROR [22018] [Microsoft][Support] (40550) Invalid character value for cast specification.,Source=MySQLODBC_sb64.dll,''Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Odbc Operation Failed.,Source=Microsoft.DataTransfer.ClientLibrary.Odbc.OdbcConnector,''Type=System.Data.Odbc.OdbcException,Message=ERROR [22018] [Microsoft][Support] (40550) Invalid character value for cast specification.,Source=MySQLODBC_sb64.dll,'",
    "failureType": "UserError",
    "target": "Copy_ogj"
}`

**Things I've found when testing:**
If the first few records have 0000-00-00 then the 0000-00-00 values gets read in as NULL (Which is prefer by me) and the data loads in fine.
On tables where the records with 0000-00-00 start at (for example) line 8000, the above ODBC error gets thrown. 
If I make the source ADF Dataset Data Type of string it looks like ODBC still reads the data as datetime and throws the same error. 
I tried an ORDER BY in my SELECT statement but that only worked with tables with just a single Date column. 

My current solution is modifying my SELECT statement to CAST the Date types as string and then the data reads in just fine. 

**My Questions:**
Is there a way to make the integration runtime to either force the 0000-00-00 to become NULL or to have it read in the MySQL Data as the Data Types defined on the ADF DataSet (So I don't have to cast every Date column in my SELECT statement)?

**Comment by fhljys** [comment]
Are you still experiencing this?

**Comment by YouLearnSomethingNewEveryDay** [comment]
@fhljys Sorry but I don't know. The source business moved away from MySQL about a year ago.

**Comment by fhljys** [comment]
@YouLearnSomethingNewEveryDay thanks for your update. Then maybe let's close this first and we can reopen it if there are other reportings.

**Comment by lmorilloPiper** [comment]
Hi!

I am experiencing this too. In my case the error is: 

```bash
Operation on target Copy data failed: Failure happened on 'Source' side.
ErrorCode=UserErrorUnclassifiedError,
'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException, Message=Odbc Operation Failed.,
Source=Microsoft.DataTransfer.ClientLibrary.Odbc.OdbcConnector, ''Type=System.ArgumentOutOfRangeException,
Message=Year, Month, and Day parameters describe an un-representable DateTime.,Source=mscorlib,'
```
From the error message I guess this is a .NET program. Following [MySQL docs](https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html) I've set property `AllowZeroDateTime` to 1 in the connection string. It didn't help, I've also tried `ZERO_DATE_TO_MIN` from [obdc docs](https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html) with same errors.

The work around is manually write queries to cast the datetime values, but that is a mess if you have hundreds of tables to copy...
