### ISSUE TITLE
Cannot update a value in a table using UPDATE QUERY 

### ISSUE THREAD

**Issue by nivebiju** [Azure/Azure-DataFactory#86]
Am using Copy Activity where I want to update a value after the complete process gets over. So, in order to update a value, am using an UPDATE query. Actually it updates the value in a table but it fails the activity with the following ERROR : 
"errorCode": "2200",
"message": "Failure happened on 'Source' side. ErrorCode=UserErrorInvalidDbQueryString,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException, **Message=The specified SQL Query is not valid. It could be caused by that the query doesn't return any data. Invalid query: 'UPDATE  tablename SET column1 = getdate() WHERE column2 = ' ' and column3= ' '**.Source=Microsoft.DataTransfer.ClientLibrary,'", 
"failureType": "UserError",
"target": "Copy Data 1"
Is it possible to update a query with a success status in COPY ACTIVITY ??

**Comment by nivebiju** [comment]
It is better to use Stored Procedure for Upsert (Update and Insert) activities.

**Comment by RaghuVarmaS** [comment]
you can also use lookup activity for this. you just write sequence of queries in it. But in the last statement you can keep select 1 as x;

**Comment by Rohitkulkarni77** [comment]
> Am using Copy Activity where I want to update a value after the complete process gets over. So, in order to update a value, am using an UPDATE query. Actually it updates the value in a table but it fails the activity with the following ERROR :
> "errorCode": "2200",
> "message": "Failure happened on 'Source' side. ErrorCode=UserErrorInvalidDbQueryString,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException, **Message=The specified SQL Query is not valid. It could be caused by that the query doesn't return any data. Invalid query: 'UPDATE tablename SET column1 = getdate() WHERE column2 = ' ' and column3= ' '**.Source=Microsoft.DataTransfer.ClientLibrary,'",
> "failureType": "UserError",
> "target": "Copy Data 1"
> Is it possible to update a query with a success status in COPY ACTIVITY ??

Are you using the SQL POOL DATABASE.

**Comment by fhljys** [comment]
Chain a stored procedure activity after copy activity to update value should be the recommended way.
