### ISSUE TITLE
In ADF V2 ForEach Activity is triggering in parallel despite of selecting sequential.

### ISSUE THREAD

**Issue by RaghuVarmaS** [Azure/Azure-DataFactory#92]
I am triggering a pipeline inside a foreach activity for array of dates. I have used sequence option to trigger it one by one.

When I run the main pipeline which has foreach activity it is triggering the inner activity in parallel for all the dates in array.

**Comment by manish-jain-alept** [comment]
I also have this issue, with the copy files data to table.

**Comment by syedhamjath** [comment]
Check the code of pipeline using PowerShell or redeploy the pipeline with only IsSequential property and remove the batch property. If possible, share the pipeline code.

**Comment by fhljys** [comment]
Close it due to inactivity.
