### ISSUE TITLE
Copy Data Activity for SQL azure errors on varbinary(max) field when staging is enabled

### ISSUE THREAD

**Issue by jebbisson** [Azure/Azure-DataFactory#94]
Error:
`ErrorCode=FailedDbOperation,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=A database operation failed with the following error: &apos;Implicit conversion from data type nvarchar(max) to varbinary(max) is not allowed. Use the CONVERT function to run this query.&apos;,Source=,''Type=System.Data.SqlClient.SqlException,Message=Implicit conversion from data type nvarchar(max) to varbinary(max) is not allowed. Use the CONVERT function to run this query.,Source=.Net SqlClient Data Provider,SqlErrorNumber=257,Class=16,ErrorCode=-2146232060,State=3,Errors=[{Class=16,Number=257,State=3,Message=Implicit conversion from data type nvarchar(max) to varbinary(max) is not allowed. Use the CONVERT function to run this query.,},],'`

I am using the Copy Data activity with out explicitly specifying a schema.
This seems to work for most tables and columns, but appears to not be working for varbinary fields.
All the tables with varbinary are failing for me.
I've checked the schema on both source and destination and both appear to be the same, data types and sizes, order of fields.

I have been able to isolate which step along the way appears to be failing.
I've setup a test where all steps are dynamic up until the Sink's Data service connection.
When I create a dataset destination with a service connection that has no schema specific table it will fail.
However, once I manually import the schema the entire pipeline succeeds and I get data in my table.
When I use variable table the schema can't be imported for it so that will also fails here with the same error.

Now it does seem that If I disable blob staging my test pipeline seems to work for my test case that fails.
So it seems to be triggered by blob staging, though it can be reversed by manually specifying the schema and creating separate data sets for each target table.

Let me know if you need more information or specific pipeline definitions.

**Comment by fhljys** [comment]
Is this resolved?

**Comment by fhljys** [comment]
Close due to inactivity
