### ISSUE TITLE
Dataset Parameters / Breaking change with pipeline parameters

### ISSUE THREAD

**Issue by dmihos** [Azure/Azure-DataFactory#95]
Hi
It seems the change with dataset parameters is now obligatory.

You can no longer publish any change unless ALL your datasets stop using @pipeline.parameters. Or you'll get the validation error "Pipeline parameters can only be used within their defining pipeline. Define dataset parameters to accept the pipeline parameter values instead"

Is it so or is this maybe a bug that we expect to be addressed soon?

**Comment by syedhamjath** [comment]
It is by design, forward we have us @dataset instead of @pipeline
