### ISSUE TITLE
Auto-Start Trigger - Release using ARM template

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-DataFactory#98]
Hi,

Is it possible to automatically start Triggers when releasing through ARM templates? It seems that the only way I can achieve this is through powershell, but I would rather have a single process. 

I could not seem to find any documentation for this.

Thanks in advance!

**Comment by syedhamjath** [comment]
It is recommended to pause trigger before deployment and resume after deployment. We have script to do this activity, check this link : https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment
