### ISSUE TITLE
Manifest.json reference

### ISSUE THREAD

**Issue by pjeannet-dior** [Azure/Azure-DataFactory#99]
Hello,

I'm trying to edit a template generated from an existing pipeline. I edited the ARM template part just fine, adding several parameters like container name for a blob storage or the name for the output pipeline. However I can't get any language reference for manifest.json that would help me create the template creation form that is then displayed in the data factory UI. 
One of the thing I want is having string inputs instead of dropdowns and connect them to the ARM parameters.

**Comment by fhljys** [comment]
What's your scenario?

**Comment by fhljys** [comment]
Close due to inactivity.
